### ISSUE TITLE
Exit Code

### ISSUE THREAD

**Issue by adrianromanko** [jsdoc3/jsdoc#1000]
jsdoc silently fails on Windows 7, node v0.12.2.
This is not a parsing error; note that there >1000 .js files and the Windows error '3221225477 ' complains about a memory access violation.
![image](https://cloud.githubusercontent.com/assets/3165356/7479647/07d867b2-f331-11e4-8a36-35ffc33568f7.png)

**Comment by hegemonic** [comment]
Can you reproduce this by running JSDoc from the command line (that is, not through gulp-shell)?

**Comment by hegemonic** [comment]
Closing due to lack of information.

**Comment by adrianromanko** [comment]
Sorry.

I can reproduct this directly from the command line using
"node_modules\.bin\jsdoc\ Scripts\R2CIQ -r -d docs --debug --verbose"

It fails silently without showing an error. After parsing about 100 files it fails with a ...
![image](https://cloud.githubusercontent.com/assets/3165356/7657374/6f256264-faff-11e4-8a0a-e37a7406f385.png)

The previous error using gulp-shell was more descriptive.

**Comment by hegemonic** [comment]
What version of JSDoc are you using? Also, can you provide access to the files you're running through JSDoc?

**Comment by adrianromanko** [comment]
JSDoc 3.3.0, I shared a private repo with a sample file.

**Comment by hegemonic** [comment]
Thanks, @adrianromanko. I'll investigate.

**Comment by hegemonic** [comment]
After looking into this, I strongly suspect that you were running into bug #976. This bug is fixed in JSDoc 3.3.2, which I just released. Please upgrade to JSDoc 3.3.2 and see if you still run into this problem.
