### ISSUE TITLE
Declaring same @module in multiple files got duplication of classes on that module

### ISSUE THREAD

**Issue by buzzzzer** [jsdoc3/jsdoc#1002]
Example:
fileone.js
```javascript
'use strict';
/**
 * @module Samplemodule
 */

/**
 * @class SomeClass1
 */
class SomeClass1  {
    constructor() {
    }
}
```
file2.js
```javascript
'use strict';
/**
 * @module Samplemodule
 */

/**
 * @class SomeClass2
 */
class SomeClass2  {
    constructor() {
    }
}
```
If i click on Module>Samplemodule  i got two classes sections
![err](https://cloud.githubusercontent.com/assets/1981785/7580950/dc28eca4-f885-11e4-90a5-2dcba5eacba9.PNG)

**Comment by hegemonic** [comment]
This is the expected behavior, because you've effectively documented the module twice.

The solution is to document the module once, in `file1.js`, and change `file2.js` to look like this:

```js
'use strict';
/**
 * @class SomeClass2
 * @memberof module:Samplemodule
 */
class SomeClass2  {
    constructor() {
    }
}
```

**Comment by buzzzzer** [comment]
but if i declare "@memberof module:Samplemodule" instead of "@module Samplemodule" i dont see any methods & etc of that class
```javascript
/**
 * @class SomeClass2
 * @memberof module:Samplemodule
 */
class SomeClass2  {
    /**
     *
     * @param {Number} somevar
     */
    constructor(somevar) {
    }

    /**
     *
     * @param {Number} somevar
     */
    someNotVisibleMethod(somevar){
    }
}
```
with @module Samplemodule  someNotVisibleMethod Visible

**Comment by SunboX** [comment]
Came across the same issue. It's a bit annoying

**Comment by seanmcilvenna** [comment]
This also occurs if your jsdoc config is setup with multiple source includes and the recursive flag pointing to the same location. For example:

```
"source": {
  "include": [
    "client/js/controllers",
    "client/js/"
  ]
}
```

If I run jsdoc with -r (recursive) using this config file, it will parse the controllers directory twice, producing duplicate documentation.

**Comment by danielo515** [comment]
This is also happening to me, I think I have opened a duplicated issue though #1325

**Comment by danielo515** [comment]
Why is this closed if the problem persist?

**Comment by ajxs** [comment]
Issue still persists.

**Comment by Mikkal24** [comment]
Sean's solution solved this for me. I was running jsdoc projectName -c conf.json -r 

But, I was also including it in my conf.json so it was essentially running twice. Just wanted to add some validity to his suggestion should anyone else be doing the same thing.

**Comment by joshuarobs** [comment]
Still getting this issue as of 2020, tried removing the "include" but didn't work
