### ISSUE TITLE
{@link <url>} not parsing correctly

### ISSUE THREAD

**Issue by Askelkana** [jsdoc3/jsdoc#1004]
A jsdoc comment of the form

    {@link http://api.jquery.com/category/deferred-object/}

fails to parse correctly. Getting the error

    "Unable to parse <a..."

which would indicate that the link is actually being generated, but is then failing afterwards.

**Comment by hegemonic** [comment]
I can't reproduce this issue. What version of JSDoc are you using?

**Comment by hegemonic** [comment]
Closing due to lack of information. I suspect you're running into a bug that was fixed in the final release of JSDoc 3.3.0. If you're using an alpha or beta version of JSDoc, try upgrading.
