### ISSUE TITLE
templates/haruki json ouput broken

### ISSUE THREAD

**Issue by ajax16384** [jsdoc3/jsdoc#1005]
jsdoc -t templates/haruki json output works only if "--debug" option specified.
without "--debug" jsdoc throws:
org.mozilla.javascript.EcmaError: TypeError: Cannot find function dump in object [object JavaImporter].
        at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3689)
        at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3667)
        at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:3695)

it seems global.dump defined only in debug mode:
JSDoc\jsdoc.js
    if (env.opts.debug) {
....        global.dump = function() {

**Comment by hegemonic** [comment]
Thanks for the heads up! I'll fix this bug and release a new version that includes the fix.

**Comment by atomicpages** [comment]
@ajax16384 you can replace `global.dump(root)` with `console.log(root)` without object expansion. Put a hotfix here https://github.com/jsdoc3/jsdoc/pull/1020

**Comment by hegemonic** [comment]
Fixed on master and releases/3.3. The fix will be included in JSDoc 3.3.1.
