### ISSUE TITLE
Methods in class/module, inconsistent behavior

### ISSUE THREAD

**Issue by enuggetry** [jsdoc3/jsdoc#1007]
I'm getting inconsistent results with method documentation in classes and modules.  Sometimes the method docs show in the module page while methods show in the class page.

In this example, I methods for the class don't show in the class doc unless I add @methodof. Why?
http://jbrowse.org/api/Util.html
Sure, I can add @methodof, but why don't they just show like the example below where @methodof is not used at all?

The next is a dojo AMD module with both @module and @class (same js file).  Some method show in the module doc, some methods show in the class doc.  Why? 
http://jbrowse.org/api/module-JBrowse_View_Track_HTMLFeatures.html
http://jbrowse.org/api/JBrowse.View.Track.HTMLFeatures.html
I've tried about every combination of @class and @constructs/@constructor I can think of to no avail.
What is the criteria for the methods showing in the class doc versus the module doc.

In fact, unless @methodof is used, many methods end up in the Global list.

Also since @class HTMLFeatures is defined the @constructs seems to still require a name @constructs HTMLFeatures.  Omitting it causes the compiler to complain.  This seems to be contrary much documentation I've read. The name shouldn't be required on the @constructs tag if it's included on the @class tag.

Using 3.3.0

**Comment by hegemonic** [comment]
That's a lot of questions to answer all at once, so I'm going to focus on your first question.

Is there a reason why `Util` isn't documented as a module? If it is, in fact, a module, you could document it as shown in [this example from the docs](http://usejsdoc.org/howto-amd-modules.html#function-that-returns-an-object-literal).

**Comment by hegemonic** [comment]
Closing due to lack of response.

If you still have questions, please email the [jsdoc-users mailing list](http://groups.google.com/group/jsdoc-users). The GitHub issue tracker is for bugs and feature requests. Thanks!
