### ISSUE TITLE
Help needed to run jsdoc in node

### ISSUE THREAD

**Issue by astoilkov** [jsdoc3/jsdoc#1008]
I am trying to run jsdoc in node and only access the parsed data so I can create a JSON format from it. I am trying to access a parser for example which returns a structured data type that I can play around with. I am just asking if this is possible and any guidance on the issue will be highly valuable.

In my opinion this should be built-in because it will open a lot of interesting possibilities. API like in the example below will be so powerful:
```javascript
var jsdocParser = require('jsdoc').Parser;
jsdocParser.parse(code, {
   // events here
   onparse: function (data, node) {
       // data for the current parsed comment
       // node is the Esprima node so you could attach additional code to a method for example
   }
});
```

Thanks in advance.

**Comment by hegemonic** [comment]
You can use the [jsdoc3-parser package](https://www.npmjs.com/package/jsdoc3-parser) to get all of the parse results as a JSON blob. If you want direct access to AST nodes, you can [write a node-visitor plugin](http://usejsdoc.org/about-plugins.html#node-visitors).

(In the future, please send questions to the [jsdoc-users mailing list](http://groups.google.com/group/jsdoc-users). The GitHub issue tracker is for bug reports and feature requests. Thanks!)
