### ISSUE TITLE
Syntax for iterables?

### ISSUE THREAD

**Issue by mzgol** [jsdoc3/jsdoc#1009]
In ES6 it'd be useful to declare a particular function accepts any iterable structure so that I can write:
```js
/**
  * Returns a concatenated string of all the values.
  * @param {Iterable.<string>}
  */
function f(iterable) {
    let ret = '';
    for (const s of iterable) {
        ret += s;
    }
    return s;
}
```
Now, `Iterable` is no special syntax here and it won't match `Array`/`Set`/`Map` or an object with a custom `object[Symbol.iterator]`defined, IDEs won't recognize valid input etc.

Is there any way to specify this? Maybe a new syntax is needed?

**Comment by mzgol** [comment]
WebStorm has its own files definining stubs for ES5/ES6 functions with jsdocs for their param suggesting, it looks like this:
```js
/**
@param [iterable]
@constructor
@template K, V
*/
function Map(iterable) {}
```
There is no type defined for the `iterable` param. It should be possible to do better.

**Comment by hegemonic** [comment]
Hmmmm. I'm not sure what the right solution is here. I agree that we may need new syntax for this. I'm open to suggestions.

(I should warn you that there's no guarantee that WebStorm, or any other IDE, will adopt the same syntax that JSDoc uses.)

**Comment by mzgol** [comment]
How about just:
```js
/** @param {iterable of <string>} */
```
Quite verbose, though. But resonates well with ES2015 `for-of` construct. Unfortunately, in JS the star (`*`) is used to denote generator functions but in jsDoc it has a different meaning.

I'm afraid that too magic a syntax might conflict with a future ECMAScript syntax.

**Comment by mzgol** [comment]
I reported a WebStorm issue: https://youtrack.jetbrains.com/issue/WEB-16905. Maybe they'll have more ideas.

**Comment by ariporad** [comment]
+1

I also understand the worry about ES7+

**Comment by hegemonic** [comment]
I'm inclined to agree with the WebStorm thread that `Iterable.<*>` is the right syntax for iterables. It looks like WebStorm has been updated to handle this case better, too.

Closing this issue.
