### ISSUE TITLE
Index page shows multiple headings as Index 

### ISSUE THREAD

**Issue by djonnala** [jsdoc3/jsdoc#1010]
Index page and other pages like modules show multiple headings in the html file. I am not able to figure out how to resolve this.

![untitled](https://cloud.githubusercontent.com/assets/12037869/7714887/84c139aa-fe37-11e4-9ce9-b28136ed1fd2.png)

**Comment by hegemonic** [comment]
It looks like you're using a third-party JSDoc template. Please file this bug against the third-party template.
