### ISSUE TITLE
Custom tag ignored on newDoclet event

### ISSUE THREAD

**Issue by atomicpages** [jsdoc3/jsdoc#1022]
There's a weird issue when I create a custom tag and then attempt to search for that _kind_ of tag on the [newDoclet event](http://usejsdoc.org/about-plugins.html#event-handlers). Rather than printing things out to the console like I expect the tag is simply ignored. I've reproduced this issue using node.js as well as the built-in Rhino interpreter.

The code to create a new tag:

	exports.defineTags = function(dictionary) {
		dictionary.defineTag('tab', {
		    mustHaveValue: true,
	    	canHaveName: true,
		    canHaveType: false,
		    onTagged: function(doclet, tag) {
	    	    doclet.kind = "tab";
	        	doclet.tab = tag.text; // name of the tab to create
	        	doclet.contexts = {};
	    	}
		});
	};

The code to handle the `newDoclet` event:

	exports.handlers = {
		newDoclet: function(e) {
			if(e.doclet && e.doclet.kind === "tab") console.log(e);
		}
	};

Nothing shows up in the output in the console like I'm expecting it to. Not sure if this is the expected behavior or not. I'm documenting my source file like this:

	_handleEvent: function(event) {

		/**
		 * Some description
		 * @tab Events
		 * @context Button Events
		 */
		switch(event.type) { ...

The weird thing is if I revise my documentation to be this:

	_handleEvent: function(event) {
		
		/**
		 * Some description
		 * @tab Events
		 * @context Button Events
		 * @event Button#onSelect
		 */
		switch(event.type) { ...

and the exporting of the handler to:

	exports.handlers = {
		newDoclet: function(e) {
			if(e.doclet && e.doclet.kind === "event") console.log(e);
		}
	};

I get output! Please help me understand why this happening and how I might be able to fix this.

**Comment by atomicpages** [comment]
Figured it out. I was just being a n00b.

**Comment by shahkeval88** [comment]
@atomicpages - could you tell me what mistake you did there? I am also facing such issue. Thanks in advance!
