### ISSUE TITLE
@memberof for shared class methods?

### ISSUE THREAD

**Issue by vitaly-t** [jsdoc3/jsdoc#1024]
Initially published [this question on StackOverflow](http://stackoverflow.com/questions/30793889/memberof-for-shared-class-methods), just didn't like the answer very much. Is there a better way?

In my library I am extending types `Database` and `Transaction` with the same method `query` defined in just one place.

If I try to use `@memberof Database` and `@memberof Transaction`, the latter overrides the former.

What is the correct way in `jsdoc` to indicate for a function that it represents a method in two different classes?

**Comment by hegemonic** [comment]
It sounds like the `query` method is a mixin, so I would document it that way:

```js
/**
 * @mixin
 */
var Query = {
    /**
     * Run a query.
     */
    query: function() {}
};

/**
 * @class
 * @mixes Query
 */
function Database() {}

/**
 * @class
 * @mixes Query
 */
function Transaction() {}
```

(In the future, please send questions to the [jsdoc-users mailing list](http://groups.google.com/group/jsdoc-users). The GitHub issue tracker is for bug reports and feature requests. Thanks!)

**Comment by vitaly-t** [comment]
@hegemonic any reference to the `@mixin` feature?

**Comment by hegemonic** [comment]
Both tags are documented on the [Use JSDoc](http://usejsdoc.org/) website:

http://usejsdoc.org/tags-mixes.html
http://usejsdoc.org/tags-mixin.html

**Comment by vitaly-t** [comment]
Such functions appear as list of mixes instead of list of methods. Anyone who reads documentation will be wondering what is a mix and how it is different from a method?

This seems like an awkward workaround. Why not just list such functions along with methods?

Perhaps a better question - why not just support a list of class names after `@memberof`?
