### ISSUE TITLE
ES6: "JSDoc does not currently handle ExportDeclaration nodes."

### ISSUE THREAD

**Issue by stefanwalther** [jsdoc3/jsdoc#1031]
I am getting the following error msg when using jsdoc on a very simple es6 file:

```
JSDoc does not currently handle ExportDeclaration nodes.
```

Any ideas? Tried it with several templates, always the same error.

**Comment by yaycmyk** [comment]
@stefanwalther Are you using the dev version in your project? `npm install git+https://github.com/jsdoc3/jsdoc.git` a lot of the ES6 stuff doesn't work with the current version in NPM.

**Comment by stefanwalther** [comment]
Ok, Thx, will try

**Comment by piotr-cz** [comment]
ES6 errors don't pop up anymore when installed from GIT

**Comment by hegemonic** [comment]
Yeah, this is definitely because you're not using the dev version of JSDoc. The current release (JSDoc 3.3.2) does not support ES 2015 code.
