### ISSUE TITLE
Question: Supported feature of documenting return objects?

### ISSUE THREAD

**Issue by eiriksm** [jsdoc3/jsdoc#1038]
Hey.

Sorry if this is stated somewhere, but I could not find it.

I wanted to document a return object, and started by stating, in a full sentence, what the object would consist of. Then I just tried to describe it as I describe nested object structures in a `@param`:

```js
/**
 * ...
 * @return {object} returnObj
 *   An object some prop and some other prop.
 * @return {string} returnObj.someProp
 *   Some prop.
 * @return {string} returnObj.otherProp
 *   Other prop.
 */
```

To my great joy, this generated the output expected and makes for a beautiful description of my return object. 

So, just to my question: Since I did not find anything in the docs about it: Is this a supported feature? Could I keep using it and depend on it being supported?

For the record, we are doing a complete jsdoc3 overhaul for Drupal (the cms) now, and we would love to be able to use this, if "officially" supported.

I'll probably submit a PR for the doc update for `@return` if you think this sounds like a good idea to do (and to avoid others confusion)

**Comment by hegemonic** [comment]
That's not exactly a supported feature--JSDoc doesn't have any notion of named return values, so it thinks you're documenting three separate return values and treats `returnObj`, etc., as part of the description. But I don't see any reason why this would work any worse in the future than it does now. If you're happy with the result, it's probably safe to keep doing this.

(In the future, please send questions to the [jsdoc-users mailing list](http://groups.google.com/group/jsdoc-users). The issue tracker is for bug reports and feature requests. Thanks!)

**Comment by morgs32** [comment]
@hegemonic can we count this a feature request
