### ISSUE TITLE
C++ Addons

### ISSUE THREAD

**Issue by Queuecumber** [jsdoc3/jsdoc#1041]
Quick question about C++ addons (sorry if this isn't the right place)

My project has a number of javascript files that I generate documentation for using jsdoc. I have recently added a set of C++ files encapsulated in an addon and I want to document them as well. Is there a procedure for integrating C++ documentation into jsdoc?

**Comment by tmcw** [comment]
The [documentation](https://github.com/documentationjs/documentation) project (an alternative JSDoc implementation) supports C++ addons by a special parsing mode: see [node-mapnik's documentation](http://mapnik.org/node-mapnik/documentation/) for an example.

**Comment by hegemonic** [comment]
JSDoc doesn't really support integrating docs for C++ or other languages. You might try the project that @tmcw mentioned and see if it meets your needs.
