### ISSUE TITLE
Document the inline object syntax for @returns

### ISSUE THREAD

**Issue by dandv** [jsdoc3/jsdoc#1045]
http://usejsdoc.org/tags-returns.html doesn't specify how returned objects with constant keys can be documented, and there has been [speculation about this on StackOverflow for 4+ years](http://stackoverflow.com/questions/6460604/how-to-describe-object-arguments-in-jsdoc).

@servoy [suggests](https://wiki.servoy.com/display/Serv7/Annotating+JavaScript+Using+JSDoc) this:

    @return {{x:Number, y:Number}}

WebStorm also uses that syntax.

Is this supported by JSDoc? Are there alternatives?

**Comment by hegemonic** [comment]
Yes, this is supported. The alternative is to create a [`@typedef`](http://usejsdoc.org/tags-typedef.html) and refer to the `@typedef` in the `@return` tag.

The documentation lives in a different repo--can you please [file this issue against the docs](https://github.com/jsdoc3/jsdoc3.github.com/issues)?

**Comment by dandv** [comment]
@hegemonic: sorry for filing this in the wrong repo. Now that GitHub supports moving issues, would it be best if someone with the appropriate access moved the issue to the https://github.com/jsdoc/jsdoc.github.io repo?
