### ISSUE TITLE
Is JSDoc case sensitive?

### ISSUE THREAD

**Issue by dandv** [jsdoc3/jsdoc#1046]
Maybe this is a silly question, but a search for "case sensitive" in the repo doesn't reveal anything as of now. [Same search on Google](https://www.google.com/search?q=case+insensitive+OR+insensitive+site:usejsdoc.org).

At http://usejsdoc.org/tags-type.html I see "number", "boolean", "string" and "Array".

At http://usejsdoc.org/tags-returns.html I see Titlecase: "Number", "Boolean", "Array".

**Comment by hegemonic** [comment]
JSDoc doesn't care. It's up to the user's preference. I tend to use lowercase for primitive types (and `function`, for some reason) and uppercase for `Array` and `Object`.

In the future, please send this sort of question to the [jsdoc-users mailing list](https://groups.google.com/forum/#!forum/jsdoc-users). Thanks!

**Comment by shanimal** [comment]
>  I tend to use lowercase for primitive types
> 
So does JSDocs...
https://jsdoc.app/tags-type.html

And **typeof** in javascript...
```
typeof true // "boolean"
typeof '' // "string"
typeof 4 // "number"
typeof undefined // "undefined"
typeof Symbol() // "symbol"
typeof function() {} // "function"
```
