### ISSUE TITLE
Feature Request: "@keywords"

### ISSUE THREAD

**Issue by reggi** [jsdoc3/jsdoc#1050]
I'm building a module and I need a way for the `@module` definition to harbor a list of keywords for the project. Is there an appropriate place for this? Or should I create a custom keyword `@keywords`?

**Comment by reggi** [comment]
I suppose I can check if the first declaration in the response has the property `order: 2`. Or invent a custom property entirely.

**Comment by hegemonic** [comment]
I'd suggest creating a [custom tag plugin](http://usejsdoc.org/about-plugins.html#tag-definitions) to define your own `@keywords` tag. This isn't something that I want to add to JSDoc proper.
