### ISSUE TITLE
Feature Request: "@package"

### ISSUE THREAD

**Issue by reggi** [jsdoc3/jsdoc#1051]
Support the object keyword `@package` within an `@module` definition. Allows you to set any of the `package.json` object properties.

[Here's an example](https://github.com/reggi/evalmd/blob/master/test-markdown.js#L14-L21):

```javascript
/**
 * :fishing_pole_and_fish: Evaluates javascript code blocks from markdown files.
 * @module evalmd
 * @package.keywords eval, evaulate, javascript, markdown, test
 * @package.preferGlobal
 * @package.scripts.test ./bin/test-markdown.js ./README.md
 * @package.bin.evalmd ./bin/test-markdown.js
 */
```

This is already implemented when generating a `package.json` using [`module-harvest`](https://github.com/reggi/module-harvest).

Note: `@package.name` would be the same as `@module`, of course `@module` would take priority.  The [proposal I put in  for `@keywords`](https://github.com/jsdoc3/jsdoc/issues/1050) could be implemented as `@package.keywords`.

**Comment by hegemonic** [comment]
Sorry, but we're already planning to add a `@package` keyword for a very different purpose (see #962), so I can't accommodate this feature request.
