### ISSUE TITLE
Disable detection of @module for CommonJs modules

### ISSUE THREAD

**Issue by daprahamian** [jsdoc3/jsdoc#1052]
As an example:

```js

/**
@class MyClass
*/
module.exports = function () {
  // Class implementation
};
```

It seems like jsdoc is creating both a class `MyClass`, as well as a module based on my filename. Can I disable the creation of the module?

**Comment by hegemonic** [comment]
For your example, JSDoc doesn't "create a module based on your filename." The generated docs show a class, and that's it.

Can you please provide a new example?

**Comment by hegemonic** [comment]
Closing due to lack of information.
