### ISSUE TITLE
Unable to generate instance methods in module

### ISSUE THREAD

**Issue by wooliet** [jsdoc3/jsdoc#1058]
I've been going through as much documentation and examples as I could find, but just can't seem to get this work as I would expect. 

I think it might be easier to show what I'm trying to accomplish rather than everything that hasn't worked.

**Code:**
```javascript
module.exports = function Ctor() {
    this.instanceMethod = function() {  }
};
```
**Desired Result:**
`instanceMethod` is documented as being an instance of `Ctor`, and _not_ as a static method.

_JSDoc 3.3.2_

**Comment by hegemonic** [comment]
I'm pretty sure this is what you want:

```js
/**
 * My module.
 * @module mymodule
 */

/**
 * @class
 */
module.exports = function Ctor() {
    /**
     * Instance method.
     */
    this.instanceMethod = function() {  };
};
```
