### ISSUE TITLE
Properly parse flow type annotations

### ISSUE THREAD

**Issue by mhagmajer** [jsdoc3/jsdoc#1060]
Code with [Flow](http://flowtype.org/) type annotations won't parse making it impossible to use JSDoc. Ideally JSDoc would also fallback to type annotations in code when generating documentation.

**Comment by jowcy** [comment]
If you use the jsdoc-babel plugin then you can use Flow annotations (jsdoc-babel will strip them).  

Install jsdoc-babel via npm and then modify your sdoc.conf.json file by adding:

"plugins": ["node_modules/jsdoc-babel"],
  "babel": {
    "extensions": ["js", "es6", "jsx", "jsdoc"],
    "optional" : ["flow"]
  }

**Comment by mhagmajer** [comment]
That worked, thanks @jowcy !

**Comment by montogeek** [comment]
@jowcy It does not work for me, I am still getting a SyntaxError: Unexpected token

**Comment by iandroutledge** [comment]
I came across this issue, so thanks for the comments. The `optional` property is Babel 5. I'm using Babel 6 so this didn't work for me, so I had to use the transform-flow-strip-types plugin for Babel. So my .jsdoc.json looks like the following, hopefully this might help someone else:

```
{
	"plugins": ["node_modules/jsdoc-babel"],
	"babel": {
		"extensions": ["js", "es6", "jsx"],
		"presets": ["es2015"],
		"plugins": "transform-flow-strip-types"
	}
}
```

**Comment by reyalpsirc** [comment]
If someone has problems generating the docs for a react-native project, this is the jsdoc.config.json that I was able to use (since the other options were generating an empty index page):

     {
        "plugins": [
          "node_modules/jsdoc-babel"
        ],
        "babel": {
          "babelrc": false,
          "presets": ["es2015", "react", "stage-0"]
        }
    }

**Comment by sobolevn** [comment]
Is there a way not to strip the types but to use them as a proper `@param` and `@return` types?

**Comment by napcoder** [comment]
@reyalpsirc thanks it worked for me on react-native
