### ISSUE TITLE
Support for Markdown Tables

### ISSUE THREAD

**Issue by pratyushtewari** [jsdoc3/jsdoc#1064]
Is there any plan to include the **[GFM Tables](https://help.github.com/articles/github-flavored-markdown/#tables)** in jsdoc3?

Would really appreciate it.
Thank you.

**Comment by hegemonic** [comment]
Our Markdown parser is [marked](https://github.com/chjj/marked), which supports GFM tables, so they should work in JSDoc. If you've [enabled the Markdown plugin](http://usejsdoc.org/plugins-markdown.html), and GFM tables aren't working, please let me know.

**Comment by pratyushtewari** [comment]
Hi Jeff,

I Have enabled the markdown plugin in the conf file.

Here is a the markdown

    * | name             | argument     | triggering UI event |
    * | :--------------- | :----------  | :------------------ |
    * | WIDGETSELECTED   | none         | onClick             |

and here is the output

<img width="848" alt="screen shot 2015-09-10 at 9 27 00 am" src="https://cloud.githubusercontent.com/assets/251768/9789451/4386796c-579e-11e5-9896-f5303442b02c.png">


I think there is a CSS issue. I dont see any borders/colors in the tables. Hope I am not making stupid typo errors in the markdown.

Please advice.
Thanks

**Comment by pratyushtewari** [comment]
I was inspecting the html and the parameter table has the same HTML structure but somehow the default CSS is working on that.

eg:
<img width="510" alt="screen shot 2015-09-10 at 2 07 36 pm" src="https://cloud.githubusercontent.com/assets/251768/9796697/80a58d16-57c5-11e5-9915-bcb6cf7a3fc5.png">

but the markdown table still is showing without any css.

eg:

<img width="848" alt="screen shot 2015-09-10 at 9 27 00 am" src="https://cloud.githubusercontent.com/assets/251768/9789451/4386796c-579e-11e5-9896-f5303442b02c.png">

**Comment by hegemonic** [comment]
Yep, looks like we need to fix this CSS issue in the template.

**Comment by hegemonic** [comment]
Fixed on master and releases/3.4. The fix will be included in JSDoc 3.4.1.
