### ISSUE TITLE
Does it matter if data types for @param are lowercase or start with an uppercase letter?

### ISSUE THREAD

**Issue by cr-nz** [jsdoc3/jsdoc#1066]
I think the current documentation is confusing. It should be crystal clear that for `@param {type} name` statements, the `type` should be written only one way e.g. with all lowercase letters. The only example I can find of a parameter being documented is here:

http://usejsdoc.org/about-block-inline-tags.html#examples

Which uses a lowercase `s` for `string`. It is not documented how the other types should be done. However I still think this is confusing as types in JavaScript are uppercase - at least wherever I've seen them defined e.g. 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures

    Boolean
    Null
    Undefined
    Number
    String
    Symbol
    Object

I would prefer that the correct way should be to document the types exactly as they are specified in the JavaScript language which is with a starting capital letter. For the documentation generator side it should probably just ignore the case and normalise it to the correct way. E.g. `string` or `String` is output as `String` in the documentation.

**Comment by hegemonic** [comment]
This was discussed in #1046, and there's a separate issue open to clarify this in the docs.

**Comment by shanimal** [comment]
I've always followed the lowercase primitives standard because of the JSDocs documentation.
https://jsdoc.app/tags-type.html

Also in the console...
```
typeof true // "boolean"
typeof '' // "string"
typeof 4 // "number"
typeof undefined // "undefined"
typeof Symbol() // "symbol"
```
