### ISSUE TITLE
[Howto] Create a changelog overview

### ISSUE THREAD

**Issue by BtM909** [jsdoc3/jsdoc#1067]
Sorry for this stupid question, but if I Google anything with @version or changelog I only get actual changelogs.

I am documenting my changes to versions like this
```
* @version 4.0.1 Initial release
* @version 4.0.2 Added custom Holidays and changed TIMEZONE to 'EDT'
```
This ensures that the latest line is included in the documentation.

Is there any way I can also have the entire changelog included in the generated JSDocs?

Thanks

**Comment by hegemonic** [comment]
You would need to customize the JSDoc template to gather up all the `@version` info and generate a changelog. This could take a lot of work.

If you have more questions about this, please ask for help on the [jsdoc-users mailing list](https://groups.google.com/forum/#!forum/jsdoc-users). Thanks!
