### ISSUE TITLE
npm 3 - Cannot find module '.../node_modules/ink-docstrap/template/publish'

### ISSUE THREAD

**Issue by destroyerofbuilds** [jsdoc3/jsdoc#1068]
I recently upgrade to npm 3 (Released today). npm 3 flattens the `node_modules/` directory.

The full error is:

```bash
Cannot find module 'node_modules/grunt-jsdoc/node_modules/ink-docstrap/template/publish'
```

The error includes a mention to `grunt-jsdoc`, but I don't believe the error resides there.

My project's `.jsdoc` file includes:

```json
        "path": "ink-docstrap",
```

The `grunt-jsdoc` package includes `ink-docstrap` as a `dependency`. My assumption is that `jsdoc` is looking for `ink-docstrap` in the `node_modules/` directory of it's parent, `grunt-jsdoc`. However the `ink-docstrap` directory is not there, because it has been moved further up in the directory structure by npm.

**Comment by destroyerofbuilds** [comment]
Closing. Issue was elsewhere in my `Gruntfile.js`.

**Comment by TulkasLaugh** [comment]
How did you fix it? I'm having the same issue on my gruntfile
