### ISSUE TITLE
Reusing @link

### ISSUE THREAD

**Issue by vitaly-t** [jsdoc3/jsdoc#1069]
Can't seem to find how to predefine and reuse links.

I am using MD notation everywhere, and have:
```javascript
  "plugins": [
    "plugins/markdown"
  ]
```

This doesn't seem to work for `@link` however. I can only find examples of the in-line use of URL-s. 

That's not really usable, because not only I reuse links in documentation a lot, but the number of links is such, if I start using in-line links everywhere, the code documentation will look unreadable in its raw text format, which is a big no-no. Plus, links become much harder to update.

Am I missing something or is this feature missing in the library? I would find the latter hard to believe, because it is the most essential piece of the MD syntax, to be able to predefine links and refer to them via `[link name]`.

**UPDATE**

Since I'm converting documentation into MD anyway, and ended up appending a file with links to the end of the output document. But if I were to use the HTML version of the output, that would be more awkward.

**Comment by hegemonic** [comment]
Sorry, but the inline `{@link}` tag doesn't provide a way to reuse links. I think it would be difficult to change this without breaking something.

For standard Markdown links, you should be able to use predefined links as long as you define the links in the same block of text where you use them (for example, in the description of a method). Your workaround might be more efficient for your purposes.
