### ISSUE TITLE
Output can be cut off in node 4

### ISSUE THREAD

**Issue by AgentME** [jsdoc3/jsdoc#1070]
Between node 0.12 and 4.0, writes to stdout are no longer synchronous, but it appears that jsdoc can call process.exit before writes are complete, so jsdoc's output can be cut off. See https://github.com/nodejs/node/issues/3033 and https://github.com/nodejs/node/issues/2972.

**Comment by tschaub** [comment]
I think the alternatives here are to have JSDoc *not* call `process.exit()` (on success), to have all templates return promises and use a version of JSDoc with the changes from #953, or to wait for a change in Node.

**Comment by hegemonic** [comment]
Fixed on master. Sorry for the long delay in getting this merged.
