### ISSUE TITLE
How to document spread operator

### ISSUE THREAD

**Issue by robcolburn** [jsdoc3/jsdoc#1074]
How do we document object spread operators in functions

``` js
/**
 * @param {object} cat - cute
 * @param {function} blender - pokey
 * @param {array} cubes - things to pass to blender
 * @return {string}
 *   result of blender
 */
const doThing = ( {cat, blender}, ...cubes ) => blender(cat, ...cubes)
```

**Comment by TimeForAChange** [comment]
+1

**Comment by thefabulousdev** [comment]
+1

**Comment by jtribble** [comment]
+1

**Comment by igor9silva** [comment]
+1

**Comment by brabeji** [comment]
Also please see #1163 , seems like code with spread operator can't be even parsed by jsdoc currently.

**Comment by ezzygemini** [comment]
+ 2

**Comment by igor9silva** [comment]
How is this solved nowadays?

**Comment by aliafshar** [comment]
`@param {...object} myParam`

works for me

**Comment by hegemonic** [comment]
See #987 and #1234 for examples of how to document this. I filed jsdoc3/jsdoc3.github.com#159 to add something about this to the docs.

**Comment by JanisE** [comment]
There is still no mention of the spread operator though, so I filed jsdoc3/jsdoc3.github.com#183 to add to the docs.

**Comment by axell-brendow** [comment]
I had a different need. I was doing my React component and I needed to document spread operator inside object destructuring. Seems that VSCode or JSDocs can not handle this properly.

I tried this way: (I've simplified)
`
/**
 * @typedef {{ value: number }} MyObj
 * @param {{ label?: string, rest: ...MyObj }} props
 */
const MyTextInput = ({ label, ...rest }) => {
`
But "rest" gets the weird type `{ rest: any, MyObj: any }`. Yes, rest is considered as an object that has a property "rest" and another property "MyObj".


I also tried this way:
`
/**
 * @typedef {{ value: number }} MyObj
 * @param {{ label?: string, ...rest: MyObj }} props
 */
const MyTextInput = ({ label, ...rest }) => {
`
But "rest" gets the weird type `{ rest: MyObj }`


So I found a solution that works for now:
`
/**
 * @typedef {{ value: number }} MyObj
 * @param {{ label?: string } & MyObj} props
 */
const MyTextInput = ({ label, ...rest }) => {
`

This time, "rest" type is correctly assigned to an object with the properties of MyObj.

**Comment by jimmywarting** [comment]
if i have something like this:
```js
/**
 * @param {function} successCallback
 * @param {function} errorCallback
 * @param {SessionRequest=} sessionRequest
 */
function requestSession (successCallback, errorCallback, sessionRequest) {
  api.requestSession(successCallback, errorCallback, sessionRequest)
}
```

and i would want to just write 
```js
function request (...args) {
  api.requestSession(...args)
}
```

What would be the best way to write my jsdoc?
I guess i could just write `const request = api.requestSession.bind(api)` but rather not

**Comment by raghav-misra** [comment]
> if i have something like this:
> 
> ```js
> /**
>  * @param {function} successCallback
>  * @param {function} errorCallback
>  * @param {SessionRequest=} sessionRequest
>  */
> function requestSession (successCallback, errorCallback, sessionRequest) {
>   api.requestSession(successCallback, errorCallback, sessionRequest)
> }
> ```
> 
> and i would want to just write
> 
> ```js
> function request (...args) {
>   api.requestSession(...args)
> }
> ```
> 
> What would be the best way to write my jsdoc?

Do correct me if I'm wrong but I think you could do:

```js
/**
 * @param {function} successCallback
 * @param {function} errorCallback
 * @param {SessionRequest} sessionRequest
 */
function requestSession (...args) {
  api.requestSession(...args)
}
```

**Comment by tylim88** [comment]
/**
```
 * @param {...number} args - array of number arguments
 */
export const a = (...args: number[]) => {
	return args
}

```

![image](https://user-images.githubusercontent.com/5227509/152971856-1aad7c7e-88b7-4618-860c-888b3f6319b5.png)

this will works, but the parameter name is fixed to `args`

indirect source: https://jsdoc.app/tags-type.html
![image](https://user-images.githubusercontent.com/5227509/152972190-e6e53c13-3bef-4026-ac6d-4e4289e52d92.png)

**Comment by BarbWire-1** [comment]
I'm writing a little lib to dynamically extend classes with mixins. In general the intellisense support is working. Now I use to add multiple mixins to one extending class. It works with:
```js
const AdvancedCalculator = extendWithFlexi('AdvancedCalculator', Calculator, Object.assign({}, MathOperations, FormatNumbers));
```
I now tried a functions like
```js
function mergedPlugins(...mixins) {
	return Object.assign({}, ...mixins);
}
```
but I cannot mage it to return an Object.
Only way to use the so merged Object is to do
```js
// Explicitly declare the type when assigning
/** @type {typeof MathOperations & typeof FormatNumbers} */
const mix = mergedPlugins(MathOperations, FormatNumbers)
```
I tried to generalize that on an abstract level for the functions return but failed.
