### ISSUE TITLE
How to document members of module.exports 

### ISSUE THREAD

**Issue by thetutlage** [jsdoc3/jsdoc#1080]
How to document something like this ? it will be preferred to have same coding style as i am aware i can put my properties under `{}`.

```javascript
/**
 * @module GreetHelpers
 */
let helpers = exports = module.exports = {}

/**
 * bar value by default
 * @memberof GreetHelpers
 * @type {String}
 */
helpers.bar = 'wow'
```

**Comment by hegemonic** [comment]
You can use the `@exports` tag to help you here, very similar to [an example from the docs](http://usejsdoc.org/howto-commonjs-modules.html#values-assigned-to-module-exports-and-local-variables):

```js
/**
 * @exports GreetHelpers
 */
let helpers = exports = module.exports = {}

/**
 * bar value by default
 * @type {String}
 */
helpers.bar = 'wow'
```

If you have other questions, please send them to the [jsdoc-users mailing list](http://groups.google.com/group/jsdoc-users). Thanks!

**Comment by Droogans** [comment]
@hegemonic I'm attempting to separate out my `@exports` into something that looks nice when I compile my documentation using the `"useLongNameInNav"` option set to `true`.

https://github.com/rackerlabs/encore-ui/pull/1481#discussion-diff-50430433

I went to change [this line](https://github.com/Droogans/encore-ui/blob/98df686c397eb070190921d43dce84f88240b538/src/atoms/rxCheckbox/scripts/rxCheckbox.exercise.js#L7) from this:

```js
/**
 * @function
 * @description rxCheckbox exercises
 * @exports rxCheckbox
 * ...
 * /
```

To this:

```js
/**
 * @function
 * @description rxCheckbox exercises
 * @exports exercise.rxCheckbox
 * ...
 */
```

In the process, my generated documentation went from looking like this:

<img width="941" alt="screen shot 2016-01-21 at 12 01 26" src="https://cloud.githubusercontent.com/assets/1214609/12489604/bd786f04-c036-11e5-9eb7-a31d1b36d7c9.png">


To this:

<img width="528" alt="screen shot 2016-01-21 at 12 02 15" src="https://cloud.githubusercontent.com/assets/1214609/12489630/dd39ce28-c036-11e5-8641-e32c23c67ad9.png">

It appears as though I've lost my `@param` definitions.

I've worked around this by using `@exports exercise-rxCheckbox`, or something using a "safe" character, such as an underscore, or a forward slash.
