### ISSUE TITLE
Custom Module Headings

### ISSUE THREAD

**Issue by jonathanamartin** [jsdoc3/jsdoc#1087]
We'd like to organize the modules on the index page into custom sub-headings similar to the Alfresco JS Docs here:

http://dev.alfresco.com/resource/docs/aikau-jsdoc/index.html

What would be the best way to implement something like this.  Custom templates, custom tag, etc.?  I'm sure it's something simple, we just haven't been able to figure it out.

Any help would be greatly appreciated.

Thanks,
Jonathan

**Comment by hegemonic** [comment]
Yes, you'll need to create a custom template. If you're using the default template, you'll probably want to start with the [code that generates the TOC](/jsdoc3/jsdoc/blob/2e04416a9a650515f924815432bfa9291aaa4419/templates/default/publish.js#L331-L379).

If you have other questions, please send them to the [jsdoc-users mailing list](http://groups.google.com/group/jsdoc-users). Thanks!
