### ISSUE TITLE
How to line wrap a long @see link without a space in the URL?

### ISSUE THREAD

**Issue by Xotic750** [jsdoc3/jsdoc#1089]
If code style requires, for example, that line length is limited to 80 characters then how do you line wrap a long URL without it inserting whitespace where it breaks?

```
   * @see https://github.com/Komodo/KomodoEdit/blob/master/src/chrome/komodo/
   * content/sdk/logging.js
```

Gives

https://github.com/Komodo/KomodoEdit/blob/master/src/chrome/komodo/%0Acontent/sdk/logging.js

I tried several other ways than the example given but all gave me the same result.

**Comment by hegemonic** [comment]
Good point. It seems reasonable to strip line breaks from the text of `@see` tags so you can break them across lines.

**Comment by mezpahlan** [comment]
Would it also be reasonable to strip breaks wherever a `*` **is not** followed by a ` @`?

For example:

````
* @param {array} array - The array [reduce]{@link https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce}
*     was called upon.
````

Outputs this for me (3.4.0):

````html
<td class="description last"><p>The array <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce">reduce</a><br>    was called upon.</p></td>
````
Whereas I would prefer it without the `<br>`.

**Comment by hegemonic** [comment]
On second thought, I'd prefer not to strip line breaks from `@see` tags. I think it could be confusing for JSDoc to strip line breaks from some tags but not others. Also, every linter that I'm aware of allows you to disable specific rules within a small region of code, which makes it possible to deal with exactly this sort of problem.

For those reasons, I'm closing this issue.
