### ISSUE TITLE
Error parsing arrow function

### ISSUE THREAD

**Issue by mturnwall** [jsdoc3/jsdoc#1100]
I have a javascript file that starts with an arrow function.

```js
(($, global) => {
// code
})(jQuery, typeof window === 'undefined' ? this : window);
```

When I run jsdoc 3.3.3 I get this error `ERROR: Unable to parse scripts/check_compat.js: Line 7: Unexpected token =>`

How can I get jsdoc to parse my ES6 files correctly? I did a search and it looks like it's supposed to be supported.

**Comment by hegemonic** [comment]
JSDoc 3.3.x does not support ES2015 code, including arrow functions. JSDoc 3.4.0 (not yet released) will include full support for ES2015. For now, you can use the version of JSDoc on GitHub master, which includes full ES2015 support.
