### ISSUE TITLE
Node only version

### ISSUE THREAD

**Issue by tschaub** [jsdoc3/jsdoc#1102]
@hegemonic what do you think about releasing a new major version that drops Rhino support?

If there are people using JSDoc with Rhino, they can continue to use JSDoc @ 3.x.

I'd be happy to help get a JSDoc 4.0 release together that dropped Rhino support.

**Comment by tschaub** [comment]
Here's a branch that removes Rhino support: https://github.com/jsdoc3/jsdoc/compare/master...tschaub:four

**Comment by hegemonic** [comment]
Thanks for putting this together, @tschaub! I'm going to drop Rhino support from JSDoc 3.4.0, since JSDoc doesn't really follow semver.
