### ISSUE TITLE
Inconsistent documentation regarding multiple types

### ISSUE THREAD

**Issue by cr-nz** [jsdoc3/jsdoc#1104]
[This page](http://usejsdoc.org/tags-returns.html) details usage for multiple return types as:

```
* @returns {Number|Array} Sum of a and b or an array that contains a, b and the sum of a and b.
```

While [this page](http://usejsdoc.org/tags-param.html) and [this page](http://usejsdoc.org/tags-type.html) details a different format:

```
* @param {(string|string[])} [somebody=John Doe] - Somebody's name, or an array of names.
```

It would be great if the documentation for this was consistent across the whole site. Personally I think the parentheses `( )` are superfluous. The {Number|Array} format for documenting multiple types is faster to write and cleaner to read in the code.

**Comment by pohutukawa** [comment]
Yes, agreed. Even if both work, there should be a canonical recommended style IMO.

**Comment by tschaub** [comment]
I think you'll find the most consistent documentation of JSDoc type annotations here: https://developers.google.com/closure/compiler/docs/js-for-compiler?hl=en#types

One option would be to make the `http://usejsdoc.org/` docs consistent with that.  So your second example above would become `@param {(string|Array.<string>)} ...`.

You may consider the parenthesis a matter of personal taste, and JSDoc may tolerate many different flavors of annotation.  But I think there is good justification in documenting the formal syntax and then tolerating typos.

**Comment by hegemonic** [comment]
JSDoc intentionally allows multiple styles of type expressions. You're not restricted to the Closure Compiler syntax.

That said, if I were to recommend a canonical style, it would include the parentheses. Sorry about that.

I'm rolling this issue into jsdoc3/jsdoc3.github.com#21, which covers better docs for type expressions.
