### ISSUE TITLE
use of @class and @constructs leads to duplicated output of the class  

### ISSUE THREAD

**Issue by TitanNano** [jsdoc3/jsdoc#1105]
Hello,
I'm working with the latest master and as soon as I use @class and @constructs, my generated documentation will contain the entire class twice. Once with a constructor without any arguments and once with the right constructor.

```JavaScript
/**
 * @class 
 * @implements {Test}
 */
var Message = {

  /**
   * @constructs
   * @param {Account} account
   * @param {ChatCore} core
   * @param {object} options
   */
  _make : function (account, core, options) {
    options = options || {};

    this.account = account;
    this.core = core;
    this.options = Make(options, MessageOptions)();
  },

  /**
   * @param {string} name
   * @private
   */
  _formatName : function (name) {
```

If I just use `@lends Class.prototype` everything works correctly, but my @extends, @implements etc. definitions are ignored. 
Can you fix this so we get a correct output?

**Comment by hegemonic** [comment]
I think you want to do something like this:

```js
var Message = /** @lends Message# */{

  /**
   * @constructs Message
   * @implements {Test}
   * @param {Account} account
   * @param {ChatCore} core
   * @param {object} options
   */
  _make : function (account, core, options) {
    options = options || {};

    this.account = account;
    this.core = core;
    this.options = Make(options, MessageOptions)();
  },

  /**
   * @param {string} name
   * @private
   */
  _formatName : function (name) {}
};
```

**Comment by TitanNano** [comment]
but this doesn't solve my problem. I can't add any tags to @lends, but if I use @class and @lends the class will apear twice...

**Comment by Pitcher4u2Catch** [comment]
Check your settings in that section and make sure you don't have some thing
clicked twice. Then check all other settings to make sure you have then
checked to function
