### ISSUE TITLE
Styles for markdown ## and ### have identical CSS settings so they can't be visually distinguished

### ISSUE THREAD

**Issue by yaronyg** [jsdoc3/jsdoc#1108]
When using markdown to specify a ## and a ### header the outputted HTML properly distinguishes these as h2 and h3. But unfortunately the way the style sheets are set up when displayed on screen both h2 and h3 elements have the identical CSS settings so they are visually indistinguishable.

**Comment by hegemonic** [comment]
Fixed on master and releases/3.4. The fix will be included in JSDoc 3.4.1.

**Comment by yaronyg** [comment]
Thank you!
