### ISSUE TITLE
Documenting Promises

### ISSUE THREAD

**Issue by dcollinsf5** [jsdoc3/jsdoc#1110]
Hello there,
I'm working on a codebase that uses Promises throughout, and have been wrestling with the right way to JSDoc promise returning functions.  I noticed that there was an issue specifically centered around this problem, but that discussion was locked a year ago and the milestone it was targetted for has come and gone.  Given how popular Promises are in the JS world today, could the issue please be re-opened?   I'd like to give my input on the discussion but it has since been locked; I think it is past time to figure out how JSDoc is going to handle asynchronously returning functions.

https://github.com/jsdoc3/jsdoc/issues/509

**Comment by hegemonic** [comment]
Sorry, but the decision has been made. See [the second example in this comment](https://github.com/jsdoc3/jsdoc/issues/509#issuecomment-45441171) and [this comment](https://github.com/jsdoc3/jsdoc/issues/509#issuecomment-63498330) for the details. I just need to implement the new tags.

**Comment by slkennedy** [comment]
Hey @hegemonic any idea when we can expect the new tags to be released?
