### ISSUE TITLE
Error with Spread Operator and Fat Arrow Functions

### ISSUE THREAD

**Issue by posgarou** [jsdoc3/jsdoc#1117]
I am currently running the tip of master.

The following code parses in Babel (and is a [pretty common idiom in React](https://github.com/facebook/fixed-data-table/blob/master/examples/ObjectDataExample.js#L22-L26)).

```
const MyFunction = ({ prop1, prop2, prop3, ...remaining }) => {
};
```

Without the spread operator, everything works fine.  But with the spread operator, JSDoc gives the following error:

```
ERROR: Unable to parse...: Line x: Invalid left-hand side in formals list
```

**Comment by yaycmyk** [comment]
Might be an issue in Espree. I see that capability was made a Stage 2 proposal about 3 months ago: https://github.com/sebmarkbage/ecmascript-rest-spread

**Comment by hegemonic** [comment]
Sorry, but Espree, the parser we use, doesn't support features that haven't made it into the spec. We can't support this until Espree does.
