### ISSUE TITLE
Tilde character prepended to symbol names when `@lends <global>` used

### ISSUE THREAD

**Issue by miguel-guedes** [jsdoc3/jsdoc#1123]
I'm attempting to document a number of classes that are mostly declared inside closures.  To avoid having to explicitly name the class using `@name` (or `@class <name>`) and include a `@memberof` annotation in every class member, I opted instead to use `@lends <global>`.  However this has the strange side-effect of producing symbol names with a prepended tilde character [1].

Sample code:

```javascript
(/** @lends <global> */ function(window, undefined) {
    /**
     * @class
     */
    var Foo = function(elevated) {};


    /**
     * @abstract
     */
    Foo.prototype.show = function() {};
});
```

Produces:

```
Class: ~Foo

~Foo
new ~Foo()
Source: test.js, line 5

Methods
(abstract) show()
Source: test.js, line 10
```

How can I get rid of the annoying tilde character without having to resort to explicitly naming classes with `@class` and using the `@memberof` tag on members?

[1] when jsdoc v3.4.0 is invoked with the form: `jsdoc <filename.js>`

**Comment by hegemonic** [comment]
That's not how the `@lends` tag is meant to be used. It can only be applied to an object literal, as shown in [the docs](http://usejsdoc.org/tags-lends.html).

You'll get better results by using an `@alias` tag to help JSDoc understand that `Foo` is just called `Foo` and is not an inner member of an anonymous function:

```js
(function(window, undefined) {
    /**
     * @class
     * @alias Foo
     */
    var Foo = function(elevated) {};


    /**
     * @abstract
     */
    Foo.prototype.show = function() {};
});
```
