### ISSUE TITLE
Semantic Versioning query.. 

### ISSUE THREAD

**Issue by 75lb** [jsdoc3/jsdoc#1124]
Hi! Do you consider the data structure exposed by `jsdoc -X` part of the public API? If so, shouldn't you bump the jsdoc major version number when the data structure changes? 

Breaking changes to the `-X` data structure (data content and structure differs if a ES5 class is rewritten in ES 2015) broke jsdoc2md and i had no idea until the reports started coming in.. jsdoc2md consumes the `-X` output..

**Comment by hegemonic** [comment]
JSDoc doesn't currently follow semantic versioning. I expect we'll switch to semantic versioning once there is a better-supported way to use JSDoc as a library.

That said, I'm not aware of any breaking changes to the `-X` data structure for ES2015 classes. (If there were breaking changes, they should have broken the default template as well.) What exactly is the change that caused problems for you?

**Comment by 75lb** [comment]
hi! Ok, fair enough if it doesn't follow SemVer.. closing.. 

Regarding the breaking change, i suppose it boils down to what is perceived as "breaking". The change causing problems for me is the difference in JSON data structure between ES5 and ES6 classes. 

My users complain "class docs are broken", but i discovered it only affects ES6 class docs. I can't advise them to "rewrite your class in ES5". The ES6 `class` statement is purely sugar, i didn't expect the underlying class representation to change. This assumption in mind, the alteration of data structure for ES6 felt like a "breaking" change. 

Anyway, I have fixed the issue my side. It's hacky (inspecting a `kind: "class"` record for tell-tale signs it might be ES6) but will do for now.
