### ISSUE TITLE
@event with multiple function arguments

### ISSUE THREAD

**Issue by yagop** [jsdoc3/jsdoc#1126]
I've read the [documentation](http://usejsdoc.org/tags-event.html) about `@event` and it seems its only for one argument callback. What if I've something like:

```js
this.emit('eventName', 'foo', {});
```

**Comment by hegemonic** [comment]
If you don't want to document this as an event named `foo`, one other option is to use the [`@callback` tag](http://usejsdoc.org/tags-callback.html), which allows you to document an arbitrary number of parameters.

**Comment by jvivs** [comment]
I'll leave a +1 for actually supporting this syntax. Data emitted by events are not limited to one parameter.

**Comment by yagop** [comment]
Sorry for the misunderstand, what I want to document is **an event**, not a callback parameter of a function.

Please reconsider reopening the issue.

**Comment by piranna** [comment]
Single data events are ok for W3C APIs (like browsers), but on Node.js or jQuery styles is acceptable to emit several arguments, +1 to support this syntax.

**Comment by pabigot** [comment]
+1 from me too.

**Comment by pabigot** [comment]
Actually, now that I've figured out how to spell `module:MyModule~MyClass#event:myevent` (!) providing multiple `@param` tags within an `@event` documentation comment appears to work fine.  Well done, whoever did this.

**Comment by piranna** [comment]
Could you be able to provide us an example how did you do it?

**Comment by pabigot** [comment]
Put the following into a file`ev.js` and run `jsdoc ev.js`:

    /**
     * @file A file
     *
     * @module ArmActions
     */
    
    /**
     * A thrower.
     *
     * Related event is {@link module:ArmActions~Hurl#event:snowball}.
     *
     * @constructor
     */
    function Hurl () { }
    
    /**
     * Throw a snowball.
     *
     * @fires Hurl#snowball
     */
    Hurl.prototype.snowball = function() {
        // ...
    };
    
    /**
     * Snowball event.
     *
     * @event module:ArmActions~Hurl#snowball
     * @param {boolean} isPacked - Indicates whether the snowball is tightly packed.
     * @param {boolean} [hasRock] - Indicates the thrower is malicious.
     */

**Comment by piranna** [comment]
Maybe I'm wrong, but seems to me this define an event object, not a Node.js-like event with several parameters...

**Comment by pabigot** [comment]
Then perhaps I'm mis-using the tag; what I'm intending to do is document that a subclass of [EventEmitter](https://nodejs.org/dist/latest-v4.x/docs/api/events.html#events_class_eventemitter) emits an event named `snowball` which should be received like this:

    hurler.on('snowball', function(isPacked, hasRock) {
      // ...
    })

Excepting that the default jsdoc template lists these under an Events block just like Modules and Classes, which seems weird, it does what I want.  I'm only using JavaScript under Node.js so if this is supposed to be used for browser events which are something different then perhaps it would help to give an example of the use you want supported.

**Comment by chjj** [comment]
Is this still not possible? This is a very essential feature. I can't think of one event-driven module I've written that I could document properly without this. Is jsdoc even meant to be used with node.js?

**Comment by Tyratox** [comment]
Any updates on this?

**Comment by jcbrand** [comment]
Using multiple `@param` directives works fine.
