### ISSUE TITLE
Is there a standard way to specify an iterable function parameter?

### ISSUE THREAD

**Issue by kruncher** [jsdoc3/jsdoc#1128]
In the past I have defined function parameters like this:
```javascript
/**
 * Foo...
 * @param {array.<number>} numbers
 */
function foo(numbers) { ... }
```

But what is the proper syntax for something that implements the iterable protocol?

This?
```javascript
/**
 * Foo...
 * @param {iterable.<number>} numbers
 */
function foo(numbers) { ... }
```

Many thanks

**Comment by chpio** [comment]
in ESDoc it's `@param {Generator<number>} numbers my numbers` dunno about jsdocs

**Comment by hegemonic** [comment]
`iterable.<number>` is a totally appropriate way to document this.

**Comment by kruncher** [comment]
Thank you for the quick response :)

**Comment by julmot** [comment]
Is this the same for generator functions?
```javascript
/**
 * Example generator function
 * @return {Generator<number>}
 */ 
function *test(example){
}
```
