### ISSUE TITLE
Invalid type expression for shorthand array [] of object declared with Closure Compiler's syntax

### ISSUE THREAD

**Issue by micaste** [jsdoc3/jsdoc#1133]
I found out that the JSDoc type ```{{attr1: String, attr2: Number}[]}``` is not supported and throws the error : ```Invalid type expression "{attr1: String, attr2: Number}[]": Expected "!", "=", "?", "|" or end of input but "[" found.```
But the following expression is supported : ```{Array.<{attr1: String, attr2: Number}>}```.

Is that expected ? Is the shorthand [] only made to be used with primitive types or already defined typedefs ?

**Comment by hegemonic** [comment]
The `[]` shorthand dates back to before [Closure Compiler type expressions](https://developers.google.com/closure/compiler/docs/js-for-compiler?hl=en#types). As you discovered, it's not really meant to be mixed with Closure Compiler's more complex syntax. In this case, `{Array.<{attr1: String, attr2: Number}>}` is the right choice.
