### ISSUE TITLE
Linking to type definitions using @link

### ISSUE THREAD

**Issue by adrian-moisa** [jsdoc3/jsdoc#1143]
It seems that currently it is not possible to link to a specific type definition from a module. Are there any plans on implementing this?

**Comment by hegemonic** [comment]
Sorry for the lengthy delay in reviewing this.

I may be misunderstanding your request, but I think this is possible today. For example:

```js
/** @module foo */

/**
 * Type definition.
 *
 * @typedef {Object} myTypedef
 */

/** Function that links to {@link module:foo~myTypedef}. */
module.exports = function() {};
```
