### ISSUE TITLE
Cross referencing parameters in the same a function description

### ISSUE THREAD

**Issue by felixhayashi** [jsdoc3/jsdoc#1145]
Hi,

I need to document that a parameter depends on another one for the same function description.

```javascript
/**
 * Foo bar blub
 * 
 * @param {int} level - If {@param text} is also provided, the level will
 *     be increased automatically by one.
 * @param {string} text - A text which makes sense. Everything else is rejected.
 * @param{delay} delay - Delays the operation if {@param level} is also provided
 */
Foo.prototype.bar = function(level, text, delay) { …
```

Is this somehow possible? Thanks

-Felix

**Comment by hegemonic** [comment]
There's no tag that allows you to cross-reference other parameters. I think you can just do it with English, more or less as you have, and make it clear what's going on.

**Comment by felixhayashi** [comment]
Ah ok, thanks for your answer, I thought I was missing something.

Then I guess I have to fallback to plain english. Still I think it makes sense to add a "marker" here to make it clear that one is talking about a parameter of the same function one is describing so the source code description is unambigous and not too verbose.

**Comment by ericauv** [comment]
I would also like this functionality

**Comment by Sajjon** [comment]
We need this yesterday :D

**Comment by tcd** [comment]
So we can't have [this](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags#paramref)?

**Comment by ivanakcheurov** [comment]
April 2023, VSCode v1.73.1
`{@link paramname}` will be shown as a link in VSCode's annotation popup, upon clicking leads to the referenced parameter.

Example where `@returns` tag contains `@link` parameter references:
```ts
/**
 * Returns the original collection or filters it before returning
 * @param collection the collection to filter
 * @param filter if `false`, don't filter; otherwise the passed value is a predicate function and will be used for filtering
 * @returns the original {@link collection} with some or all of the original items depending on passed {@link filter}
 */
export function optionalFilter<T>(collection: T[], filter: ((value: T, index?: number, array?: T[]) => boolean) | false) {
    if (filter === false) {
        return collection;
    }
    return collection.filter(filter);
}
```
The VSCode documentation popup looks like this:
![image](https://user-images.githubusercontent.com/5347026/231126472-9fea09fe-54a7-4ae2-a875-22098a4b7075.png)
