### ISSUE TITLE
Code blocks do not work within @summary

### ISSUE THREAD

**Issue by vitaly-t** [jsdoc3/jsdoc#1149]
Code section `some code` doesn't work within @summary, comes up as text - `some text` instead of `some text`.

This works within @description however.

I tried with and without `"plugins/markdown"` - the same, doesn't work in @summary.

**Comment by hegemonic** [comment]
Fixed on master and releases/3.5. When the Markdown plugin is enabled, it now processes the text of the `@summary` tag. The fix will be included in JSDoc 3.5.2.
