### ISSUE TITLE
Question: Is there something similar to eslint plugin?

### ISSUE THREAD

**Issue by AdrieanKhisbe** [jsdoc3/jsdoc#1151]
Thinking about seting up in a set of repository (#microservicesOblige),
was wondering if it was possible to keep configuration DRY, 
with a master config that is refered by disciples config in each repo.

Something similar to eslint plugins:
http://eslint.org/docs/developer-guide/working-with-plugins.html

**Comment by hegemonic** [comment]
Sorry, I don't think there's anything quite like what you're requesting. We support a [JSON config file](http://usejsdoc.org/about-configuring-jsdoc.html), but you'd need to build your own logic to extend one JSON config file with another. (We also have [plugins](http://usejsdoc.org/about-plugins.html), but those have nothing to do with configuration.)
