### ISSUE TITLE
How to distinguish between static and instance methods of same name?

### ISSUE THREAD

**Issue by bojand** [jsdoc3/jsdoc#1152]
for example:

```
module.exports = Request;

/**
 * Simple request class
 * @param {Object} options - request options
 * @param {String} options.url - url string
 * ...
 * @constructor
 */
function Request(options) {
  ...
}

/**
 * Perform the request after creating a new object with options.
 * @param {Function} fn - callback
 */
Request.prototype.request = function (fn) {
  ...
}

/**
 * Create and perform a request.
 * @param {Object} options - request options
 * ...
 * @param {Function} fn - callback
*/
Request.request = function request(options, fn) {
  var req = new Request(options);
  return req.request(fn);
};
```

This seem to result in HTML anchors for with same name for both the static and instance version of `request` functions. So you only end up going to 1 of the documentation bodies. Is there a way to force a different anchor definition. I have tried `@variation` attribute but it didn't seem to work. `@alias` works but it's kind of an ugly solution.

Thanks,

**Comment by ponury-kostek** [comment]
Use `@static` for your static method

**Comment by hegemonic** [comment]
@ponury-kostek is correct. In the current version of JSDoc, this will give you a different HTML anchor for the static method.
