### ISSUE TITLE
@type Map and Set?

### ISSUE THREAD

**Issue by julmot** [jsdoc3/jsdoc#1174]
Example:

```javascript
/**
 * Description
 * @type {???}
 */
this.xyz = new Set([
    "test",
    "123"
]);
```

or

```javascript
/**
 * Description
 * @type {???}
 */
this.xyz = new Map([
    [1, "xyz"],
    [2, 123]
]);

// or:

/**
 * Description
 * @type {???}
 */
this.xyz = new Map([
    [1, "xyz"],
    ["string", 123]
]);
```

**Comment by julmot** [comment]
CC @micmath @tschaub @jannon @hegemonic

**Comment by hegemonic** [comment]
I don't understand your question. Yes, you can use `@type {Map}` or `@type {Set}`. What else do you want to know?

**Comment by julmot** [comment]
That was exactly my question. There seems to be no documentation about new ES6 things (e.g. set, map, generators), so I wanted to make sure using the right syntax.

**Comment by AMorgaut** [comment]
I'm currently having an issue on raw JS map object documentation: #1271 

As my mentioned use case show it, I think saying `Map` or `Set` objects are Map or Set instances will often be not enough.

How can I say that my property is a Map or a Set of Movies, or string, or another type?

If we would like

- to get the right auto-completion when I receive such Set or Map object and use their `get()` method,
- or idem when I iterate over them (with `for ... of`)
- or to be alerted when sending a bad value type to their `add(value)` / `has(value)` / `delete(value)` /  `set(key, value)` method

Could we write something like this ?
```js
/**
 * Description
 * @type {Set<string>}
 */
this.xyz = new Set([
    "test",
    "123"
]);

/**
 * Description
 * @type {Map<string>}
 */
this.xyz = new Map([
    [1, "xyz"],
    [2, 123]
]);
```
And knowing that Map keys can be of any type (symbol, string, number, object, function, ..) could we then also define the type of its key?
```js
/**
 * Description
 * @type {Map<number:string>}
 */
this.xyz = new Map([
    [1, "xyz"],
    [2, 123]
]);
```
It can be very useful so an IDE could say that you provide a wrong parameter type to the Map `get(key)` and `set(key, value)` methods. So would it when iterating of the `map.keys()` values.

**Comment by AMorgaut** [comment]
The google styleguide looks to push something similar but using a comma instead of a semicolon to seperate the key and the value types: https://google.github.io/styleguide/javascriptguide.xml#JsTypes

This could give something like:
```js
/**
 * Description
 * @type {Map<number,string>}
 */
this.xyz = new Map([
    [1, "xyz"],
    [2, "123"]
]);
```
