### ISSUE TITLE
Group Classes?

### ISSUE THREAD

**Issue by kmgilbert100** [jsdoc3/jsdoc#1180]
Is it possible do something like

- Group 1
----- SomeClass
- Group 2
----- SomeClass

```
@group Group1
@namespace SomeClass
```

```
@group Group2
@namespace SomeClass
```

**Comment by dh--** [comment]
This looks like it might be a duplicate of issue #1136

**Comment by kmgilbert100** [comment]
@dh--  Agreed.

**Comment by Syler921** [comment]
#1496
