### ISSUE TITLE
Docs not generated for @enum

### ISSUE THREAD

**Issue by AlexTalis** [jsdoc3/jsdoc#1184]
When I run jsdoc 3.4 or even latest dev version on JS file below, jsdoc does not generate documentation for the enum.

```
(function () {
    window.ns = {};

    /**
     * @enum {string}
     */
    ns.MyStrings = {
        VAL1: "a",
        VAL2: "bcd"
    };

    /**
     * @constructor
     */
    ns.MyClass = function () {
        /**
         * @type {ns.MyStrings}
         */
        this.myProp = ns.MyStrings.VAL1;
    };
})();
```

It generates links to enum documentation, but they don't work. For example, it generates the following details for ns.MyClass#myProp:

> myProp :ns.MyStrings

"ns.MyStrings" above is a link, but the target page does not exist.

I am using plain, clean jsdoc without any customizations.

**Comment by AlexTalis** [comment]
Declaring the namespace for JSDoc fixes the problem. When namespace is declared, jsdoc generates a namespace link and enums are shown there as members of the namespace.
```
/**
  * @namespace ns
  */
```

**Comment by buenjybar** [comment]
did you try something like this ?

```
   /**
     * My String
     * @enum
     */
    ns.MyStrings = {
       /** 
        * VAL1 
        * @type{string} 
        */
        VAL1: "a",
       /** 
        * VAL2 
        * @type{string} 
        */
        VAL2: "bcd"
    };
```
