### ISSUE TITLE
Feature request - Annotation option

### ISSUE THREAD

**Issue by ORESoftware** [jsdoc3/jsdoc#1190]
JSDoc seems to have two primary options:  Api docs and tutorials

Why not add a third - annotations

Annotations in code are normally accomplished by standard codings comments

However, there are examples of cleaner annotations that are separate from the code, for example Docco which powers Underscore/Backbone docs.

Right now I want to annotate some code, but I am finding it hard to do with JSDoc

**Comment by hegemonic** [comment]
This is pretty far outside of the scope of JSDoc, which is designed to support Javadoc-style API documentation, not literate programming-style annotations like Docco. If you want something like Docco, I recommend using a different tool than JSDoc.
