### ISSUE TITLE
How to add a method summary to a class documentation / to the template?

### ISSUE THREAD

**Issue by SunboX** [jsdoc3/jsdoc#1191]
Hi,

how can I add a method summary / table of contents to the documentation of a class?

It's no problem for me to modify the standard template for that. But how can I achive this?
Is there some documentation somewhere, or a sample that shows how to do this?

**Comment by buenjybar** [comment]
Hi @SunboX ,

if you would like to display a simple summary of your class details you should only modify the template.
but if you need to add any extra information from your documentation class, you might need to write down a small plugin.

in your template folder go edit the file **container.tmpl** starting at _<div class="container-overview"> ... _

**Comment by hegemonic** [comment]
Sorry, but we don't have any documentation or samples that show how to modify the default template. The [Baseline template](https://github.com/hegemonic/jsdoc-baseline) provides [summary blocks](https://github.com/hegemonic/jsdoc-baseline/blob/master/views/partials/summary-blocks.hbs) of the sort you're describing, but Baseline works very differently from the default template.
