### ISSUE TITLE
JSDoc 3.4.0 fails

### ISSUE THREAD

**Issue by kec2** [jsdoc3/jsdoc#1196]
I run jsdoc3.4.0 globally and i get this error.

![jsdoc3 4 0_fails](https://cloud.githubusercontent.com/assets/3109622/14519739/0b324ad6-0221-11e6-8391-268c963cd15d.jpg)

Everything works fine with jsdoc3.3.3

**Comment by hegemonic** [comment]
It looks like you're trying to run JSDoc with something other than Node.js. Sorry, but JSDoc only supports Node.js.
