### ISSUE TITLE
What is the status of documenting Promise

### ISSUE THREAD

**Issue by agirorn** [jsdoc3/jsdoc#1197]
I have been trying to make out what the plan is on how to document promises in jsdoc and can't seam to find any one solution. Can any one explain what the plan is, how it should be documented, when that is planed to be released, what is left to do to implement it  and dose the project need assistance in getting this done?

**Comment by dcollinsf5** [comment]
I asked about this in November of last year (https://github.com/jsdoc3/jsdoc/issues/1110) and was informed that the decision on how JSDoc will handle this has been made, but nothing has been implemented as of yet.  Given that the syntax has been decided upon, I have begun documenting all of my code with the syntax described.  For example:

`/** Get a list of user names`
`* @returns {Promise.<string[]>} Array of usernames`
`*/ `

Unfortunately, current JSDoc thinks that everything I document this way is an array of objects.
For example, this JSDOC:
`/** Get a single user object`
`* @returns {Promise.<userObject>} A single user objects`
`*/ `

Is output in the JSDOC as:
'RETURNS: Array of userObject'

I've been ignoring this inaccuracy, and just dealing it while we wait for support to be officially added; it's more important that things have some documentation even if it's inaccurate until the next JSDoc version

**Comment by Sequoia** [comment]
#509 was locked so I won't start it up again out of respect for moderators here, but I also am not clear on how that thread resolved. 

## Question
I'm not even using JSdoc right now so impl isn't that important, I just want to know if there's a standard syntax so I can use it. **Are `@fulfills` & `@rejects` what was settled upon?** For me, knowing this is enough-- I'll start using so my code will be future-ready.

**Comment by saschagehlich** [comment]
I'm gonna ping @hegemonic here - Promises have become an important part of modern JavaScript. Can you tell us what is going to be implemented?

**Comment by icopp** [comment]
My only comment is that what looks like the proposed syntax...

```
/**
 * @promise PromiseTypeName
 * @fulfills {type} description
 * @rejects  {type} description
 */

/**
 * @returns {PromiseTypeName}
 */
function () {}
```

...seems overly voluminous, while the proposed shorthand...

```
/**
 * @returns {Promise.<type>} description
 */
function () {}
```

...seems overly verbose, discarding valuable info on types and cramming both fulfillment info and timing info into the same line. It seems like a better happy medium for shorthand would be something like:

```
/**
 * @returns  {Promise} description
 * @fulfills {type}    description
 * @rejects  {type}    description
 */
function () {}
```

This allows for a good description for one-off promises without having to discard or overly compress any of the info involved.

**Comment by michaelalhilly** [comment]
I agree with using the following with the exception of @fulfills. The more common callback name to use is @resolve which is the same as the Promise method Promise.resolve().
``
/**
 * @returns  {Promise} description
 * @resolve {type}    description
 * @rejects  {type}    description
 */
``

**Comment by saschagehlich** [comment]
This is so sad - this issue has been around for way more than a year now and there is no official statement from the JSDoc developers. Documentation is one of the most important aspects of software development and JSDoc seems to be the only option for JS documentation... and it seems to be dead / unmaintained.

**Comment by Sequoia** [comment]
@saschagehlich They are probably all off using typescript 😄

**Comment by oanguenot** [comment]
@saschagehlich +1

**Comment by hegemonic** [comment]
You can use this syntax to document promises today:

```js
/**
 * Retrieve the user's favorite color.
 *
 * @returns {Promise<string>} A promise that contains the user's favorite color
 * when fulfilled.
 */
User.prototype.getFavoriteColor = function() {
    // ...
};
```

This is the recommended way to document promises. The only downside is that you can't document the error condition this way.

This is the syntax that will be supported at some point in the future, for users who need to document the error condition:

```js
/**
 * A promise for the user's favorite color.
 *
 * @promise FavoriteColorPromise
 * @fulfill {string} The user's favorite color.
 * @reject {TypeError} The user's favorite color is an invalid type.
 * @reject {MissingColorError} The user has not specified a favorite color.
 */

/**
 * Retrieve the user's favorite color.
 *
 * @returns {FavoriteColorPromise} A promise for the user's favorite color.
 */
User.prototype.getFavoriteColor = function() {
    // ...
};
```
