### ISSUE TITLE
Block comments within @example tags

### ISSUE THREAD

**Issue by not-an-aardvark** [jsdoc3/jsdoc#1207]
Sometimes I want to use a block comment in an @example tag:

``` js
/**
* @summary Does something
* @example
*
* Foo(5);
* /* This is a block comment within an @example block.
* Unfortunately it doesn't work and it results
* in a syntax error, because a `*` followed by a `/` will end the entire jsdoc
* comment block. */
*/ // <-- syntax error
function Foo () {}
```

I've tried escaping the closing `*/` by preceding the `/` with a backslash, but the backslash still renders as part of the example. Is there a supported way to use block comments like this?

**Comment by zxqfox** [comment]
Commit in the master. Feel free to close this

**Comment by zxqfox** [comment]
Feels like it can be if we split `*` and `/` like you did: `*\/`.

I feel it a little bit hacky but natively. Don't see better ways to escape that.

**Comment by not-an-aardvark** [comment]
A commit was made to a fork, but I don't think this issue has been fixed on the master branch of `jsdoc3/jsdoc`.

**Comment by hegemonic** [comment]
Sorry, but this isn't supported, and I don't think there's any way to fix this issue without potentially causing breakage for some users.
