### ISSUE TITLE
issue in libs/jsdoc/path.getResourcePath

### ISSUE THREAD

**Issue by Uxspy** [jsdoc3/jsdoc#1208]
Well, guys, I found a very tricky issue when I use gulp-jsdoc which wraps jsdoc3, the issue is jsdocs reports `Module Not Found` for one of its plugins `markdown`, it tried to load `markdown` from my working directory rather than it's node_modules folder where suppose it should be.

When I debug I found the only reason is that there happens to be a folder called `plugin` under my working directory. Then I found the code below(`libs/jsdoc/path.js line:129`):

```
// absolute paths are normalized by path.resolve on the first pass
[path.dirname(env.opts.configure || ''), env.pwd, env.dirname].forEach(function(_path) {
    if (!result && _path) {
        _path = path.resolve(_path, filepath);
        if ( pathExists(_path) && (filename ? fileExists(path.join(_path, filename)) : true)) {
            result = _path;
        }
    }
});
```

To the code above and in this case, it tried to find the absolute path for jsdoc's `plugins` from these 3 places: env.opts.configure, env.pwd and env.dirname, once it found, it will return.

In this case, there's a `plugin` folder under env.dirname, and there also **HAPPENS TO** be a `plugin` folder under env.pwd(which is my working directory and believe me that that's NOT the right folder which contains its toys), anyway, since env.pwd comes first, so the `incorrect path` returned.

So, guys, please take care of this, thanks!

**Comment by hegemonic** [comment]
This should be fixed by https://github.com/jsdoc3/jsdoc/commit/4a187da5. The fix will be released in JSDoc 3.5.0.
