### ISSUE TITLE
Can support sass

### ISSUE THREAD

**Issue by guohuihot** [jsdoc3/jsdoc#1213]
Can support sass, for example
```
/**
 * opacity
 * @param  {number} $opacity .5
 */
@mixin opacity($opacity) {
  opacity: $opacity;
  // IE8 filter
  $opacity-ie: ($opacity * 100);
  filter: alpha(opacity=$opacity-ie);
}
```

**Comment by pixelass** [comment]
Why not use [sassdoc](http://sassdoc.com/) which was specifically made to generate jsdoc like documentations for Sass.

It also respects a lot of tags that are Sass speciffic

**Comment by hegemonic** [comment]
JSDoc is for documenting Javascript. I don't have any plans to make it support other languages, including Sass.

Fortunately, SassDoc looks like a great alternative!
