### ISSUE TITLE
@alias should not override name and longname

### ISSUE THREAD

**Issue by onury** [jsdoc3/jsdoc#1217]
#### Documentation
```js
/**
 *  ...
 *  @alias lib.secondaryName
 *  @memberof lib
 */
function originalName() { .. }
```
#### outputs:
```js
{
    "code": {
        "name": "lib.originalName", // original name is only documented here
        ...
    },
    "alias": "lib.secondaryName", // alias
    "name": "secondaryName", // alias
    "longname": "lib.secondaryName", // alias
    ...
}
```
This is misleading. Since aliases are secondary names, the `name` and `longname` of the symbol should be kept unchanged. We already have the `alias` documented.

**Comment by hegemonic** [comment]
The whole point of the `@alias` tag is to treat the symbol as though it had a different longname. [See the docs for this tag](http://usejsdoc.org/tags-alias.html). Sorry, but we can't change this tag's behavior without breaking a lot of people.
