### ISSUE TITLE
which template engine is used

### ISSUE THREAD

**Issue by pixelass** [jsdoc3/jsdoc#1224]
It seems to be impossible to figure out which template engie uses `<?js`

Can you please document this and recommend a syntax highlighter. 

After 2hrs of unsuccessful web searches I decided to make this an issue

**Comment by pixelass** [comment]
Seems to be underscore with custom delimiters. 

https://github.com/jsdoc3/jsdoc/blob/fb2c36781f01d74c13f3e5eabe96763646c264c6/lib/jsdoc/template.js#L26-L31

Is there any way to get some syntax highlighting for this?

I would suggest documenting this somewhere as it seems very important information if you want to create themes.  IMHO using these custom delimiters really break the experience as a developer.

I can't imagine I'm the only one who has wasted hours on this.

**Comment by hegemonic** [comment]
Sorry, but it's unlikely that anyone will provide syntax highlighting for JSDoc's custom delimiters. I agree that the custom delimiters are annoying, but at this point it's too late to do anything about them.

**Comment by Azmisov** [comment]
You can use the `Underscore Template Colorizer` extension for VSCode. It supports the `<?js ?>` delimiters.
