### ISSUE TITLE
Allow putting documentation after members

### ISSUE THREAD

**Issue by FriendFX** [jsdoc3/jsdoc#1227]
Having used Doxygen in the past, I came to like its [Putting documentation after members](http://www.stack.nl/~dimitri/doxygen/manual/docblocks.html#memberdoc) syntax in some cases.

Here is an example:

```
var numbers = {
  one:   1, /**< A single item */
  two:   2, /**< Two items */
  three: 3  /**< Three items */
}
```

This lends itself particularly well to table-like initialisations and similar code structures where the documentation consists of just a single line or less.

**Comment by hegemonic** [comment]
Thanks for the suggestion. Unfortunately, it would be extremely difficult to implement, and I think the difficulty of implementing this suggestion outweighs the value it would add. For that reason, I'm closing this issue.
