### ISSUE TITLE
Child classes without constructor are ignored

### ISSUE THREAD

**Issue by bensampaio** [jsdoc3/jsdoc#1230]
If I have the following files:

``` js
// src/A.js

/**
 * A beautiful class
 */
export default class A {

  /**
   * Beautifully initialises everything.
   */
  constructor() {}
}
```

``` js
// src/B.js
import A from './A.js';

/**
 * Amazing class.
 * @extends A
 */
export default class B extends A {

  /**
   * Determines how amazing this class is.
   */
  someMethod() {}

}
```

And then run `jsdoc src -r -d docs`, only `A` will be in the generated documentaion. If I add a `constructor` to class `B` and then run the above command again, `B` will already be in the generated documentation. Is this a know issue or am I doing anything wrong? Thank you!

**Comment by hegemonic** [comment]
There have been a lot of changes to how JSDoc handles ES2015 classes and modules. The following examples work okay for me on GitHub master (which should closely match JSDoc 3.5.1):

```js
// src/A.js

/** @module A */

/**
 * A beautiful class
 */
export default class A {

  /**
   * Beautifully initialises everything.
   */
  constructor() {}
}
```

```js
// src/B.js

/** @module B */

import A from './A.js';

/**
 * Amazing class.
 * @extends A
 */
export default class B extends A {

  /**
   * Determines how amazing this class is.
   */
  someMethod() {}

}
```
