### ISSUE TITLE
Can you resolve this comment?

### ISSUE THREAD

**Issue by guohuihot** [jsdoc3/jsdoc#1232]
```
{# 
/**
 * 设置菜单-字段
 * dropdownFormField(o)
 * @param o.field 字段名
 * @param o.model 服务
 * @param o.title 标题
 */
 #}
{% macro dropdownFormField(o) %}
    <div class="dropdown dropup">
        <button class="btn btn-sm btn-default dropdown-toggle" type="button" id="dropdown{{ o.field }}" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            {{ o.title }}
            <span class="caret"></span>
        </button>
            
        <ul class="dropdown-menu" aria-labelledby="dropdown{{ o.field }}">
            {% for item in o.model|getFormField(o.field) %}
            <li>
                <a data-role="submit" data-name="{{ o.field }}" data-value="{{ item.value }}" href="#">{{ item.title }}</a>
            </li>
            {% endfor %}
        </ul>
    </div>
{% endmacro %}
```
This is the twig template, fileName `abc.html.twig` not `.js`

**Comment by hegemonic** [comment]
JSDoc isn't designed to work with non-JavaScript files. However, you can use the [`commentsOnly` plugin](https://github.com/jsdoc3/jsdoc/blob/master/plugins/commentsOnly.js) to tell JSDoc to ignore everything except the JSDoc comments. That will allow JSDoc to parse your file. See also the [docs for enabling plugins](http://usejsdoc.org/about-plugins.html#creating-and-enabling-a-plugin).

You'll also need to add a `@name` tag to each JSDoc comment so JSDoc knows the name of the function.
