### ISSUE TITLE
Adding my own documentation, just like Tutorials

### ISSUE THREAD

**Issue by seckwei** [jsdoc3/jsdoc#1233]
I understand that we can add in our own tutorial documents, but is there a way to add my own documentation file/folder for JSDoc to include in the generated docs?
For example, I have documented my own process of doing the project, problems faced, solutions, etc but I'd like to include those docs too.

I have Googled and searched in the issues but to no avail. Any ideas?

Thanks

**Comment by AndrewGuenther** [comment]
You could just copy those files into your document output folder as a separate step. Then, you can use the `@link` tag in order to reference them.

**Comment by hegemonic** [comment]
JSDoc's default template allows you to copy static files to the output directory during the doc-generation process. See the [documentation](http://usejsdoc.org/about-configuring-default-template.html#copying-static-files-to-the-output-directory) for details.

However, if you want to include links to the static files in the navbar or anything like that, you would need to fork and modify the default template.
