### ISSUE TITLE
Add support for triple slash single line comments for indicating documention blocks

### ISSUE THREAD

**Issue by rd-secretstuff** [jsdoc3/jsdoc#1237]
Instead of using 
```
/**
* My comments go here
* Second line comment
* third line comment
*/
```

I would like to use 
```
/// My comments go here
/// Second line comment
/// Third line comment
```

I personally use block comments (i.e. /* ... */ ) for temporary commenting out code, not for documentation. This is because block comments cannot be nested, so I will always run into a problem where only part of the code gets commented out, forcing me to comment code out in parts or to use line comments (i.e. // ...) over multiple lines.

triple slash can be used to distinguish comments you want to have documented from the other comments in a similar fashion as /** is used now. (doxygen for instance supports this).

**Comment by hegemonic** [comment]
JSDoc includes a [`commentConvert` plugin](https://github.com/jsdoc3/jsdoc/blob/master/plugins/commentConvert.js) to support exactly this feature. [See the documentation](http://usejsdoc.org/about-plugins.html#creating-and-enabling-a-plugin) to learn how to enable plugins.

**Comment by iambumblehead** [comment]
@hegemonic is the commentConvert plugin you mentioned still available somewhere?

**Comment by iambumblehead** [comment]
maybe this... https://gitlab.cas.mcmaster.ca/theateam/FloppyFishGroup/-/blob/c953e275b9f61d66c4485b7331bcf933305b0c1e/JavaSriptDocs/jsdoc/plugins/commentConvert.js

**Comment by iambumblehead** [comment]
double|triple-slash comments,
 * shorter, less vertical space,
 * flexible, safely include nested comments and regular expressions,
 * flexible, safely be embeddable inside larger comment areas

it would be great if there were a programming-language-agnostic documentation generator offering a completed solution that supported both block-style javadoc and double|triple-slash style
