### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by FezVrasta** [jsdoc3/jsdoc#1239]
I'm wondering if this project is dead, if so I'd like to know it so I can switch to a different one.

Thanks.

**Comment by colinclarkbcgdv** [comment]
looks like it

**Comment by RainbowDangerDash** [comment]
ripperoni

**Comment by pixelass** [comment]
+1 for some info. I have been suspecting the same.

**Comment by OussamaRomdhane** [comment]
Looks dead to me by some of the issues and PRs here.
But I here some talks about a new release that is coming up.
I'm adding jsdocs to a project I'm working on but this makes me worry I won't find the right tool to generate docs once I'm done, make me question whether it is worth it to add jsdoc.
Maybe @hegemonic can answer this question.

**Comment by seansd** [comment]
+1 for some info as well as I'm very much wanting to use this stuff. . and all the PR's look like they'd be nice to have.

Not too mention, in JSDoc 2, you could tell it to not bother trying to parse the file source code, and just have it use the ```@name comments to generate great docs but I don't see anything like that in version 3.

**Comment by AnilRedshift** [comment]
@tschaub You're the only one in the org who has a lot of (public) github activity. Do you have any status to report, or know if adding more maintainers etc would help? Having an (npm) tagged release for the ES2015 work etc. would really be useful. Not even including all of the built up issues and PR's.

Thanks!

**Comment by pixelass** [comment]
As of the current state of this library is should at least have a "deprecated" or "unmaintained" note.

Basic ES2015 or ES2016 code will not work due to too many issues. Therefore this library is not up to date and it seems it will not be updated in near future.

I would also like to use this thread to list possible alternatives. 

I have been looking left and right but cannot find a library that looks promising or works on ES2015/ES2016 code

In my latest tests I played around with https://github.com/tj/dox but it also has too many issues and does not deliver a usable structure. The resulting JSON has to be parsed and all connections have do be done manually. The output is IMHO not usable for "big" & "precise" documentations 

I also tested [esdoc](https://github.com/esdoc/esdoc) but the output is unsorted and a lot of things just don't get generated


For now I will just stop putting any effort into doc-generation. I'd be happy if others also mentioned some alternatives and experiences since I really hate not having a generated documentation for my projects.

**Comment by seansd** [comment]
I actually went back to using the old JSDoc 2.  That system had a command line option (-n or --nocode), that would skip parsing the code all together, and just create documents based on comments that have the ```@name tag.  Combined with namepaths, it works gloriously well and in fact allows the engine to do doc generation from any language that handles C-style comments (so ES2015 and beyond is a non-issue). Plus it's template system was already customizeable/flushed out (uses old school JSPlate).

**Comment by hegemonic** [comment]
JSDoc is not dead! It's just taking a long nap while I deal with some stuff in my personal life. I hope to return to more active JSDoc development sometime soon.

@seansd: JSDoc 3 includes a [`commentsOnly` plugin](https://github.com/jsdoc3/jsdoc/blob/master/plugins/commentsOnly.js) that accomplishes the same thing as JSDoc 2's `--nocode` option. [See the documentation](http://usejsdoc.org/about-plugins.html#creating-and-enabling-a-plugin) for instructions on enabling plugins.

**Comment by OussamaRomdhane** [comment]
@hegemonic Thank you for your answer and good luck in whatever you are facing in life :smile: 
Cheers!

**Comment by pixelass** [comment]
@hegemonic nice to hear from you and good luck.

**Comment by pixelass** [comment]
@seansd jsdoc uses undersore and taffydb for the publish script

**Comment by hegemonic** [comment]
@seansd:

1. The `-q` command-line option allows you to pass in data that will be available through `env.query` in template files. I'm not sure how that compares to the old `-D` option.
2. JSDoc 3 uses Underscore.js templating with custom delimiters. Unfortunately, JSDoc 2 templates are not compatible with JSDoc 3--you'll need to re-customize your template. (JSDoc 3's default template does include built-in functionality to [copy static files to the output directory](http://usejsdoc.org/about-configuring-default-template.html#copying-static-files-to-the-output-directory).)

**Comment by valnub** [comment]
As of 2018 - Is jsdoc still dead or has it risen from the zombies?
If it's dead, what are the alternatives?
Found this but it lacks a bit the details https://www.slant.co/options/13737/alternatives/~jsdoc-alternatives

**Comment by pixelass** [comment]
@valnub. I switched to esdoc which does a good job. It's different but compatible and actively maintained.

**Comment by jcrben** [comment]
fyi, it looks like @pixelass is working on a fork of esdoc over at https://github.com/esdoc2/esdoc2 - sounds like it will have a more open approach to maintainers

@hegemonic any luck in accepting more contributors? there are open security vulnerabilities associated with this project

**Comment by lll000111** [comment]
Let's face it, and I don't understand why the maintainer won't just admit it, this project **IS** dead. Sooo many issues, for example I'm chasing why varying but incomplete output is produced even though there are no errors and everything is correct - must be some nested arrow function code (function returning function returning function) which jsdoc3 cannot deal with (but like its maintainer it does not admit it - no errors, just swallowing random bits of output from that file).

**Comment by iPherian** [comment]
There's obviously a lot of interest. We just need a contributor or two. 

@hegemonic more contributors please

**Comment by dessant** [comment]
https://documentation.js.org works well and it is maintained.
