### ISSUE TITLE
How to create a new Kind

### ISSUE THREAD

**Issue by EmpireWorld** [jsdoc3/jsdoc#1242]
i want to create a new kind like events for hooks.
that must be documented outside of all and can be visible in home page.

**Comment by hegemonic** [comment]
This would involve a lot of work to customize the default template. Unfortunately, there are no docs for customizing the default template, but you may be able to figure this out by seeing how the default template implements things like the "Events" section. You can also ask for help on the [JSDoc Users mailing list](http://groups.google.com/group/jsdoc-users).

**Comment by EmpireWorld** [comment]
Thanks
