### ISSUE TITLE
New to jsdoc template

### ISSUE THREAD

**Issue by hugohuynh** [jsdoc3/jsdoc#1245]
Hi,
I'm quite confusing with tmpl file. What are technology jsdoc template has used. Let say How can I to set a java script variable in client side from server side in tmpl like this.

  <script>
        var obj_nav =  <?js this.category ?> ;
   </script>

It doesn't work.

Thanks,
Trung.

**Comment by hegemonic** [comment]
JSDoc uses Underscore.js' templating system with custom delimiters.

[Here's the code](https://github.com/jsdoc3/jsdoc/blob/8c07fc519d509d17ad2f595f7d01c399fe892299/templates/default/publish.js#L212) that sets the context for the template. If you want to pass in additional information to the template, you could fork the template and modify the `generate` function in `publish.js`.

**Comment by hugohuynh** [comment]
Hi hegemonic,
Thanks a lot. I have one more question, please advise. Let say I added `category ` variable to `publish.js` file in `exports.publish` function for instance `view.category = "TEST"`. Then I would like to get the value of the variable then assign to a local javascript variable `str_cat` in `layout.tmpl` like this. But it didn't work.

In `layout.tmpl` file.
```
 <script>
        var str_cat =  <?js this.category ?> ;
 </script>
```
Thanks,
Trung.

**Comment by cancerberoSgx** [comment]
I generate an output using several template so we can compare which is the most suitable according to one's needs: https://cancerberosgx.github.io/jsdoc-templates-demo/demo/ I will put more with time but I think this is really helpful to make a decision. Also its documented how each of them is generated. Hope it helps!
