### ISSUE TITLE
How to call an exported function of a plugin in publish.js

### ISSUE THREAD

**Issue by hugohuynh** [jsdoc3/jsdoc#1247]
Hi,
I have implemented a plugin so call `category.js` that support `@category` tag. The plugin has been loaded and can get `@category` tag successfully. But I also have exported `processCategories `  function in `category.js`
```
exports.defineTags = function(dictionary) {
   dictionary.defineTag('category', {
    // do my stuffs
}
exports.handlers = {
    parseBegin: function() {
        // do my stuffs
    },
};
exports.processCategories = function (categories){
    // do some stuffs here
};
```
Is it possible to call `processCategories `function in `publish.js` file without requiring `require('path_to/categories')` because I think jsdoc already loaded the plugin so there is no need to require it again.

Thanks,
Trung.

**Comment by hegemonic** [comment]
It's not possible to call plugin functions from `publish.js`. You'll have to either a) do all of the work in the plugin itself or b) modify `publish.js` to include your new function.
