### ISSUE TITLE
Documenting use of global variable

### ISSUE THREAD

**Issue by richard-jones** [jsdoc3/jsdoc#1248]
I'm new to jsdoc so apologies if this is already covered elsewhere.

Today I was looking to document a function which looks for a global variable and acts based on whether it finds it or not.  In a way that's kind of a parameter to the function, so I wanted to document it, but I couldn't find a suitable way to do so (except in the descriptive text).

If that's useful to other people, perhaps something along the lines of

    @depends myGlobal <some descriptive information about the global>

Thanks for jsdoc, by the way, I'm just getting to grips with it, and it's excellent.

**Comment by hegemonic** [comment]
Glad to hear you like JSDoc!

In this case, I suggest just documenting this behavior in the descriptive text. I'd prefer not to add a new tag for this use case.
