### ISSUE TITLE
TaffyDB package name changed

### ISSUE THREAD

**Issue by joseym** [jsdoc3/jsdoc#1249]
[hegemonic/taffydb/package.json#L2](https://github.com/hegemonic/taffydb/blob/507d2d75fa16e1386f6d50abee1894b264d4458b/package.json#L2)

I noticed this earlier when cleaning npm cache. Apparently the `hegemonic/taffydb` decided to change the package name from `taffydb` to `taffydb-jsdoc` which causes the following error:

```
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3

npm ERR! Invalid Package: expected taffydb but found taffydb-jsdoc
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by lopesc** [comment]
+1

**Comment by wesleytodd** [comment]
This needs to be fixed ASAP.  Pointing a production dependency to a git repo is probably a bad idea :)

Also makes it difficult that npm doesn't tell you which dep causes this package to be installed, because I am having trouble finding it in our dep tree to remove it.

**Comment by hegemonic** [comment]
This has been fixed.
