### ISSUE TITLE
Commit 6be9dac6 introduces requirement ".js" not be included in plugin name

### ISSUE THREAD

**Issue by exaltedone** [jsdoc3/jsdoc#1251]
I previously had a plugin listed in my conf.json as:
    "plugins": [
        "plugins/somefile.js"
    ],

However, running jsdoc now returns the error:
ERROR: Unable to find the plugin "plugins/somefile.js"

Looks like commit 6be9dac6 introduced the following change:
-        var pluginPath = path.getResourcePath(dirname);
-        // convoluted way to detect the correct path for the plugins; done this round-about way to cope
-        // with scenarios where JSDoc is executed in another project's working directory where that
-        // project has plugins of itself in a similar directory structure (plugins/*)
-        var pluginPath = path.getResourcePath(dirname, basename + ".js");

which will give the above error if a plugin has a .js suffix.

**Comment by hegemonic** [comment]
I believe this issue was fixed in JSDoc 3.4.2.
