### ISSUE TITLE
Failed to parse tutorial config.json in utf8 BOM

### ISSUE THREAD

**Issue by artin-phares** [jsdoc3/jsdoc#1256]
Hi, I'm trying to add config.json for my tutorials and receiving exception:

```
SyntaxError: Unexpected token ? in JSON at position 0
    at Object.parse (native)
    at d:\Workspaces\TerminalUI\Main\node_modules\jsdoc\lib\jsdoc\tutorial\resolver.js:141:37
```

config.json encoded to utf8-BOM. When encoded to utf8 (without BOM) everything is OK.  

I believe the reason is that [fs.readFile() does not strip BOM markers](https://github.com/nodejs/node-v0.x-archive/issues/1918) which leads to invalid JSON.
[Here](http://stackoverflow.com/a/24376813/1064570) are possible solutions...

windows v7, nodejs v6.4.0

**Comment by hegemonic** [comment]
Fixed on master. The fix will be included in JSDoc 3.5.0.
