### ISSUE TITLE
Where is the JSDoc formal specification?

### ISSUE THREAD

**Issue by jtlapp** [jsdoc3/jsdoc#1257]
I can't find a specification for JSDoc. I'm only seeing pages that require me to infer JSDoc syntax from examples, and I'm not finding anything comprehensive there either. Is there a spec? Anything out there that attempts to comprehensively communicate JSDoc? Or do we infer from Javadoc?

**Comment by hegemonic** [comment]
Sorry, but there's no formal specification. However, the [Use JSDoc website](http://usejsdoc.org/) includes detailed documentation for each JSDoc tag. If you can't find the answers you're looking for on that site, please [file an issue in the documentation repo](https://github.com/jsdoc3/jsdoc3.github.com/issues).

**Comment by jtlapp** [comment]
I spent 10 minutes looking around on that site and decided that I didn't know how to find the information I want. I was looking for comment expectations for things other than parameters.
