### ISSUE TITLE
Using object spread operator still crashes jsdoc

### ISSUE THREAD

**Issue by leeyeh** [jsdoc3/jsdoc#1258]
Object spread operator is supported in v3.4.1

It still throw an Error when parsing the code below:

```javascript
var a = { b, ...c }
```

`ERROR: Unable to parse /home/travis/build/leancloud/js-realtime-sdk/src/conversation.js: Line 41: Invalid left-hand side in formals list`

It's a bug of espree and has already been fixed in v3: https://github.com/eslint/espree/pull/249

**Comment by hegemonic** [comment]
Thanks for the report. Unfortunately, upgrading to Espree v3 is going to take a lot of work, but it needs to be done at some point. I'll look into it.

**Comment by hegemonic** [comment]
Upgrading Espree didn't take nearly as much work as I expected! This issue should now be fixed on master and releases/3.4. The fix will be included in JSDoc 3.4.2.
