### ISSUE TITLE
v3.4.1 can not find plugins node_modules

### ISSUE THREAD

**Issue by leeyeh** [jsdoc3/jsdoc#1259]
I installed jsdoc-ignore-future plugin in node_modules and my config looks like:

```json
{
  "plugins": ["node_modules/jsdoc-ignore-future"]
}
```

It works in jsdoc@3.4.0, but breaks after upgrade to v3.4.1 with Error `Unable to find the plugin "node_modules/jsdoc-ignore-future"`

I checked the changes and find this commit related: https://github.com/jsdoc3/jsdoc/commit/6be9dac616549ce226e4c0064876c7cb3b64fe25#diff-2cce40143051e25f811b56c79d619bf5R320

Currently, changing my config to

```json
{
  "plugins": ["node_modules/jsdoc-ignore-future/index"]
}
```
 
resolves the crash, but is not elegant since I need to care about the structure of the plugin package.

Will it be better if we use the internal require mechanism of node?

**Comment by hegemonic** [comment]
Well, that's no good! I reverted the fix for #1081, so this problem should now be resolved on master and releases/3.4. The fix will be included in JSDoc 3.4.2.
