### ISSUE TITLE
[UI] The navigation design of doc site is poor for jumping one link to another

### ISSUE THREAD

**Issue by e-cloud** [jsdoc3/jsdoc#1260]
When someone wants to figure out how to use some tags, he/she has to click one link, read through, and naviagte back, and click another link...

It would be great to be able to naviagte inside one page.

**Comment by hegemonic** [comment]
Thanks for the feedback. For a variety of reasons, though, I prefer to keep the navigation as it is.

(P.S. For future reference, please file documentation issues in the [documentation repo](https://github.com/jsdoc3/jsdoc3.github.com/). Thanks.)
