### ISSUE TITLE
Default values with spaces only work with optional parameters

### ISSUE THREAD

**Issue by guohuihot** [jsdoc3/jsdoc#1261]
```
@param {String} o.tpl=<a href="%url%" class="sort-btn %cls%">%title%<i class="up font-lp-12"></i><i class="down font-lp-11"></i></a> 按钮模板 %url%-要替换的`url` %title%-要替换的标题 %cls%-要替换的`class`
```
![image](https://cloud.githubusercontent.com/assets/3119995/18469337/67c9a2cc-79da-11e6-94b0-32200b749843.png)

**Comment by hegemonic** [comment]
I agree that this behavior is a little weird, but I don't think it's worth fixing. In general, if a parameter has a default value, it should be marked as optional rather than required, which fixes the issue. Just change your comment to look like this:

```
@param {String} [o.tpl=<a href="%url%" class="sort-btn %cls%">%title%<i class="up font-lp-12"></i><i class="down font-lp-11"></i></a> 按钮模板 %url%-要替换的`url` %title%-要替换的标题 %cls%-要替换的`class`]
```

**Comment by guohuihot** [comment]
It\'s OK, Thanks!
