### ISSUE TITLE
"Octal literals are not allowed in strict mode" for special characters

### ISSUE THREAD

**Issue by JamesCullum** [jsdoc3/jsdoc#1263]
In NodeJS, i have the following command which produces the error "Octal literals are not allowed in strict mode" when creating the doc. If i remove it, it works.

`process.stdout.write('\033c');`

This command [clears the console on windows](http://stackoverflow.com/a/26373971/1424378) and is a special character. There is no other way to get past this restriction, if i encode it and decode it (what shouldn't be necessary) it doesn't clear the console anymore.

**Comment by JamesCullum** [comment]
`process.stdout.write('\x1Bc');`  on the other hand work

**Comment by hegemonic** [comment]
Unfortunately, I don't see any easy way to fix this issue. But I think you're saying that there is a workaround, which is to use `'\x1Bc'` instead of the octal literal. I think that's the right approach.

**Comment by JamesCullum** [comment]
The easy issue would be fixing the regex or however this error gets produced. I dont think a workaround for a known issue, which obviously is methodically wrong, can be considered a serious solution.

**Comment by silverbucket** [comment]
When I try to run jsdoc 5.0 on my code I get the following error:

```
JSDOC_ERROR: ERROR: Unable to parse index.js: Octal literal in strict mode (309:24)
```

Offending line:
```
      const message = '\001ACTION ' + job.object.content + '\001';
```

This literal needs to be there for the functionality I'm implementing, I don't see any reason why it makes sense for jsdoc to simply fail to handle a file that has this string.
