### ISSUE TITLE
Object map of {type} vs Array of {type}

### ISSUE THREAD

**Issue by AMorgaut** [jsdoc3/jsdoc#1271]
It is quite easy to document Array properties for which all items are of the same type

ex:

``` js
{
    /**
     * @property {Movie[]} movies
     */
    movies: [grease, grease2, dirtyDancing]
}
```

But what if I need to document a property which is instead a map with identical value type

Could we use such notation?

``` js
{
    /**
     * @property {Keyword{}} keywords
     */
    keywords: {
        "module": {hits:42, lastHit: 1475492681888, rating: 4.5},
        "plugin": {hits:51, lastHit: 1475492681888, rating: 3.8},
        "extension": {hits:51, lastHit: 1475492681888, rating: 3.8}
    }
}
```

**Comment by AMorgaut** [comment]
I found this notation 
```js
/**
 * @type Object<number,string>
 */
var obj = {};
obj[1] = 'bar';
```
https://google.github.io/styleguide/javascriptguide.xml#JsTypes

Is it supported ? (or planned to be?)

**Comment by hegemonic** [comment]
For your first example, you can document the type as `Object<number, Keyword>`. For the second example, yes, `Object<number, string>` is correct.
