### ISSUE TITLE
Can't have multiple blocks of code for one example

### ISSUE THREAD

**Issue by mmclau14** [jsdoc3/jsdoc#1273]
Trying to figure out how i can have something like the following example:

@example
// example code goes here
// second block of example code, continuation of the first block - but separate and distinct code block

**Comment by jakeknerr** [comment]
Try
/**
 * @example
 *  // example code goes here
 * @example
 * // second block of example code, continuation of the first block - but separate and distinct code block
*/

**Comment by hegemonic** [comment]
@jakeknerr's solution is the best you can do for this.

**Comment by mmclau14** [comment]
thanks all. i figured as much
