### ISSUE TITLE
Unexpected character '@' with ES7 Decorators @connect ! hurry up!

### ISSUE THREAD

**Issue by seven1986** [jsdoc3/jsdoc#1276]
![s](https://cloud.githubusercontent.com/assets/20808494/19259950/803a72d4-8fb8-11e6-8ee4-69f57fe51c44.png)
# how can I solve this problem?  Just pass it and keep build document would be fine, I think.

**Comment by hegemonic** [comment]
JSDoc supports new ECMAScript features once they're implemented by [Espree](https://github.com/eslint/espree), our JavaScript parser. Once Espree implements this feature, JSDoc will be able to support it.

**Comment by joelday** [comment]
@hegemonic Are there any ECMAScript features that can't be expressed by Closure Compiler yet?

**Comment by georgezouq** [comment]
@hegemonic get this error `ERROR: Decorators cannot be used to decorate object literal properties`, when use decorators like this:

```
export default {
  @loading("loading")
  async mounted() {
    await this.getData();
  },
}
```

how to fix?

**Comment by pinturic** [comment]
I am having the same issue. Is there any plan to fix it ?
