### ISSUE TITLE
formalize the use of {} around any namepath

### ISSUE THREAD

**Issue by Netmosfera** [jsdoc3/jsdoc#1280]
```
@name graph_parens_not_needed
@type {graph_parens_needed}
@this graph_parens_not_needed
```

having to remember whether parens are needed or not is hard.
editors like webstorm already allow parens to be added even when not necessary, jsdoc should do the same, even just for consistency's sake

thanks

**Comment by ProLoser** [comment]
`{}` is consistently used to refer to types. Like how `@param {type} name` works. It seems consistent enough to me.

**Comment by hegemonic** [comment]
I agree with @ProLoser, particularly because you can already omit the braces from the `@type` tag.
