### ISSUE TITLE
Include a sideEffect block tag

### ISSUE THREAD

**Issue by jdetle** [jsdoc3/jsdoc#1283]
**Problem**:
In some cases when writing a function, side-effects are unavoidable, but they shouldn't be undocumentable. 

**Solution**:
I'd be happy to try to go in and make a PR to include a side-effect tag for easy API documentation. 

**Proof that I'm not the only one concerned about this**:
This [StackOverflow question](http://stackoverflow.com/questions/25314979/documenting-side-effects-of-javascript-methods) does a good job at summarizing my concern as well.

**Comment by hegemonic** [comment]
On GitHub master, JSDoc now provides a `@modifies` tag that serves this purpose. For example, you can write things like `@modifies {foo}` or `@modifies {(foo|bar)}`.

The new tag will be available in JSDoc 3.6.0.

**Comment by noelmace** [comment]
It's indeed undocumented, but it's there since 3.6.0
https://github.com/jsdoc/jsdoc/commit/2f99af8fbbfb7f19d9f962c40884a13ce38696da
linked to #605
