### ISSUE TITLE
Doesn't work with prototype methods?

### ISSUE THREAD

**Issue by Jakobud** [jsdoc3/jsdoc#1284]
I have this

```
@module MyObj
@desc ...
var MyObj = function(){
  // code
};

/**
@name something
@function
@memberof MyObj
*/
MyObj.prototype.something = function(){
  // more code
};
```

Only documentation for `MyObj` is generated. Nothing else. What am I misunderstanding here?

**Comment by Netmosfera** [comment]
```
/**
 * @class
 * @name MyClass
 */
function MyClass(){}

/**
 * @method
 * @name MyClass#something
 * @returns {!string}
 */
MyClass.prototype.something = function(){};
```

**Comment by Jakobud** [comment]
Thanks. I think the key to this is to use `@name MyClass#something` instead of `@name something`.

**Comment by mrself** [comment]
Instead of pointing `@name` for each method you can use the approach described [here](https://github.com/jsdoc3/jsdoc/issues/495#issuecomment-129924254). The result will be:

```
MyClass.prototype = /** @lends MyClass# */ {
constructor: MyClass,

/**
 * @returns {!string}
 */
something: function() { return 'x'; }
}
```
In this case you event do not need `@method`.

You can replace `@lends MyClass#` with `@lends MyClass.prototype`.
