### ISSUE TITLE
“There are no input files to process.” error while parsing with jsdoc

### ISSUE THREAD

**Issue by jsafield** [jsdoc3/jsdoc#1288]
I describe the situation here;
http://stackoverflow.com/questions/40299936/there-are-no-input-files-to-process-error-while-parsing-with-jsdoc

what can be the problem? thanks in advance.

**Comment by hegemonic** [comment]
It looks like you're using a Gulp or Grunt plugin, or something like that, to run JSDoc. Sorry, but I can't help with that.
