### ISSUE TITLE
<a> link not created when using @callback

### ISSUE THREAD

**Issue by GautierT** [jsdoc3/jsdoc#1291]
Hi,
I want to reference a callback in my function like this. 
The function and the callback are generated but the <a> link to the callback doc is not.

```
/**
 * Callback for updating a workflow
 *
 * @callback updateCallback
 * @param {Error} err
 * @param {Workflows} workflow - A workflow object
 */

/**
 *
 * Update a workflow
 * @function
 * @param {String|Workflows} workflow - A workflow or a workflow_id
 * @param {Object} updatedWorkflow - An updated workflow
 * @param {updateCallback}  callback - A callback function
 */

export function update(workflow, updatedWorkflow, callback) {
    // do things
}
```

Here is the output : 
![image](https://cloud.githubusercontent.com/assets/6089653/20154313/032a069e-a6c7-11e6-8fb2-3583432dfd57.png)

Am i doing something wrong or is this the correct behaviour ?

**Comment by djake** [comment]
I believe you have to use a namepath. If you have `@module workflows` on the top of this file, then you'd say `@callback workflows~updateCallback` and `@param {module:workflows~updateCallback} callback A callback function`

**Comment by hegemonic** [comment]
I believe @djake is correct. When I run your example through JSDoc, the link is created as expected.

**Comment by santiana** [comment]
Thanks for the explanation. This had me baffled - its not obvious from the documentation, and is IMO unnecessarily awkward. 

What @djake suggests does not quite work for me. In the example above, it only works if I say `@callback updateCallback` (ie. without `workflows~`). Why is `module:` required in the `@param` type? Can this not be inferred from the context?

**Comment by zeorin** [comment]
@santiana I had to do:
```
@param {module:workflows~updateCallback} callback - A callback

...

@callback module:workflows~updateCallback
```
For things to work correctly. I wish there was some way to simply reference the current module without explicity naming it (i.e. so I can keep using derived module names). Now I must manually name all my modules.
