### ISSUE TITLE
There are no input files to process

### ISSUE THREAD

**Issue by Mattomanka** [jsdoc3/jsdoc#1299]
Inside root directory I have `.jsdocrc` file. 
But if I run the command `jsdoc --configure .jsdocrc *.js`, I will get message 
```
ERROR: Unable to find the source file or directory D:\HomeProjects\logux\logux-client\*.js
There are no input files to process.
```

[https://github.com/logux/logux-client/blob/master/package.json](url)
[https://github.com/logux/logux-client/blob/master/.jsdocrc](url)
Current [https://travis-ci.org/logux/logux-client](url)

Can it be due to Win OS?
```
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "docs"
npm ERR! node v6.9.2
npm ERR! npm  v4.0.3
npm ERR! code ELIFECYCLE
npm ERR! logux-client@0.1.0 docs: `jsdoc --configure .jsdocrc *.js`
npm ERR! Exit status 1
```

**Comment by Dimezis** [comment]
Same stuff

**Comment by Mattomanka** [comment]
@hegemonic How I can help with it?

**Comment by ai** [comment]
@hegemonic any updates? This issue affects to my repos. Maybe we could provide more details?

**Comment by codeocelot** [comment]
I'm getting the same issue.  (MacOS 10.12, node v6.0.0, npm v3.8.6)

**Comment by hegemonic** [comment]
Usually this issue happens because part of the source path includes a leading underscore. By default, JSDoc ignores files and directories with leading underscores. However, that doesn't look like the issue that the original reporter is seeing.

If you're still running into this problem, please add a comment with the output you get from `jsdoc --debug`.

**Comment by hegemonic** [comment]
Closing due to lack of information.

**Comment by Mattomanka** [comment]
I still have this problem. 
I checked the path for the presence of a leading underscore, but there are none.
Output from `jsdoc --debug` :
```
D:\HomeProjects\logux\logux-client>jsdoc --debug
DEBUG: JSDoc 3.4.3 (Thu, 10 Nov 2016 00:25:10 GMT)
DEBUG: Environment info: {"env":{"conf":{"tags":{"allowUnknownTags":true,"dictionaries":["jsdoc","closure"]},"templates":{"monospaceLinks":false,"cleverLinks":false,"default":{"outputSourceFiles":true}},"source":{"includePattern":".+\\.js(doc|x)?$","excludePattern":"(^|\\/|\\\\)_"},"plugins":[]},"opts":{"_":[],"debug":true,"destination":"./out/","encoding":"utf8"}}}
There are no input files to process.

JSDoc 3.4.3 (Thu, 10 Nov 2016 00:25:10 GMT)
```

**Comment by BurtHarris** [comment]
@hegemonic, I seem to be getting the same error.  `>jsdoc -c test/config.json lib/*.js --debug` produces:

```
DEBUG: JSDoc 3.4.3 (Thu, 10 Nov 2016 00:25:10 GMT)
DEBUG: Environment info: {"env":{"conf":{"tags":{"allowUnknownTags":true,"dictionaries":["jsdoc","closure"]},"templates":{"monospaceLinks":false,"cleverLinks":false},"source":{"includePattern":".+\\.js(doc|x)?$","excludePattern":"(^|\\/|\\\\)_"},"plugins":[],"recurseDepth":10},"opts":{"_":["lib/*.js"],"configure":"test/config.json","debug":true,"destination":"./out/","encoding":"utf8"}}}
There are no input files to process.

JSDoc 3.4.3 (Thu, 10 Nov 2016 00:25:10 GMT)
```
...
 Unable to find the source file or directory

**Comment by chovy** [comment]
How do I specify a wildcard for files?

**Comment by brettz9** [comment]
FWIW, I got this error by my `excludePattern` having a `|` at the end without anything following it. Otherwise, wildcards like `**/*.js` seem to be working fine.
