### ISSUE TITLE
namepath with @ (at sign) in it

### ISSUE THREAD

**Issue by djake** [jsdoc3/jsdoc#1302]
I am attempting to document a namespaced NPM package, like `@prefix/my-module`. I am able to set `@module @prefix/mymodule`. I also have a callback definition, and need the namepath `module:@prefix/my-module~myCallback` so I can `@param module:@prefix/my-module~myCallback`. Parsing the `@param` is giving me an error, like: 

`JSDOC_ERROR: ERROR: Unable to parse a tag's type expression for source file /path/to/index.js with tag title "param" and text "{module:@prefix/my-module} cb Callback": Invalid type expression "module:@prefix/my-module".`

I think it is fairly obvious why I'm getting this error, I just can't figure out how to get around it. Am I doing this wrong? Is there some way to escape the `@` (at sign)? Users will `npm i @prefix/my-module` and `require('@prefix/my-module')`, so it is important that the prefix be included in the docs.

**Comment by hegemonic** [comment]
Sorry for the lengthy delay in responding to this issue. It's now fixed on the master and releases/3.5 branches. You should be able to pick up the fix simply by removing your `node_modules` directory and running `npm install`. If that doesn't work, the fix will definitely be included in JSDoc 3.5.3.

**Comment by djake** [comment]
Thank you very much for taking care of this and for your work on this project in general!
