### ISSUE TITLE
memberOf prevents ES6 methods to appear on documentation

### ISSUE THREAD

**Issue by danielo515** [jsdoc3/jsdoc#1303]
Hello,

Today I went crazy trying to document some ES6 classes.
The class name and constructor were picked up correctly, but none of the methods appeared.
I was documenting the methods like this:

```js
    /**
     * @returns summary Section
     * @memberOf Section
     */
    summary(){
        return
    }
```

JSDoc says that you don't have to specify things like `@class` or constructor, but it does not say that if you use memberOf the documentation will fail for that method. This was unexpected for me, not sure if it was a mistake using memberof or it is a bug.
The documentation comments were generated by documentIT vscode extension.

Thanks and regards

**Comment by danielo515** [comment]
Another weird and unexpected thing is that, if you don't provide a class description, none of the methods is documented, just the constructor. Why?

**Comment by Native-Coder** [comment]
This issue is posted 3 times on the first page alone...

https://github.com/jsdoc3/jsdoc/issues/1301

https://github.com/jsdoc3/jsdoc/issues/1293  <-- I actually posted a work around on this thread. Read the last comment

https://github.com/jsdoc3/jsdoc/issues/1272

**Comment by dxinteractive** [comment]
Having the same issue with `3.4.3`, and more. I'm using `@memberof` to compensate for jsdoc's failure to recognise the method nesting.

## Issues

- Only the class itself and the first method of a class has a doclet generated for it
- Unless the first method is a constructor, it will be documented with a name of "value", which is incorrect.

## Repro and output

Given this:

```
/**
 * My foobar class description.
 */
class Foobar {
  /**
   * Beep a foobar.
   * @memberof Foobar
   */
  beep() {
  }

  /**
   * Boop a foobar.
   * @memberof Foobar
   */
  boop() {
  }
}
```

I get the following doclets:

```
[
    {
        "longname": "Foobar",
        "name": "Foobar",
        "scope": "global",
        "kind": "class",
        "description": "<p>My foobar class description.</p>",
        "comment": "/**\n * My foobar class description.\n */"
    },
    {
        "longname": "Foobar.value",
        "name": "value",
        "memberof": "Foobar",
        "scope": "static",
        "kind": "function",
        "description": "<p>Beep a foobar.</p>",
        "comment": "/**\n         * Beep a foobar.\n         * @memberof Foobar\n         */"
    }
]
```

## Potential workaround

Use a `@name` tag for each method does circumvent the issue. That said, this really needs to be fixed at the source. I'm keen to contribute if there is a likely chance my changes will be considered.

@Native-Coder The three issues you've referenced aren't the exact same thing as #1293 and #1272, although they do have similar symptoms. This has nothing to do with exports, and the symptoms of #1301 sound different.

**Comment by hegemonic** [comment]
I think the problem is that you all are using `@memberof` tags when they're not needed. The following example works fine for me:

```js
/**
 * My foobar class description.
 */
class Foobar {
  /**
   * Beep a foobar.
   */
  beep() {
  }

  /**
   * Boop a foobar.
   */
  boop() {
  }
}
```

If that doesn't solve your problem, please provide a sample that illustrates why you're finding it necessary to include the `@memberof` tag.

**Comment by dxinteractive** [comment]
Hi @hegemonic , I added the `@memberof` tags because without them I have the same issue, plus the class methods don't fill in their own `memberof` tags. Running your above example with jsdoc `3.4.3` I get:

```
{
        "meta": {
            "range": [
                780,
                1099
            ],
            "filename": "Test.js",
            "lineno": 10,
            "path": "/mnt/c/Users/Damienn/Documents/make/web/react-component-grid/src",
            "code": {
                "id": "astnode100002058",
                "name": "Foobar",
                "type": "CallExpression",
                "value": ""
            }
        },
        "longname": "Foobar",
        "name": "Foobar",
        "scope": "global",
        "kind": "member",
        "___s": true,
        "___id": "T000002R000249",
        "description": "<p>My foobar class description.</p>",
        "comment": "/**\n * My foobar class description.\n */"
    },
    {
        "meta": {
            "range": [
                951,
                976
            ],
            "filename": "Test.js",
            "lineno": 21,
            "path": "/mnt/c/Users/Damienn/Documents/make/web/react-component-grid/src",
            "code": {
                "id": "astnode100002079",
                "name": "value",
                "type": "FunctionExpression",
                "value": "beep"
            }
        },
        "longname": "value",
        "name": "value",
        "scope": "global",
        "kind": "function",
        "___s": true,
        "___id": "T000002R000252",
        "description": "<p>Beep a foobar.</p>",
        "comment": "/**\n     * Beep a foobar.\n     */"
    },
```

Right now it's within a small node project using the default `conf.json`, and there are a couple of other files being documented too. Is there a standard test harness or something I should be using to eliminate issues specific to my own usage, to be sure I'm running it the same way as you?

The above output I'm getting still has only the first doclet within the class being picked up, and its `name` comes through as `value` which is very strange.

**Comment by sasha240100** [comment]
@hegemonic Doesn't work for me
