### ISSUE TITLE
es6: event names containing a dot don't work.

### ISSUE THREAD

**Issue by namel** [jsdoc3/jsdoc#1304]
Declaring an event

```javascript
/**
 * foo just happened on the client
 *
 * @memberof Engine
 * @event client.foo
 */
```

This causes much strangeness - the menu doesn't show the word "client".  The following approaches didn't work either:

- declaring the event inside the class, without `@memberof`
- declaring `client.foo` with single quotes or double quotes caused the quotes to be included in the event name in the output
- escaping the dot

**Comment by hegemonic** [comment]
The correct solution is to enclose the event name in double quotes. I believe there's a separate issue to remove the quotes in the generated documentation.
