### ISSUE TITLE
@lends is broken, or example is incorrect

### ISSUE THREAD

**Issue by drjayvee** [jsdoc3/jsdoc#1305]
I've tried 3.4.3 and (today's) 3.5.0-dev on last two examples [example for `@lends`](http://usejsdoc.org/tags-lends.html), but jsdoc doesn't list the instance methods at all:
> Class: Person
> Person
> new Person()
> 
> Source:
>         tehst.js, line 2

So either `@lends` has been broken for a while, or the examples are wrong.

**Comment by drjayvee** [comment]
Related to #1265

**Comment by purtuga** [comment]
Related #1130 ... In that thread, I mentioned a pending contribution, but it also did work for me...

**Comment by hegemonic** [comment]
The problem with the examples is that the methods didn't have any comments, so no documentation was being generated for them. I've fixed the examples, and they should now work out of the box.
