### ISSUE TITLE
Error on parsing

### ISSUE THREAD

**Issue by Fohlen** [jsdoc3/jsdoc#1306]
Heya there .. I am getting 
`ERROR: Unable to parse /home/fohlen/workspace/inexor/flex/src/connector/index.js: Assigning to rvalue`
when generating JSDoc configuration with ES6 code.
The code can be found [here](https://github.com/inexor-game/flex/blob/master/src/connector/index.js).
Using the `--debug` flag didn't give me more information on what's going wrong.
How could we debug and fix this?

**Comment by hegemonic** [comment]
I'm not able to reproduce this issue using the current version of the code and JSDoc.
