### ISSUE TITLE
ES6 arrow functions as class members - throws error

### ISSUE THREAD

**Issue by IamTheHttp** [jsdoc3/jsdoc#1310]
It seems that the parser hangs with "Unexpected token =" when a class contains an arrow function.

See example : 

```
class Test{

sample = () =>{
 console.log('hi');
}

}
```

**Comment by Ryalian** [comment]
I don't think that's how you define function in class syntax. In classes, you do:

class Test() {
  sample() {
    // code here
  }
}

**Comment by IamTheHttp** [comment]
Thanks for the reply.

I think this is related to this issue : https://github.com/jsdoc3/jsdoc/issues/1246

Which discusses class properties. 
The example i wrote assigns an anonymous function to a class property, so it seems related.

My IDE is fine with this code and babel has no problems either.

I tried using the babble plugin but hit the same problem.

**Comment by Ryalian** [comment]
As the comment in that issue states, that's not an valid syntax in ES6

**Comment by IamTheHttp** [comment]
I see, Well now I just feel silly I mis-read that. 
For future readers, this syntax appears to be a in proposal stages and is not part of the ES2015 or ES2016.
