### ISSUE TITLE
jsdoc fails when using new dynamic import syntax

### ISSUE THREAD

**Issue by ssylvia** [jsdoc3/jsdoc#1320]
https://github.com/tc39/proposal-dynamic-import

When using this syntax
```js
import('path/myModule').then((myModule) => {
  myModule();
});
```

jsdoc throw "ERROR: Unable to part path/../../index.js: Unexpected token import"

Is there a way to change the JavaScript parser or another way to add support for new features?

**Comment by hegemonic** [comment]
JSDoc supports ECMAScript 2017 features when our parser, [Espree](https://github.com/eslint/espree), gets support for them. When Espree supports this syntax, so will JSDoc.
