### ISSUE TITLE
symbolic anchors to links in source files

### ISSUE THREAD

**Issue by mjhm** [jsdoc3/jsdoc#1321]
Is there a way to insert symbolic anchors into the source file output, so that specific links to source code output aren't dependent on line numbers?  I'm thinking something along the lines of this source code "whatever.js" with the indicated line numbers:
```
...
61: 
62: /** @function */
63: var myFunction = function () {
64:   doWhatever();
65: };
...
```
then instead of using an explicit line number reference
```
{@LINK whatever.js.html#sunlight-1-line-63}
```
I could maybe use a symbolic reference instead. Something like:
```
{@LINK whatever.js.html#sunlight-1-line-myFunction}
```

**Comment by hegemonic** [comment]
Sorry, but this isn't currently possible, and I'm not sure how one would go about implementing this feature. I'm open to suggestions, though.
