### ISSUE TITLE
sharing documentation between static method and instance method

### ISSUE THREAD

**Issue by mbroadst** [jsdoc3/jsdoc#1324]
Hi, for legacy reason in our codebase we need to support the following type of code:

```
function MyClass() {
  /**
   * @param [options.test] test option
   * ....
   */
  this.someFunction = function(options) {};
}

/**
 * @param [options.test] test option
 * ....
 */
MyClass.someFunction = function(options) {};
```

where both functions support the exact same documentation. We haven't been able to find a way to "share" that documentation (tried using `@augments`,`@extends`) between the two, and have been left maintaining two identical pieces of documentation (which in our case is pretty huge because of all the options).

Is there a way to do this that we've missed?

**Comment by hegemonic** [comment]
Sorry, but there's currently no way to do this. I believe there's an issue open that would extend the `@inheritdoc` tag to allow you to inherit from arbitrary symbols.

My dopey solution would be to use a cross-reference rather than duplicating all of the docs:

```js
/** @class */
function MyClass() {
  /**
   * @param [options] Options object.
   * @param [options.test] Test option.
   */
  this.someFunction = function(options) {};
}

/**
 * @param [options] Options object. See {@link MyClass#someFunction} for a
 * list of supported properties.
 */
MyClass.someFunction = function(options) {};
```
