### ISSUE TITLE
ES5 class methods are not picked automatically if they are not at the root of the module

### ISSUE THREAD

**Issue by danielo515** [jsdoc3/jsdoc#1325]
Hello,

I'm in the middle of a crusade. I have a class and I want it to be part of a module. If the class is no the same file where the module is declared everything works as expected: the class appears as part of the module with all its members. This is the exact thing that I was expecting, excellent!

But, if the class is in another file and I want it to be part of the module then I have to decide between  duplication of information on the module page or losing the automatic pickup of the class methods. I don't think this is the intended behavior, because it is quite confusing and inconsistent. Why declaring a class inside a module works and declaring it as part of the module does not?

Let me ilustrate this with a simple example:

This works flawlessly if this is the only file with the `@module` tag:

```js
/**
 * @module  stuff
 */

/**
 * @function PersonsFactory
 * @param {Object} deps The class dependencty
 */
module.exports = function Factory(deps) {
    
    /**
     * @class
     * */
    const Person = function Person( name ) {
        this.name = name;
    };

    /**
     * Greets the user
     * @returns {void} Returns nothing
     */
    Person.prototype.greet = function greet() {
        console.log( 'I Use deps', deps );
    }

    return Person
}
```

However, none of this works as expected:

```js
/**
 * @memberof module:stuff
 * @function HumanFactory
 * @param {Object} deps The class dependencty
 */
module.exports = function Factory(deps) {
    
    /**
     * @class
     * @memberof module:stuff
     * */
    const Human = function Human( name ) {
        this.name = name;
    };

    /**
     * Borns
     * @returns {void} Returns nothing
     */
    Person.prototype.born = function greet() {
        console.log( 'I Use deps', deps );
    }

    return Human
}
```

```js
/**
 * @memberof module:stuff
 * @function HumanFactory
 * @param {Object} deps The class dependencty
 */
module.exports = function Factory(deps) {
    
    /**
     * @class module:stuff.Human
     * */
    const Human = function Human( name ) {
        this.name = name;
    };

    /**
     * Born as human
     * @returns {void} Returns nothing
     */
    Person.prototype.born = function greet() {
        console.log( 'I Use deps', deps );
    }

    return Human
}
```

If I create a second file with the `@module` tag at top, then the class will be properly documented, all the methods will appear as part of class and the class will be included on the module. The problem is that the main page of the module will have all it's members duplicated.

**Comment by hegemonic** [comment]
This example doesn't really make sense to me, because in both of the source files, you're assigning to `module.exports`. If `module:stuff` exports a single class, it seems like it has to export either `PersonsFactory` or `HumanFactory`, but not both.

Can you provide a better example?

**Comment by danielo515** [comment]
Sorry @hegemonic , could you please expand on why does this make no sense to you? The file exports a factory that returns classes. I want to document both the factory and the class itself and I want to group all of them under the same module. 
I think it is quite common to do `require('myModule')` to get the default export and also `require('myModule/person') to get a part of it, and both needs to be documented. 

Does it make more sense after this explanation?

**Comment by hegemonic** [comment]
From JSDoc's perspective, that means you have two modules, not one. You'll need to document your code as two separate modules.

Module 1:

```js
/** @module myModule */

/** Your docs here */
module.exports = function Factory(deps) {};
```

Module 2:

```js
/** @module myModule/person */

/** Your docs here */
module.exports = function Factory(deps) {};
```

**Comment by danielo515** [comment]
The example you gave will work if I have two different elements that belongs to the same module, fine. But what I have is a factory of classes. I want to document the class, but I also want to make clear that it should be called through the factory.
Splitting the class and the factory into two modules will force me to change the structure of my code, which I think it something that a documentation tool should not you force to do.

Regards
