### ISSUE TITLE
Consider adding @schema tag support to allow automatic JSON schema generation

### ISSUE THREAD

**Issue by john-doherty** [jsdoc3/jsdoc#1327]
Hello,

Would you consider adding @schema tag support to allow automatic generation of JSON Schemas?

I created a module to do this but it would be great if it was part of the core/spec [jsdoc-to-json-schema](https://github.com/john-doherty/jsdoc-to-json-schema).

Thanks.

**Comment by hegemonic** [comment]
JSDoc isn't really designed for generating JSON schemas, so I'd prefer not to add support for a `@schema` tag, particularly since JSDoc doesn't currently have dotted tag names like `@schema.name` and `@schema.description`.

(Your schema-generation tool looks cool, though!)
