### ISSUE TITLE
Feature Request: Exclusive @param Sets To Support Overridden Functons

### ISSUE THREAD

**Issue by CoryGH** [jsdoc3/jsdoc#1329]
An example to highlight this request:

    /**
     * Check if a Rectangle is within another Rectangle.
     * @param {Rectangle} rectangle_or_x
     * @return {boolean}
     */
    /**
     * Check if a coordinate is within a Rectangle.
     * @param {number} rectangle_or_x
     * @param {number} y
     * @param {number} [tolerance]
     * @return {boolean}
     */
    Contains(rectangle_or_x, y, tolerance) {
        if (rectangle_or_x instanceof Rectangle) { return ((rectangle_or_x.X >= this._x) && (rectangle_or_x.Y >= this._y) && (rectangle_or_x.Right <= this._right) && (rectangle_or_x.Bottom <= this._bottom)); }
        if ((tolerance === undefined) || (tolerance === null) || (!Rectangle._isNumeric(tolerance))) {
            if ((rectangle_or_x < this._x) || (y < this._y) || (rectangle_or_x > this._right) || (y > this._bottom)) { return (false); }
        } else if (((rectangle_or_x + tolerance) < this._x) || ((y + tolerance) < this._y) || ((rectangle_or_x - tolerance) > this._right) || ((y - tolerance) > this._bottom)) { return (false); }
        return (true);
    }

To allow something like the following, with different `@param` types and descriptions for each definition:

    Contains(Rectangle rectangle_or_x)
    Contains(Number rectangle_or_x, Number y[, Number tolerance])

Friendlier aliases for `@param` names would also be nice in this context, to allow generated documentation and things like intellisense within Webstorm to see:

    Contains(Rectangle rectangle)
    Contains(Number x, Number y[, Number tolerance])

**Comment by hegemonic** [comment]
If I understand your request correctly, you can already do what you're asking for. You just need to nestle the two JSDoc comments together, like so:

```js
/**
 * Check if a Rectangle is within another Rectangle.
 * @param {Rectangle} rectangle - The Rectangle.
 * @return {boolean}
 *//**
 * Check if a coordinate is within a Rectangle.
 * @param {number} x - The x coordinate.
 * @param {number} y - The y coordinate.
 * @param {number} [tolerance] - The tolerance.
 * @return {boolean}
 */
function Contains(rectangle_or_x, y, tolerance) {}
```

Note that you can also use different names for the parameters in your JSDoc comments, so you can document the parameter as either `rectangle` or `x` rather than `rectangle_or_x`.
