### ISSUE TITLE
--access private not working

### ISSUE THREAD

**Issue by 75lb** [jsdoc3/jsdoc#1331]
With this source code (example.js):

```js
/** @namespace */
var Documents = {
  /**
   * An ordinary newspaper.
   */
  Newspaper: 1,
  /**
   * My diary.
   * @private
   */
  Diary: 2
}
```

this command should include only `@private` members in the output but instead, the output is empty: 

```
$ jsdoc --access private example.js
```

**Comment by LeoAref** [comment]
+1

**Comment by LeoAref** [comment]
@hegemonic Could you check this issue :)

**Comment by hegemonic** [comment]
This happens because when you set `--access private`, the parent namespace is omitted from the documentation, which means there's nowhere to document the member. (Where would the docs for the member appear, after all?) This is the expected behavior.
