### ISSUE TITLE
@lends should process uncommented methods

### ISSUE THREAD

**Issue by cefn** [jsdoc3/jsdoc#1333]
I understand that https://github.com/jsdoc3/jsdoc/issues/1265 was interpreted as a documentation issue and resolved by https://github.com/jsdoc3/jsdoc3.github.com/commit/1c988699101aa4e0e67b1601f12b4bf7dad5abfc 

I gather from this that normative behaviour is considered to be to silently fail on uncommented methods.

I am raising this separate issue as a placeholder for the feature request to provide a configuration in which @lends renders methods even where they have no comments, and _not_ to silently fail. 

I consider this could be a basis for a practical source-documentation workflow. As discussed in https://github.com/jsdoc3/jsdoc/issues/1265 the default behaviour presents the risk of making source intended for jsdoc both error-prone (silent failure) and unnecessarily complex (pointless empty comments).

The below code represents a test case. To satisfy the feature I am requesting, both the ```present(...)``` and ```absent(...)``` methods below should appear in the jsdoc.

I can't find or intuit a rationale for ```@lends``` or jsdoc having silent failure as fixed and unconfigurable behaviour, even if it is a preferred default for some reason. I don't know what workflow it is expected to support. Having uncommented methods appear in the jsdoc would be an extremely effective way to ensure all methods bound by a ```@lends``` directive indeed DID have comments - as you could see them. 

If this feature is not considered worthy, it would be very useful to understand why, and what practical workflow can resolve the fundamental problems arising (e.g. relying on a warn-uncommented flag could be a legitimate alternative workflow to help an author satisfy the demands of jsdoc normative commenting). 

```
_ = require("lodash");

/** @class */
function Thing(){ }

Thing.prototype = _.create(Object.prototype, /** @lends Thing.prototype */ {
    /** Something you can do to a thing. */
    present:function(){
        console.log("This function is rendered in the jsdoc output for Thing");
    },
    absent:function(){
        console.log("This function is suppressed in the jsdoc output for Thing");
    },
})
```

**Comment by ProLoser** [comment]
Currently no undocumented methods, variables or classes are documented. Why should an exception be made to consistent behavior for just `@lends` instead of more complete (and explicit) documentation?

**Comment by hegemonic** [comment]
I agree with @ProLoser. I don't think it makes sense for JSDoc to show undocumented methods just because the `@lends` tag was involved with them somehow.

If you run JSDoc with the `-X` option, you'll see that `Thing#absent` does show up in the parse results; however, it also has the `undocumented` property set to `true`, which means that JSDoc's default template (and every third-party template that I'm aware of) ignores it. If you really wanted to, you could create your own template that doesn't discard doclets with `undocumented` set to `true`.

**Comment by ProLoser** [comment]
Maybe make this theme behavior of discarding undocumented stuff more easily configurable? Although this means you're locked in across the codebase. 

Perhaps we could introduce a new tag intended to explicitly enable this behavior that you would then use alongside @lends or anything else. 

For example @autodoc coupled be used to auto generate document subs for any object or class?

**Comment by cefn** [comment]
I feel the right answer provides a practical workflow. 

Example scenario; you have finished structuring, naming, authoring, and testing code and want to document objects which are intended as an API accurately now they are stable, so that others can use them. This seems like the most mainstream possible scenario.

Problem: The current situation is a challenge which requires human precision and attention to ensure there are no omissions in the source code. Both are in short supply. Computers are good at precision and attention putting pressure on the tools to assist in some way. 

JSDoc already visits all the candidate structures which might need documentation. Paging through source code to find elements which JSDoc would parse into API documentation is surely a task better done by JSDoc than by eye. Diving into creating your own template logic to facilitate this core workflow is a very high bar.

> Maybe make this theme behavior of discarding undocumented stuff more easily configurable? Although this means you're locked in across the codebase.

Definitely. As an outsider to the project, the core normative expectation (everything must be documented to appear in the API or else) seems optional, introducing the problem in the first place. Putting this policy in the control of the user would be a very positive step and was an option I was surprised not to see.

If a global flag could be used to show undocumented methods, jsdoc can be used to surface objects and methods not having comments. As a by-product it would provide a navigable API for code still under development, also helping with documentation. Once you've finished exhaustively documenting, you may well want to hide (deliberately) undocumented methods again.

> For example @AutoDoc [could] be used to auto generate document subs for any object or class?

If this is on a per-object basis, having to manually hunt around for places where @AutoDoc was missing is very like the original problem, so some way of globally asserting this behaviour for a source file or project seems pretty important.
