### ISSUE TITLE
Does jsdoc support typescript class with property?

### ISSUE THREAD

**Issue by miaolq** [jsdoc3/jsdoc#1334]
```
/** Class representing a point. */
class Point {
    x: String;
}
```
when i use jsdoc to document code above,it cause error  "Unexpected token :"
How can i use jsdoc with typescript?

**Comment by miaolq** [comment]
I searched a lot ,but I didn't find an anwser. hope for reply

**Comment by hegemonic** [comment]
Sorry, but JSDoc does not support TypeScript.
