### ISSUE TITLE
Setting @param default value to `{}` does not compile correctly

### ISSUE THREAD

**Issue by calebmosher** [jsdoc3/jsdoc#1335]
With a parameter definition such as:

```js
/**
 * @param [options={}] {Object} Description of parameter
 */
```

Expected output:

|Name|Type|Attributes|Default|Description|
|:--|:--|:--|:--|:--|
|options|Object|\<optional>|{}|Description of parameter|

Actual output:

|Name|Type|Attributes|Default|Description|
|:--|:--|:--|:--|:--|
|options=| |\<optional>| |{Object} Description of parameter|

---

Note: This DOES work if the definition is written as such:

```js
/**
 * @param {Object} [options={}] Description of parameter
 */
```

However, the first example is valid doc style, and our team's preferred method of documentation (no dash needed for clarity).

---

This is with:

```shell
$ jsdoc -v
JSDoc 3.4.3 (Thu, 10 Nov 2016 00:25:10 GMT)
```

**Comment by hegemonic** [comment]
Sorry, but your first example is not valid JSDoc, per the [documentation for the `@param` tag](http://usejsdoc.org/tags-param.html). If you specify a type, it must always come before the parameter name.
