### ISSUE TITLE
Folder name start with _ automatically ignored

### ISSUE THREAD

**Issue by hellomaya** [jsdoc3/jsdoc#1337]
Hi,

I am using jsdoc 3.4.3, with the -r parameter in command line, I found when the folder name start with ```_```, then jsdoc will ignore it.

Inside conf.json I created, I have exclude pattern:

```
"excludePattern": "(^|\\/|\\\\)_"
```

It will ignore ```\\, /, _```, so I removed ```_```, not working, jsdoc will ignore everything.

So I am not sure it's a bug or I used wrong pattern, hope this is a correct place to ask about it.

Thanks.

**Comment by hegemonic** [comment]
Yes, this is intentional. If you don't want this to happen, set `excludePattern` to an empty string.
