### ISSUE TITLE
Is there anyway to ignore annotations in ES.Next

### ISSUE THREAD

**Issue by hellomaya** [jsdoc3/jsdoc#1338]
Hi,

I found jsdoc will warning and not compile the file with javascript ```annotations``` which is supported by ES.Next, I also read similar issue here, knowing it's probably the javascript parser used by jsdoc limitation.

But I would ask if there is anyway to ignore those annotations? So jsdoc can continue to work on those files.

**Comment by hegemonic** [comment]
You have a couple of options:

+ Use the [jsdoc-babel plugin](https://github.com/ctumolosus/jsdoc-babel) to preprocess the files.
+ [Write your own plugin](http://usejsdoc.org/about-plugins.html) to preprocess the files (for example, by applying a regexp).
