### ISSUE TITLE
File scanning only works to a depth of 10

### ISSUE THREAD

**Issue by blindspeed90** [jsdoc3/jsdoc#1340]
We have a deep file structure, and some files weren't being processed, without any indication that the recursive scan was halted.  I'm not sure why there has to be a limit at all, and shouldn't even be something you have to configure in the conf.json.  The cli.js is what mattered to me, but resolver.js had the same limit.

cli.js:
cli.scanFiles = function() {
        env.sourceFiles = app.jsdoc.scanner.scan(env.opts._, (env.opts.recurse ? 10 : undefined),

resolver.js:
exports.load = function(filepath) {
    var files = fs.ls(filepath, env.opts.recurse ? 10 : undefined);

**Comment by hegemonic** [comment]
The limit is there to prevent infinite recursion.

Contrary to what you said, I think the correct solution is to make this value configurable in `conf.json`, rather than hard-coding the value `10`. A good name for this option would be `recurseDepth`.

**Comment by hegemonic** [comment]
Fixed on master. The fix will be included in JSDoc 3.5.0.
