### ISSUE TITLE
Why you are not using Glob?

### ISSUE THREAD

**Issue by EmpireWorld** [jsdoc3/jsdoc#1344]
As i see your source code you are using a walker that can walk into directories in 10 depth so why?
If you use glob there is no limitations.
Also [Globby](https://github.com/sindresorhus/globby) has good support for matching directories with minimatch patterns.

**Comment by hegemonic** [comment]
We're not using glob for a couple of reasons:

+ JSDoc has been around for longer than most glob modules. (JSDoc originally ran on Mozilla Rhino, not Node.js, and it predates most of the Node.js ecosystem.)
+ We allow users to include and exclude files and directories using regular expressions, which isn't compatible with glob libraries.

**Comment by EmpireWorld** [comment]
But the node glob libraries support most of the regular expressions.

[node-glob](https://github.com/isaacs/node-glob)

And multiple patterns:

[globby](https://github.com/sindresorhus/globby)
