### ISSUE TITLE
Option to print error stack

### ISSUE THREAD

**Issue by 75lb** [jsdoc3/jsdoc#1345]
hi! Say my code has a syntax error:

```js
/**
 * Documenting some broken code
 */
function badJavascriptSyntax () {
  const a = { one: 1, two: 2 }
  const b = { ..a } // should be three fullstops
}
```

Running jsdoc highlights the error but not the line number where i can find the issue.. 
```
$ jsdoc broken-javascript.js
ERROR: Unable to parse /Users/lloydb/broken-javascript.js: Unexpected token .
```

Is there a way to print the full parse error stack?

**Comment by iPherian** [comment]
+1

As a workaround, you can use a quick little node.js script I made. It uses espree which I believe is the linter jsdoc uses.

[espree-check.txt](https://github.com/jsdoc3/jsdoc/files/1051444/espree-check.txt)

To install espree:

`npm i espree --save`

Then call it like:

`node.exe espree-check.txt --file some.js`

It should print the same error jsdoc gives, but at the bottom of the (long) trace you will see "lineNumber: x, column: y".

Saved me a lot of time.

**Comment by hegemonic** [comment]
On master, JSDoc now prints the line number and column when there's a syntax error, which should make it easier to track down the problem. Printing the stack trace wouldn't be helpful in most cases.

**Comment by 75lb** [comment]
true, the fix has landed on `master`.. Once he's finished the new release (3.5.0) i'll pull it into jsdoc2md.
