### ISSUE TITLE
Please update the README for installation with npm!

### ISSUE THREAD

**Issue by bobhairgrove** [jsdoc3/jsdoc#1346]
On Ubuntu 16.04, I tried installing jsdoc, but the system didn't find the executable and wanted me to install `jsdoc-toolkit` instead. Then I found out what was wrong, that I needed the `-g` option for `npm`.

In the README file, it says:
```To install the latest version available on NPM:
    npm install jsdoc
```

This should be:
```To install the latest version available on NPM:
    npm install -g jsdoc
```

Took me a long time to figure this out. Also, it is necessary to run this as root if installing globally; that should be mentioned as well.

**Comment by ProLoser** [comment]
This is not mandatory. There is an assumption that the user has a degree of knowledge of npm executables.

**Comment by bobhairgrove** [comment]
Considering that jsdoc is probably one of the most compelling reasons to even use nodejs, npm, etc., there are probably lots of people like me who want to use it but never worked with nodejs before. You could help to ease the learning curve.

**Comment by camden** [comment]
@bobhairgrove Regarding the sudo issue, check out this link https://docs.npmjs.com/getting-started/fixing-npm-permissions

You shouldn't need root permissions to run npm.

**Comment by hegemonic** [comment]
Fixed by ec7ac85ecbb734a5c125a9ab16d6c9e0621c9106.
