### ISSUE TITLE
flowtype modules are ignored

### ISSUE THREAD

**Issue by phtrivier** [jsdoc3/jsdoc#1348]
This is probably not an issue with j`sdoc` itself, but I'm not sure where to ask. 
I've been using `jsdoc` on a codebase for a while, and I'm migrating the code to use `flow`. 

I'm using a configuration close to this : 

```
{
    "plugins": ["node_modules/jsdoc-babel"],
    "babel": {
        "presets": ["react"],
        "plugins": ["transform-react-jsx", "transform-flow-strip-types"]
    }
}
```

The `transform-flow-stip-types` plugin makes it possible for jsdoc to parse the files, however, all modules that include "// @ flow" are ignored (no documentation is generated for them.)

How would I go about debugging this ? Can I run jsdoc in `verbose` mode or something ? Are there "intermediate" files generated during the build ?

**Comment by phtrivier** [comment]
In particular, if I write a module like this: 

```
// @flow
/**
 * Bug example.
 * @module
 */

/**
 * A Type definition
 *
 * @typedef {object} module:model/foo.Fo
 * @property {number} bar - a property
 */
export type Foo = {
  bar: number
};
```
Nothing is generated. 

If I add a function afterwards:

```
// @flow
/**
 * Bug example.
 * @module
 */

/**
 * A Type definition
 *
 * @typedef {object} module:model/foo.Fo
 * @property {number} bar - a property
 */
export type Foo = {
  bar: number
};

/**
 * One.
 * @param {number} x - a number
 * @return {number} - always 1.
 */
export function one (x: number) : number {
  return 1;
}
```

The doc for the typedef is generated, but not the doc for the functions.

What am I missing ?

**Comment by hegemonic** [comment]
There are a couple of ways you can debug this:

+ JSDoc allows you to write [event-handler plugins](http://usejsdoc.org/about-plugins.html#event-handlers); the `beforeParse` event gives you the source code for the file that JSDoc is about to parse. You could write a `beforeParse` plugin that dumps the source code for the current file, so you can see how the Babel plugins have changed your original source code.
+ JSDoc provides an `-X` option that dumps the parse results to the console. This allows you to see how JSDoc interpreted your source code.

I suspect the first option would be more useful. My hunch is that the `transform-flow-strip-types` plugin is dropping comments, or putting them in an obviously wrong location, and that should be easy to diagnose by looking at the preprocessed source code.
