### ISSUE TITLE
Integrating GitBook with JSDoc

### ISSUE THREAD

**Issue by KevinAst** [jsdoc3/jsdoc#1353]
Your package is very much appreciated!  

I have always been a proponent of documenting my API through JSDoc!  I recently was able to integrate JSDoc with GitBook, to promote a very polished set of docs (GitBook for the Guide and JSDoc for the API).  **Here is the end result** (_notice the API is machine generated via JSDoc_): https://astx-redux-util.js.org/

I have written a comprehensive article that describes how I accomplished this: [Integrating GitBook with JSDoc to Document Your Open Source Project](https://medium.com/@kevinast/integrate-gitbook-jsdoc-974be8df6fb3)

I wanted to try to get the word out, and I suspect this is something that your users may be interested in.  If you feel this article has value, **_feel free to promote it in your site_** (either you readme or your wiki).

**Thanks again for the great package!**

**Comment by hegemonic** [comment]
Many thanks for the feedback, @KevinAst! I'm glad JSDoc has been useful to you.

Thanks also for the links—I added a link to your Medium article to JSDoc's `README`.

**Comment by KevinAst** [comment]
Thanks @hegemonic for the link ... much appreciated :-)
