### ISSUE TITLE
ES2017 Trailing comma in function

### ISSUE THREAD

**Issue by nlepage** [jsdoc3/jsdoc#1356]
Would it be possible to allow trailing commas in function declarations and function calls ?

These are allowed as of ES2017, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas

It is supported by babel and eslint, and it would be nice to have it in jsdoc as well.

Anyway thanks for the great work !

**Comment by hegemonic** [comment]
We now support this on GitHub master. The change will be released in JSDoc 3.5.0.
