### ISSUE TITLE
[QUESTION] How to make jsdoc work with es6?

### ISSUE THREAD

**Issue by johhansantana** [jsdoc3/jsdoc#1357]
I'm having trouble using jsdoc I get `Unexpected token =`

I'm using https://github.com/zeit/next.js/ as my framework.

**Comment by Fl4m3Ph03n1x** [comment]
Can you investigate the line causing the error? 
The way I do it is by removing comments until I find the one causing the problem. I recommend the same approach.

**Comment by hegemonic** [comment]
On master, JSDoc now logs the line and column that caused an error when it's not able to parse a JavaScript file. That should help you track down the error.
