### ISSUE TITLE
Make a Difference between @abstract and @virtual

### ISSUE THREAD

**Issue by kappe-c** [jsdoc3/jsdoc#1358]
I'm referring to [http://usejsdoc.org/tags-abstract.html](url) here.
While currently both the tag `@abstract` and `@virtual` exist but are treated as synonyms, I propose to let `@abstract` signal *pure* virtual methods as opposed to "ordinary" virtual methods signalled by `@virtual`. The difference being that the former *must* while the latter *may* be overriden. 
I think this is a common (and important) differentiation made in OOP and worth a clear documentation. Compare e.g. `virtual …` and `virtual … = 0` methods in C++.

**Comment by LFP6** [comment]
I'd like to second this request. Virtual and abstract definitely have distinct meanings.

**Comment by hegemonic** [comment]
Sorry, but we can't change this without breaking tons of existing projects that use JSDoc. If you want `@abstract` and `@virtual` to mean different things, you'll need to [write a plugin that redefines one or both tags](http://usejsdoc.org/about-plugins.html#tag-definitions), then modify your template accordingly.
