### ISSUE TITLE
getting initial indentation of start of comment

### ISSUE THREAD

**Issue by AlmirKadric** [jsdoc3/jsdoc#1362]
Currently when a comment is parsed from a JS file and put inside the comment property of a doclet, the initial indentation (indentation of the starting `/**`) is stripped away or ignored. Currently we have a use for that indent.

To give a bit of background, we have created a jsdoc i18n tool and workflow which allows our users to translate their documentation into many different languages. A part of that workflow revolves around the translation of the comment. However when rendering the comment  we end up having all lines except the first indented. Whilst we could just strip these away without know the first indentation, it would remove any intended indentation the user may have. To get a more accurate indentation removal algorithm it would be ideal to have the indentation of the first line.

Anyways before jumping to any conclusions on our end we thought it best to check with the jsdoc team and see what kind of feedback we get. Our linked issue can be found here:
https://github.com/AlmirKadric-Published/jsdoc-i18n/issues/7

**Comment by AlmirKadric** [comment]
Alternatively, can you confirm how many properties from a doclet would require translation or rather so contain some form of description. One thing I'm considering is switching back to translating the parsed object rather than the comment itself and parsing it again.
 - Description
 - Params Description
 - What else?

**Comment by AlmirKadric** [comment]
After looking into what tags would need to be translated, we decided to stay with re-parsing comments as it reduces the complexity of the tool UI as well as lowers potential maintenance required in future.

**Comment by hegemonic** [comment]
On GitHub master, we now add a `columnno` attribute to `jsdocCommentFound` events, which tells you which column the JSDoc comment starts on (i.e., how far it was indented). You can [create an event-handler plugin](http://usejsdoc.org/about-plugins.html#event-handlers) that uses this information. This change will be included in JSDoc 3.5.0.

Hope that's helpful!

**Comment by AlmirKadric** [comment]
@hegemonic 
Thanks!!! will take a look
