### ISSUE TITLE
Question regarding some re-organisation

### ISSUE THREAD

**Issue by AlmirKadric** [jsdoc3/jsdoc#1363]
This is a more general question rather than an issue itself. As I mentioned in a previous issue, I have developed a translation tool and workflow for jsdoc. However to get things to work, and extend the jsdoc CLI quite a fair bit of hackery was involved. Personally I would like to try and clean up some of those hack and potentially have jsdoc support some form of CLI extensibility on an official level.

The question being, is this something jsdoc would be interested in? If I spend some time refactoring minor pieces here and there to get this cleaned up would you be happy about the change? Would you mind maintaining it to ensure future iterations aren't broken?

Linked issue can be found here:
https://github.com/AlmirKadric-Published/jsdoc-i18n/issues/8

**Comment by hegemonic** [comment]
Sorry, but after looking at the changes in [AlmirKadric-Published/jsdoc-i18n](https://github.com/AlmirKadric-Published/jsdoc-i18n), I don't think we can merge those back into JSDoc.

**Comment by AlmirKadric** [comment]
@hegemonic i wasn't asking for those exact changes to be put in.
Rather so to spend some time with me to think about potential minor architecture changes to allow something like what I am doing in the above PR to be simpler to do without the need for such hackery. If this is an interest I don't mind making an initial proposal as to what could be done.
