### ISSUE TITLE
customization of the template

### ISSUE THREAD

**Issue by zizizi17** [jsdoc3/jsdoc#1365]
Hello everyone.
I need to customize the template of the jsDoc so that i could have the documentation, gainded by the comments with navigation like in my project(project tree), not like in the default template(Classes, Modules, Types), but i did not find any information about how to implement it.

**Comment by hegemonic** [comment]
Sorry, but there's currently no documentation on how to modify JSDoc's default template. You can look at some of the third-party templates listed in our `README` to see how they've implemented their own changes, and perhaps one of these third-party templates will have the feature you're looking for.
