### ISSUE TITLE
A property can't be nullable and accept multiple data types

### ISSUE THREAD

**Issue by Native-Coder** [jsdoc3/jsdoc#1366]
For instance, I have a nullable property that can be a String or a Number, but

`@property {?String|Number}`

Doesn't work, and neither does

`@property {?String|?Number}`

The documentation produces `<optional>` instead of `<optional><nullable>` in both cases

**Comment by hegemonic** [comment]
This works if you enclose the type union in parentheses and put the nullable operator outside of the parentheses:

```js
/**
 * Foo function.
 * @param {?(string|number)} bar - The bar parameter.
 */
function foo(bar) {}
```
