### ISSUE TITLE
Update to latest version of espree (3.4.3)

### ISSUE THREAD

**Issue by kbmmdwork** [jsdoc3/jsdoc#1367]
I'm running into a problem with Lab where the code coverage depends on a newer version of espree than jsdoc (although they're currently allowing 3.x.x).  JSDoc is fine with 3.1.7 but Lab fails when it uses 3.1.7, but it works fine if our own app depends on espree directly and thereby forces Lab to use a newer version.  Essentially, JSDoc and Lab aren't playing nicely together.  I've added an issue to Lab's backlog as well, but essentially, either project could resolve this issue.

**Comment by kbmmdwork** [comment]
Incidentally, I started trying to fix this by pulling down jsdoc locally and making the dependency change but two unit tests failed when I did this and I'm not sure how to "fix" the unit tests appropriately:
- 1) should define all of the node types that are defined by Espree
- 2) should define all of the node types that are defined by Espree

1278 tests, 3246 assertions, 2 failures

**Comment by hegemonic** [comment]
JSDoc now uses [Babylon](https://github.com/babel/babylon) as its parser on GitHub master. This change will be included in JSDoc 3.5.0.
