### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by reyraa** [jsdoc3/jsdoc#1368]
Hi everyone
I'm running 
`jsdoc -c conf.json -r`
using npm v4.6.1 and node v6.10.0 in osx. in my config I have:
```
{
    "tags": {
        "allowUnknownTags": true,
        "dictionaries": ["jsdoc","closure"]
    },
    "source": {
        "include": ["src/app"],
        "exclude": [
            "node_modules",
            "src/test"
        ],
        "includePattern": ".+\\.js(doc)?$",
        "excludePattern": "(^|\\/|\\\\)_"
    },
    "plugins": [],
    "templates": {
        "cleverLinks": false,
        "monospaceLinks": false
    }
}
```
and node runs out of memory:

> FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

I've tried:
`node --max_old_space_size=4096 /usr//local/lib/node_modules/jsdoc.js -c conf.json -r`
but 4G wasn't enough either.
Is this a known issue? How can I fix it?
thank you

**Comment by irajkovic** [comment]
We experienced similar issue and after some debugging, I pinpointed the problem to be somewhere within attachModuleSymbols() function  in publish.js. When there is allot of files with the same @module tag, for each object in the module, this function adds list of all other modules within the same module, and each of this is object with it's own module property containing same list and so on. There is some recursive copying, that, after certain amount of files start to be exponentially more resource intensive and eats up all the heap memory.

For now, we just removed @module tag and everything looks good, but this seem to be a bug with jsdoc.

**Comment by hegemonic** [comment]
I can't investigate this bug without having a way to reproduce it. Please provide a link to a repo that causes this bug, and I'll reopen this issue.

**Comment by tHBp** [comment]
Definitely a bug with JSDoc.

Removing **@module** tag didn't work for me. Tried allocating memory till 9 GB, still fails.

**Comment by Gkolman** [comment]
For me the issue was my node_modules. Because I was using the -r extension it was generating docs for all of my node modules and it just may have been to large of a load. Probably still a bug though..
