### ISSUE TITLE
Duplicate Class Documentation When Splitting Class and Constructor Docs

### ISSUE THREAD

**Issue by jthomerson** [jsdoc3/jsdoc#1371]
I want to document my class separately from my constructor, and I'm using `class.extend` (ala John Resig) to make my classes. I have tried a bunch of different combinations of tags, but no matter what I do, when I document the class separately from the constructor, I get duplicated class documentation.

For example, this class would end up being duplicated in the documentation: once with a no-args constructor, and once with the constructor that takes `@arg a`.

Is there a way to separate the class documentation from the constructor documentation?

```js
'use strict';

var Class = require('class.extend');

/**
 * This is the first paragraph of class documentation.
 *
 * This is the second paragraph of class documentation.
 *
 * @class SomeFooClass
 */
module.exports = Class.extend(/** @lends SomeFooClass.prototype */{

   /**
    * This is my constructor documentation.
    *
    * @constructs
    * @arg a {string} apple
    */
   init: function(a) {
   },

   /**
    * The foo function is really cool.
    *
    * @arg a {string} apple
    * @arg b {string} banana
    * @arg c {string} cherry
    * @returns {number} some foo number
    */
   foo: function(a, b, c) {
      return 42;
   },

});
```

**Comment by hegemonic** [comment]
The solution is to move the class documentation to the constructor, preceded by a `@classdesc` tag:

```js
'use strict';

var Class = require('class.extend');

module.exports = Class.extend(/** @lends SomeFooClass.prototype */{

   /**
    * This is my constructor documentation.
    *
    * @classdesc This is the first paragraph of class documentation.
    *
    * This is the second paragraph of class documentation.
    *
    * @constructs
    * @arg a {string} apple
    */
   init: function(a) {
   },

   /**
    * The foo function is really cool.
    *
    * @arg a {string} apple
    * @arg b {string} banana
    * @arg c {string} cherry
    * @returns {number} some foo number
    */
   foo: function(a, b, c) {
      return 42;
   }
});
```

I filed jsdoc3/jsdoc3.github.com#163 to add this to the documentation.

**Comment by jthomerson** [comment]
@hegemonic thanks for the info. That's helpful. That said, it would sure be nice if the pattern shown in my initial post were supported ... it makes more sense to open a file and see the class documentation right at the top where the class is defined, and separate from the constructor. Would it be possible to support that?
