### ISSUE TITLE
allowUnknownTags - adding array of custom tags

### ISSUE THREAD

**Issue by ozasheetal** [jsdoc3/jsdoc#1374]
I have the latest of JsDoc (3.4.3), and as per the [documentation](http://usejsdoc.org/about-configuring-jsdoc.html) of JsDoc, I added array of unknown tags, but got slapped with error of unknow tag

**The @foo: tag is not a known tag.**
`"allowUnknownTags": [ "foo", "usage", "test" ]`

Am I missing something ?

**Comment by hegemonic** [comment]
This feature works for me. Make sure you're running JSDoc with the `-c` option to specify the location of your config file.

**Comment by skurgansky-sugarcrm** [comment]
why does jsdoc 4.0.2 doesn't recognise custom tags whatever i do?

i have a comment in file 

```
/**
 * @sampleid check-in-action
 * @samplename Check-In Action
 */
```

and my jsdoc config has 
```
tags: {
        allowUnknownTags: ['sampleid', 'samplename', 'sampledesc', 'samplefeature'],  <- tried true here as well
        dictionaries: ['jsdoc', 'closure']
    },
```
