### ISSUE TITLE
What's the current take on dots before angle brackets?

### ISSUE THREAD

**Issue by dandv** [jsdoc3/jsdoc#1375]
Is it preferable to write `Promise<Number>` or `Promise.<Number>`?

When it comes to Arrays, I see `Array.<>` on the [@type help page](http://usejsdoc.org/tags-type.html), but `Array<>` on [@interface](http://usejsdoc.org/tags-interface.html) and [@implements](http://usejsdoc.org/tags-implements.html).

There's even a [debate on SO](https://stackoverflow.com/questions/14611995/how-to-specify-an-array-of-objects-as-a-parameter-or-return-value-in-jsdoc?rq=1#comment56331069_14854851) about this! :)

**Comment by hegemonic** [comment]
`Promise<number>` is preferable, but either one is fine. I filed jsdoc3/jsdoc3.github.com#156 to clean up the docs.
