### ISSUE TITLE
@callback and @module integration

### ISSUE THREAD

**Issue by Fl4m3Ph03n1x** [jsdoc3/jsdoc#1378]
I have the same problem as issue: https://github.com/jsdoc3/jsdoc/issues/356

This issues describes that @callback doesn't work as expecetd with @module. This is intended behavior and someone suggested a plugin to solve the problem. 

However, it seems the issue was closed, but the plugin never got fixed. Any news?

**Comment by hegemonic** [comment]
As stated in #356, issue #101 is still open to fix the plugin.
