### ISSUE TITLE
Is there a JSDoc intermediate format?

### ISSUE THREAD

**Issue by DrMiaow** [jsdoc3/jsdoc#1379]
I'm wondering if there is an existing intermediate format which could be emitted by other documentation projects such as 'typedoc' that could be read into JSDoc to leverage the JSDoc ecosystem of templates and plugins?

eg:
`file : { node: { line: 123, comments: {..}, context{..} }, ...  }`

**Comment by davidosomething** [comment]
check out https://github.com/jsdoc2md
and there are other projects that parse jsdoc to json too (eg. https://github.com/documentationjs/documentation/blob/master/docs/NODE_API.md among others) -- i personally used jsdoc2md on my site for a while.

**Comment by hegemonic** [comment]
Sorry, there's no intermediate format like that. The closest thing is the JSON output you get when you run `jsdoc -X`, and JSDoc isn't capable of reading that JSON, only generating it.
