### ISSUE TITLE
Release 3.5.0 prevents usage of .jsdocrc configuration files

### ISSUE THREAD

**Issue by mjfisheruk** [jsdoc3/jsdoc#1391]
This might well be a deliberate design decision, but I just wanted to draw your attention to the breaking change introduced in 3.5.0 around configuration file handling. Our repositories were using files named .jsdocrc to store JSON configuration for JSDoc; this worked for 3.4.x, but [this commit](https://github.com/jsdoc3/jsdoc/commit/2aad297cdc735f6ca7726e73218cda65f5cac1d5) released in 3.5.0 only allows for files with a .js or .json extension to be accepted.

You explicitly specify those extensions in the documentation now, but previously there seems to have been a reasonably widespread (if informal) convention for using .jsdocrc file. A [quick search to confirm](https://www.google.co.uk/search?q=jsdocrc) suggests there are around seven hundred mentions found, so it's likely to have a reasonable impact.

We're about to start updating our JSDoc configuration files to have .json extensions anyway, but I just wanted to make sure you were aware of this as a side effect. Regardless, thanks for your work on a very useful project!

**Comment by hegemonic** [comment]
Thanks for the heads up. I'll update JSDoc to assume that the config file is in JSON format if there's no file extension (which is the behavior we should have used in the first place).

Because there's an easy workaround for this issue, I'll wait for some more bugs to trickle in before I release a new version of JSDoc with the fix.

**Comment by mjfisheruk** [comment]
Cheers @hegemonic. We had jsdoc pinned to "^3.4.0", so a bunch of our CI pipelines that generate documentation have gone a little bit red on a few of our core libraries; it's something we need to workaround immediately regardless, but we figured it might save someone else some headaches further down the line!

**Comment by hegemonic** [comment]
Fixed on master and releases/3.5. The fix will be included in JSDoc 3.5.1, which I'll probably release later today.

**Comment by Reinmar** [comment]
Thanks for quick reaction!

**Comment by mjfisheruk** [comment]
Superbly quick turn around - thank you, @hegemonic !
