### ISSUE TITLE
3.5.0 requires node >= 5.10.0

### ISSUE THREAD

**Issue by jaredmcateer** [jsdoc3/jsdoc#1393]
As of version 3.5.0, jsdoc uses `Buffer.alloc` which was introduced in Node v5.10.0 but the package.json currently specifies >= v4.2.0

This results in an error when trying to run jsdoc on a system running node < v5.10.0

```
.../node_modules/jsdoc/lib/jsdoc/fs.js:103
    var buffer = Buffer.alloc(BUF_LENGTH);
                        ^

TypeError: Buffer.alloc is not a function
```

**Comment by hegemonic** [comment]
Whoops, sorry about that! Fixed on master and releases/3.5. The fix will be included in JSDoc 3.5.1.
