### ISSUE TITLE
`export default` a class will appear a exports class

### ISSUE THREAD

**Issue by initialdmg** [jsdoc3/jsdoc#1402]
### Input code

```js
/**
 * a circle
 */
export default class Circle {
    constructor(radius) {
        this.radius = radius;
    };
    /** 
     * calculating area
     * @returns {number}
     */
    area() {
        return Math.pow(this.radius, 2) * Math.PI;
    };
}
```

### JSDoc configuration

default

### JSDoc debug output

nothing error output

### Expected behavior

produce document like using `export class`, `export default className`(after class defined).

![20170713152247](https://user-images.githubusercontent.com/22365060/28155737-8842c776-67e2-11e7-8eba-2a4d1660aed6.png)

### Current behavior

when using `export default class foo`, jsdoc produces a class `export` and global methods.

![20170713152517](https://user-images.githubusercontent.com/22365060/28155478-84fe131e-67e1-11e7-8daf-9c1293621889.png)
![20170713152531](https://user-images.githubusercontent.com/22365060/28155485-8b54a282-67e1-11e7-99b3-691c51ef8fc7.png)

`exports` class disappeared after using a `@exports className` tag, but only methods were generated.

![20170713152444](https://user-images.githubusercontent.com/22365060/28155949-44cb3f40-67e3-11e7-885a-d0c6ba21caf3.png)

### Your environment

| Software         | Version
| ---------------- | -------
| JSDoc            | 3.5.2
| Node.js          | 8.1.2
| npm              | 5.0.1
| Operating system | Windows 7

**Comment by hegemonic** [comment]
You also need a `@module` tag so JSDoc understands that it's parsing a module:

```js
/** @module circle */

/**
 * a circle
 */
export default class Circle {
    constructor(radius) {
        this.radius = radius;
    };
    /**
     * calculating area
     * @returns {number}
     */
    area() {
        return Math.pow(this.radius, 2) * Math.PI;
    };
}
```
