### ISSUE TITLE
[Question] Allow optional properties in typedefs

### ISSUE THREAD

**Issue by 3stacks** [jsdoc3/jsdoc#1407]
Hey there, 

Are there currently any plans in this project to support optional properties? e.g.

```
/**
 * @typedef {Object} Something
 * @property {string} someProperty - required
 * @property {string} [anotherProperty] - optional
 */
```

Had a search through the issues and couldn't find this specifically, so apologies if it's a repeat.

**Comment by hegemonic** [comment]
They're already supported! Your example generates this output with the default template:

![image](https://user-images.githubusercontent.com/1522391/28222213-469cef1a-687b-11e7-9ff9-066b4a6e196b.png)

**Comment by 3stacks** [comment]
Oh great! Thank you for your reply. Is this in the docs? I had a hard time finding it, personally, so if it is, maybe it's worth emphasising more.

Cheers.

**Comment by hegemonic** [comment]
Good suggestion! I filed jsdoc3/jsdoc3.github.com#172 to document this feature.
