### ISSUE TITLE
ES6 subclass factory mixin documentation adds "undefined" prefix to names

### ISSUE THREAD

**Issue by msqr** [jsdoc3/jsdoc#1409]
I am trying to document a _subclass factory_ style ES6 mixin, but am finding that the word `undefined` is inserted before method names, when I don't expect that to appear.

I have posted a [demonstration project](https://github.com/msqr/jsdoc-es6-mixin-test) that shows the issue.

I am not sure if I am simply missing the right tags, have misplaced the tags, or something else. I have tried many different variations, but have not been able to get "undefined" to not appear.

### Input code

```js
/**
 * A mixin.
 * 
 * @param {*} superclass the class to mix onto 
 * @mixin
 * @property {string} myProp a string property
 */
const TestMixin = (superclass) => class extends superclass {

    get myProp() {
        return this._myProp;
    }

    set myProp(val) {
        this._myProp = val;
    }

    /**
     * Get 2nd property.
     * @returns {string} the 2nd property
     */
    get myProp2() {
        return this._myProp2;
    }

    /**
     * Set 2nd property.
     * @param {string} val the value to set
     */
    set myProp2(val) {
        this._myProp2 = val;
    }

    /**
     * Do something.
     * 
     * @param {boolean} param important parameter
     * @returns {string} the base URL to SolarUser
     * @memberof TestMixin#
     */
    doSomething(param) {
        console.log('param =', param);
        return 'thanks';
    }

}
```

### JSDoc debug output

```
DEBUG: JSDoc 3.5.3 (Fri, 14 Jul 2017 02:48:27 GMT)
DEBUG: Environment info: {"env":{"conf":{"plugins":[],"recurseDepth":10,"source":{"includePattern":".+\\.js(doc|x)?$","excludePattern":"(^|\\/|\\\\)_"},"sourceType":"module","tags":{"allowUnknownTags":true,"dictionaries":["jsdoc","closure"]},"templates":{"monospaceLinks":false,"cleverLinks":false,"default":{"outputSourceFiles":true}}},"opts":{"_":["src"],"package":"package.json","recurse":true,"destination":"build/apidoc","debug":true,"encoding":"utf8"}}}
DEBUG: Parsing source files: ["/Users/matt/Documents/SolarNetwork/Developer/git/jsdoc-es6-mixin-test/src/testMixin.js"]
Parsing /Users/matt/Documents/SolarNetwork/Developer/git/jsdoc-es6-mixin-test/src/testMixin.js ...
DEBUG: Finished parsing source files.
DEBUG: Indexing doclets...
DEBUG: Adding inherited symbols, mixins, and interface implementations...
DEBUG: Adding borrowed doclets...
DEBUG: Post-processing complete.
Generating output files...
Finished running in 0.57 seconds.
```

### Expected behavior

The prefix `undefined` should not appear.

### Current behavior

The prefix `undefined` is showing up on mixin method names.

### Your environment

| Software         | Version
| ---------------- | -------
| JSDoc            | 3.5.3
| Node.js          | 8.1.3
| npm              | 5.0.3
| Operating system | OS X

**Comment by msqr** [comment]
Here's a screen shot of what I mean, with `undefined` highlighted:

![testmixin-docs-annotated](https://user-images.githubusercontent.com/139448/28236860-76939b50-6985-11e7-97ae-117b218e6d36.png)

**Comment by hegemonic** [comment]
This is definitely a bug of some sort; we shouldn't be adding `undefined` to method names regardless of whether your JSDoc tags are correct. I'll look into this.

**Comment by hegemonic** [comment]
I've made some fixes that make it possible to document this pattern. The fixes are currently on master and releases/3.5; they'll be included in JSDoc 3.5.4.

With the fixes in place, here's how I would document your sample code:

```js
/**
 * Create a mixin class.
 *
 * @exports testmixin
 * @param {*} superclass - The class to mix onto.
 * @return {module:testmixin~mixin} The mixin class.
 */
const TestMixin = (superclass) =>
/**
 * A mixin.
 *
 * @mixin
 * @alias module:testmixin~mixin
 */
class extends superclass {

    /**
     * A string property.
     *
     * @type {string}
     */
    get myProp() {
        return this._myProp;
    }

    set myProp(val) {
        this._myProp = val;
    }

    /**
     * 2nd property.
     *
     * @type {string}
     */
    get myProp2() {
        return this._myProp2;
    }

    set myProp2(val) {
        this._myProp2 = val;
    }

    /**
     * Do something.
     *
     * @param {boolean} param important parameter
     * @returns {string} the base URL to SolarUser
     */
    doSomething(param) {
        console.log('param =', param);
        return 'thanks';
    }
};

export default TestMixin;
```

**Comment by msqr** [comment]
That's awesome, thank you for addressing this!

**Comment by Smolations** [comment]
@hegemonic I was wondering if you could expound on that example a bit? I am using the same pattern but I am allowing constructors in the mixins to pass options up the super chain. My mixin constructor signatures look like this:
```
constructor({ mixinOpt, anotherMixinOpt = 'default', ...superOpts }) {
  super(superOpts);
  // ...
}
```
Using your example I was able to get the docs to show when another module uses the mixin by specifying `@mixes module:...`. However, I am unable to see docs for the constructor in either the mixin docs or the class that mixes it in. I see a member variable show up in the mixin docs, but the class that mixes it doesn't show the member, only a link to the mixin. Is that expected behavior? Could you include an example of a class that implements a mixin and exports that class as a module?

**Comment by Smolations** [comment]
Also, if you have time, perhaps you can solve a related problem. In my project, I am planning on publishing `myModule` on npm. It will allow implementors to import two types: mixins and models. Mixins are defined as above, and models are classes that extend mixins. The way implementors will gain access to these will be like this:
```
const { Mixin1, Mixin2 } = require('myModule/mixins');
const { Model1, Model2 } = require('myModule/models');
```
And here is my directory structure:
```
mixins/
  index.js
  mixin1.js
  mixin2.js
models/
  index.js
  model1.js
  model2.js
```
Each index file imports all of the individual mixins/models, e.g.:
```
// mixins/index.js
const Mixin1 = require('./mixin1');
const Mixin2 = require('./mixin2');

module.exports = {
  Mixin1,
  Mixin2,
};
```
Every model is exported as a class that extends from one or more mixins. However, if I document everything as a module, they show up under the modules section in the docs. I would expect to only have two entries in the modules section: `myModule/mixins` and `myModule/models`. Then the mixins would all show up under the Mixins section and all of the models would show up under the Classes section. Is this possible? If so, how might I go about doing it?

**Comment by icsaba** [comment]
How do u add multiple mixins? So my code looks like:

```javascript 
const Mixin1 = (superclass) => class extends superclass {} 

const Mixin2 = (superclass) => class extends superclass {} 

class A extends Mixin1(Mixin2(SomeBaseClass)) {}
```

but just one of the mixins docs appears in VSCode.

**Comment by manix** [comment]
> How do u add multiple mixins? So my code looks like:
> 
> ```js
> const Mixin1 = (superclass) => class extends superclass {} 
> 
> const Mixin2 = (superclass) => class extends superclass {} 
> 
> class A extends Mixin1(Mixin2(SomeBaseClass)) {}
> ```
> 
> but VSCode intellisense can recognize the Mixin1 docs only. Do u have any suggestions for this problem?

+1

How do I get intellisense to recognize, in this case, Mixin2's members?
