### ISSUE TITLE
Generate documentation for code with return outside function

### ISSUE THREAD

**Issue by kozi** [jsdoc3/jsdoc#1411]
I am trying to generate jsdoc documentation for code with return statements outside of functions.
Since the 3.5.0 release babylon is used as parser and the parser treats this as an error.

The babylon parser has some Options https://github.com/babel/babylon#options
`allowReturnOutsideFunction`  By default, a return statement at the top level raises an error. Set this to true to accept such code.

**IDEA:** Add the possibility to customize the parserOptions in the jsdoc config file.

**Comment by hegemonic** [comment]
Fixed on master and releases/3.5. The fix will be included in JSDoc 3.5.4.

Now that I've enabled all of Babylon's options, I don't think there's a good use case for making the parser options customizable.
