### ISSUE TITLE
Configurable main page title [Feature Request]

### ISSUE THREAD

**Issue by omrilotan** [jsdoc3/jsdoc#1423]
Use 'mainpagetitle' option to modify the main page's title

### Expected behavior
`mainpagetitle` should change the page's H1 and title tags of the main page

### Current behavior
Name is hard coded to "Home"

[```generate('Home',```](https://github.com/jsdoc3/jsdoc/blob/8e2f8686c42c9c371c35be10faac61268497b12e/templates/default/publish.js#L625)

**Comment by yossi-eynav** [comment]
YES!

**Comment by omrilotan** [comment]
Suggested solution #1424

**Comment by omrilotan** [comment]
Suggested solution #1424: Add option "projectname" to modify main page title
