### ISSUE TITLE
Deadlock!? Files reset changes on fail!?

### ISSUE THREAD

**Issue by blaasvaer** [jsdoc3/jsdoc#1434]
I use Sublime/DocBlockr to insert jsdoc comments in my code. When I fail to fill out the stub – like change {[type]} to the proper type {string} – jsdoc3 fails. But when I then remove those failing lines and save the file and run gulp again; jsdoc3 fails. BUT, then it freaking reset my changes (put back those deleted lines into the file).

Now, I use git, and I can only suspect IT to being able to 'remember' anything about my files content. But what is it that triggers a file reset when jsdoc3 fails? I'm totally baffled and have no clue where to start looking for a solution ... other than scrapping jsdoc3 and go with something else.

**Comment by hegemonic** [comment]
JSDoc only reads source files; it never alters them. Another tool must have caused this issue to occur.
