### ISSUE TITLE
onTagged called twice for each actual usage of the defined tag

### ISSUE THREAD

**Issue by devsnek** [jsdoc3/jsdoc#1450]
`onTagged` in a custom tag definition is called twice for each occurrence of the tag

example tag declaration:
```js
exports.defineTags = (dictionary) => {
  dictionary.defineTag('dynamic', {
    onTagged(doclet, tag) {
      console.log(tag, 'look i\'m here twice weeeeee');
    },
  });
};
```

### Expected behavior

`onTagged` called once

### Current behavior

`onTagged` called twice

### Your environment

| Software         | Version
| ---------------- | -------
| JSDoc            | 3.5.5
| Node.js          | 8.5.0
| npm              | 5.3.0
| Operating system | Darwin sentry 17.0.0 Darwin Kernel Version 17.0.0

**Comment by Elaniobro** [comment]
@devsnek was this resolved? If so how? I am using a plugin that is currently doubling up as well.
