### ISSUE TITLE
ES6 class: document class & constructor separately

### ISSUE THREAD

**Issue by GerkinDev** [jsdoc3/jsdoc#1455]
Hi,

In order to be clearer to read (IMHO) and to be conform with eslint rule `require-jsdoc`, I'd like to be able to document classes & constructors separately. Documentation code I'm trying to use is like in the *Input code* section

For information, the [require-jsdoc](https://eslint.org/docs/rules/require-jsdoc) rule, with some configuration, requires that both the `class` & `constructor` nodes have documentation.

If you have an alternate way to achieve the same requirements, I'd be glad to know it :)

### Input code

```js
/**
 * @class Foo
 * @classdesc Foo fooing bars
 */
class Foo {
	/**
	 * @constructs Foo
	 * @description Constructs a new Foo by setting bar to `bar`
	 * @param {*} bar Thing representing some data
	 */
	constructor( bar ){
		this.bar = bar;
	}
}
```
### Expected behavior

I'd like that both instructions were merged, to document a single class with provided `classdesc`, and with constructor documented from 2nd comment.

### Current behavior

Currently, JSDoc generates 2 classes with the same name: Foo.

### Your environment

| Software         | Version
| ---------------- | -------
| JSDoc            | 7.10.1
| Node.js          | 3.5.5
| npm              | 4.2.0
| Operating system | OSX

**Comment by jakeknerr** [comment]
Try this:

```
/**
 * Foo fooing bars
 */
class Foo {
	/**
	 * Constructs a new Foo by setting bar to `bar`
	 * @param {*} bar Thing representing some data
	 */
	constructor( bar ){
		this.bar = bar;
	}
}
```

**Comment by GerkinDev** [comment]
Hi, thank you for your answer, that worked well. But I still don't understand why the "*verbose*" way does not work as intended.

Anyway, I close this issue. Thank you :)
