### ISSUE TITLE
Go back to markdown-it-anchor?

### ISSUE THREAD

**Issue by chrisveness** [jsdoc3/jsdoc#1481]
https://github.com/jsdoc3/jsdoc/commit/599a376cb51c00ed1239fb092cc5f5512d9041c6 switched from `markdown-it-anchor` to `markdown-it-named-headers`, but the latter seems to be inconsistent with GitHub style links (qv [toc_filter.rb](https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/toc_filter.rb)), and hence with the [remark](https://www.npmjs.com/package/remark) `remark-autolink-headings` plugin, etc. Also `markdown-it-named-headers` has lower npm download figures than `markdown-it-anchor`.

The handling of punctuation seems to be different from GitHub, and also with `markdown-it-named-headers`, anchors in headings get included in the id. It is also arguably broken in its own right (e.g. italic formatting in a header can result in leading/trailing hyphens).

The incompatibility with GitHub styling in particular makes the `idInHeadings` option almost useless to me.

Could you go back to `markdown-it-anchor`?

**Comment by hegemonic** [comment]
JSDoc 3.6.0 will no longer support Node.js 4.x, so yes, we can and should make this change.

**Comment by hegemonic** [comment]
Fixed on master. The fix will be included in JSDoc 3.6.0.
