### ISSUE TITLE
Unable to select text track with no ROLES ( v 2.3.0 )

### ISSUE THREAD

**Issue by kchandran1029** [jsdoc3/jsdoc#1488]
No way to select a text track that has empty roles when there is another track for same language that has non-empty roles.

Version : 2.3.0

### Input code
// this sets currentTextRole_ to empty.
shakaPlayer.selectTextLanguage(this.textTracks[trackId].language, ''); 
shakaPlayer.setTextTrackVisibility(true);

// Now refine the choice based on role preference.
  if (preferredRole) {   // Kiran : This won't be true for empty role preference
    var roleMatches = shaka.util.StreamUtils.filterTextStreamsByRole_(
        chosen, preferredRole);
    if (roleMatches.length) {
      return roleMatches;
    } else {
      shaka.log.warning('No exact match for the text role could be found.');
    }
  }

Then , 

 // Either there was no role preference, or it could not be satisfied.
  // Choose an arbitrary role, if there are any, and filter out any other roles.
  // This ensures we never adapt between roles.

  var allRoles = chosen.map(function(stream) {
    return stream.roles;
  }).reduce(shaka.util.Functional.collapseArrays, []);

// Kiran: This will return the stream that has non empty ROLE.

### Expected behavior

should return the first track that matches the language as well as exact role, if role preference is empty , should return the track where roles.length === 0.

### Current behavior
Always returns the non-empty role text track.

**Comment by kchandran1029** [comment]
@joeyparrish , any idea about this ?

**Comment by joeyparrish** [comment]
@kchandran1029, this appears to be a Shaka Player issue, but you filed it against jsdoc.  That would explain why we didn't see it before now.  Can you close this and file on Shaka Player?  https://github.com/google/shaka-player/issues/new
