### ISSUE TITLE
Reopen 2+ year old locked issue

### ISSUE THREAD

**Issue by OmgImAlexis** [jsdoc3/jsdoc#1497]
Can https://github.com/jsdoc3/jsdoc/issues/509 be reopened since it's been closed for the last 2 years and a lot has changed since then.

**Comment by jake-lambert-volusion** [comment]
I happen to be here looking for the same info, this is a bit newer: https://github.com/jsdoc3/jsdoc/issues/1197#issuecomment-312948746
