### ISSUE TITLE
How do I get Markdown in descriptions

### ISSUE THREAD

**Issue by mercmobily** [jsdoc3/jsdoc#1499]
I would like to be able to have Markdown text in function descriptions. Is this something that can be done with a plugin? If so, how?

### Input code

```js
  /**
  * I would love to use `markDown` in a function's description
  */
  async startWebDriver () {
    // If it's already connected, nothing to do
    if (this._webDriverRunning) return

    // If spawning is required, do so
    if (this._spawn) {
      // No port: find a free port
      if (!this._port) {
        this._port = await getPort({ host: this._hostname })
      }

      // Options: port, args, env, stdio
      var res = this._browser.run({
        port: this._port,
        args: this._args,
        env: this._env,
        stdio: this._stdio }
      )
      this._killCommand = res.killCommand
      this._commandResult = res.result
    }
```

### Expected behavior

I would love to see that `markdown` as `<code>`

### Your environment

| Software         | Version
| ---------------- | -------
| JSDoc            | 3.5.5
| Node.js          | 8.9.3
| npm              | 5.6.0
| Operating system | Linux

**Comment by Jaid** [comment]
It seems that you are looking for the official Markdown plugin that is [already included](https://github.com/jsdoc3/jsdoc/tree/master/plugins) in your installed `jsdoc` dependency. You can enable that plugin in your JSDoc config. Reference the config file in your `jsdoc` command.

```bash
jsdoc --configure .jsdoc.config.js
```

And create a config file in your project folder.

`.jsdoc.config.js`
```js
module.exports = {
    opts: {
        recurse: true
    },
    plugins: ["plugins/markdown"]
}
```

**Comment by mercmobily** [comment]
Thank you!!!
