### ISSUE TITLE
Update to latest taffyDB for license purpose

### ISSUE THREAD

**Issue by josecolella** [jsdoc3/jsdoc#1531]
Hello, The version 3.5.5 uses a version of taffydb that did not have any license. Can you update the jsdoc to use the latest taffydb?

**Comment by hegemonic** [comment]
Sorry, but I can't upgrade `taffydb`. The most recent version has a major bug that breaks JSDoc. See the "Alternative 1" section of [this comment](https://github.com/jsdoc3/jsdoc/issues/961#issuecomment-244245221).

For what it's worth, if you look at the `taffy.js` file in the `taffydb` package, the BSD license appears in a comment at the top of the file. That was good enough to satisfy my company's lawyers, but I know that some lawyers are less forgiving.

A future version of JSDoc will drop the TaffyDB dependency, but I can't say how soon that will happen.
