### ISSUE TITLE
Jsdoc File 

### ISSUE THREAD

**Issue by arn-the-long-beard** [jsdoc3/jsdoc#1536]
Hello guys. I got an issue with jsdoc and I do not understand what is happening 

### Input commands

` jsdoc -c jsdoc.json`

### JSDoc configuration

```js

 
 {
  "tags": {
    "allowUnknownTags": false
  },
  "source": {
    "include": [ "index.js" ],
    "includePattern": ".js$",
    "excludePattern": "(node_modules/|docs)"
  },
  "plugins": [
    "plugins/markdown"
  ],
  "opts": {
    "template": "assets/template/docdash/",
    "encoding": "utf8",
    "destination": "docs/",
    "recurse": true,
    "verbose": true
  },
  "templates": {
    "cleverLinks": false,
    "monospaceLinks": false
  },

  "docdash": {
    "static": [true],
    "sort": [true]
  }

}


```
I also tried just with without config , I also try the default config example and I get the same error.

I saw it can be wierd stuff with UTF8 with Dom and UTF8 without. I tried both and I get the error.

### JSDoc debug output

```
Cannot parse the config file jsdoc.json: TypeError: stripJsonComments is not a function
Exiting JSDoc because an error occurred. See the previous log messages for details.
DEBUG: JSDoc 3.5.5 (Thu, 14 Sep 2017 02:51:54 GMT)
DEBUG: Environment info: {"env":{"conf":{},"opts":{"_":[],"configure":"jsdoc.json","debug":true,"destination":"./out/","encoding":"utf8"}}}
There are no input files to process.
```

### Expected behavior

I am trying to generate my documentation. I did it 2 months ago with an other computer ( on linux) and there were no problems.

### Current behavior

Cannot parse the config file jsdoc.json: TypeError: stripJsonComments is not a function
Exiting JSDoc because an error occurred. See the previous log messages for details.
DEBUG: JSDoc 3.5.5 (Thu, 14 Sep 2017 02:51:54 GMT)
DEBUG: Environment info: {"env":{"conf":{},"opts":{"_":[],"configure":"jsdoc.json","debug":true,"destination":"./out/","encoding":"utf8"}}}
There are no input files to process.

I got also this mistake on a colleague computer- He has node.js 8.11.0 , I am using the 10

### Your environment

| Software         | Version
| ---------------- | -------
| JSDoc            |  3.5.5
| Node.js          | 10.1.0 
| npm              | 6.1.0
| Operating system | Windows 10

Let's find out whats is happening ! 🗡

**Comment by hegemonic** [comment]
It sounds like you're probably running JSDoc from a clone of the Git repo. If so, I bet you can fix this issue by changing to the clone directory, then running `npm install`.
