### ISSUE TITLE
Generating docs don't work in folders that start with an underscore (or subfolders of those)

### ISSUE THREAD

**Issue by Felix-Franz** [jsdoc3/jsdoc#1541]
### Input code

It is necessary to put following file (`test.js`) in a folder starting with an underscore (e.g. `_test`).

```js
/** This is a description of the foo function. */
function foo() {
}
```

### JSDoc configuration

No configuration need to be provided to reproduce this bug. Just run:

```bash
jsdoc test.js
```

### JSDoc debug output

```
There are no input files to process.
```

### Expected behavior

The documentation should be build.

### Current behavior

Only an error message is shown, no documentation is generated.

### Your environment

| Software         | Version
| ---------------- | -------
| JSDoc            | 3.5.5
| Node.js          | 8.11.3
| npm              | 5.6.0
| Operating system | Microsoft Windows 10

**Comment by mreuter** [comment]
In its default configuration, jsdoc ignores files starting with an underscore. The default exlude pattern is `(^|\\/|\\\\)_` You have to use a config file and change the excludePattern (see: http://usejsdoc.org/about-configuring-jsdoc.html)

**Comment by Felix-Franz** [comment]
Oh I did not see that... 😬

Thank you very much!
