### ISSUE TITLE
Load config from package.json

### ISSUE THREAD

**Issue by ai** [jsdoc3/jsdoc#1550]
### Expected behavior

All modern JS tools take config or from `.TOOLrc` or from `"TOOL"` key in `package.json`. The second way is nice to keep the project root clean. It will be cool if JSDoc supports also `"jsdoc"` key in `package.json`.

Maybe we should add the same behavior to JSDoc? For instance, [cosmiconfig](https://github.com/davidtheclark/cosmiconfig) could automatically look into both places.

### Current behavior

JSDoc now takes options only from CLI arguments or `.jsdocrc` config.

@hegemonic if you like this idea, I will send PR.

**Comment by damianobarbati** [comment]
+1 for this, @ai please submit a PR 🙏🏻

**Comment by ai** [comment]
@damianobarbati I think nobody will accept it :(

**Comment by hegemonic** [comment]
Fixed on master. The fix will be included in the next major version of JSDoc. Sorry, but I don't have an estimated date for that release.
