### ISSUE TITLE
JSDoc info not showing in VSCode on `exports.default`

### ISSUE THREAD

**Issue by mesqueeb** [jsdoc3/jsdoc#1573]
I have a very strange experience with VSCode and JSDocs.

JSDocs information is shown for named exports, but not for default exports with the commonJS export method.

### Problem: No info popup on `exports.default`

File: `index.js`

```js
/**
 * Some explanation
 *
 * @param {object} obj The obj has to be~~~ !
 * @returns {void}
 */
function fn (obj) {
  // ...
}

exports.fn = fn;
exports.default = fn;
```
Then in another file:

### Case 1: `import` import
```js
    import fn from './index'
    fn // → no JSDoc info...
    
    import { fn } from './index'
    fn // → JSDoc info works
```
So it works on named import, but not on default.
### Case 2: `require()` import
```js
    let fn = require('./index')
    fn // → no JSDoc info...
    
    let fn = require('./index').fn
    fn // → JSDoc info works
```
So it works on named import, but not on default.

### Gif to show exactly what happens

![2018-09-27 13 13 10](https://user-images.githubusercontent.com/3253920/46123104-6c512280-c257-11e8-8c00-654f6ef568e9.gif)

Related my question on StackOverflow: https://stackoverflow.com/questions/52511753/jsdoc-broken-on-exports-default-in-vscode

**Comment by lll000111** [comment]
You shojld post that to VScode.

https://github.com/Microsoft/vscode

This repo here is a tool to create API documentation from JSDoc comments and has nothing to do with whatever VSCode does or doesn't do.

**Comment by hegemonic** [comment]
Yep, what @lll000111 said.

**Comment by thammarith** [comment]
[Discussion of VSCode](https://github.com/Microsoft/TypeScript/issues/24033)
