### ISSUE TITLE
tag value string with spaces

### ISSUE THREAD

**Issue by crobinson42** [jsdoc3/jsdoc#1578]
Is there a solution to using spaces in tag values, ie: `@alias POST /token/validate`

### Input code

```js
/**
   * Validate a user token and
   * return the data needed for first load on all platforms.
   * If the token validation fails a 403 will be returned.
   *
   * example response:
   * {
   *   user, // user.metadata populated
   *   organization,
   * }
   * @alias POST /token/validate
   * @param ctx
   * @returns {Promise<void>}
   */
```

### Your environment

| Software         | Version
| ---------------- | -------
| JSDoc            | 3.5.5
| Node.js          | 10
| npm              | 6
| Operating system | OSX

**Comment by lll000111** [comment]
What exactly is the question? If you want the style used in the output HTML changed just change the template.

**Comment by crobinson42** [comment]
Thanks for the suggestion - I was looking to get the benefit of JSDOC's nesting hierarchy and unable to accomplish this when there are spaces in an `@alias` ie: `@alias some name` or `@alias "some name"`, etc..

I worked around it.
