### ISSUE TITLE
Code for version 3.5.5 of JSDoc on npm is different from that on Github

### ISSUE THREAD

**Issue by brettz9** [jsdoc3/jsdoc#1579]
### Your environment

| Software         | Version
| ---------------- | -------
| JSDoc            |  Supposedly 3.5.5
| Node.js          | 9.2.1
| npm              | 6.4.1
| Operating system | 10.14

When I obtain 3.5.5 from npm, it is different from the latest version on Github. It is also missing code improvements such as the markdown highlight option.

Here's the portion from our `package-lock.json` showing us getting the more current code on Github:

```diff
     "jsdoc": {
-      "version": "3.5.5",
-      "resolved": "https://registry.npmjs.org/jsdoc/-/jsdoc-3.5.5.tgz",
-      "integrity": "sha512-6PxB65TAU4WO0Wzyr/4/YhlGovXl0EVYfpKbpSroSj0qBxT4/xod/l40Opkm38dRHRdQgdeY836M0uVnJQG7kg==",
+      "version": "git+https://github.com/jsdoc3/jsdoc.git#b21427343c7294bbf1f14c718a390f3e955e37cb",
+      "from": "git+https://github.com/jsdoc3/jsdoc.git#b21427343c7294bbf1f14c718a390f3e955e37cb",
```

Might your last npm release may have been based on a different version than that on Github, e.g., by having been present on an older branch when doing `npm publish`?

**Comment by hegemonic** [comment]
I release JSDoc from the `releases/x.x` branches, not the `master` branch. At the moment, `master` is where the next minor version gets developed. (That's 3.6.0 as of right this second.)
