### ISSUE TITLE
Reopen locked issue again

### ISSUE THREAD

**Issue by OmgImAlexis** [jsdoc3/jsdoc#1603]
Can #509 be unlocked since it's been locked for quite some time and a lot has changed since then.

@hegemonic I'd appreciate it if you actually gave a reason for closing and locking an issue instead of just closing it especially when the issue I was asking about was another issue you locked. This is the kind of behavior that drives users away. 👎 

Ref: https://github.com/jsdoc3/jsdoc/issues/1497

**Comment by hegemonic** [comment]
I closed and locked #1497 because, to be honest, I don't think more discussion in #509 is likely to be productive.

I've unlocked #509 anyhow, but I reserve the right to lock it again.

**Comment by OmgImAlexis** [comment]
Okay but I asked for an answer and not a discussion. You didn’t even try to answer instead you just locked the issue and palmed me off.

Kinda off putting to be honest and I’m sure others have had similar experiences but haven’t spoken up.

**Comment by hegemonic** [comment]
Yes, I understand that you were put off by my response. Thank you for the feedback.
