### ISSUE TITLE
How to properly document optional return properties

### ISSUE THREAD

**Issue by gabmontes** [jsdoc3/jsdoc#1620]
How a function that return an object with optional/nullable properties shall be documented?

```js
/**
 * A function that returns an object with an optional property.
 *
 * @param {*} val Any value.
 * @returns {{key:*}} An object with or without `key` prop.
 */
function myFunction (val) {
  return val ? { key: val } : {}
}
```

In the example above, the `key` property is not specified as optional/nullable. How should that be specified? It is not clear to me from the docs how to do that. The documentation for @ype appears to be missing that scenario.

Suggestion: Typescript uses the following syntax that might work well for this case: `{key?:*}`

**Comment by lll000111** [comment]
Use a `@typedef {Object} MyReturnObj` (plus `@property` tags) to define a type for your return object and declare the property optional there.

http://usejsdoc.org/tags-property.html (2nd example)

**Comment by JustinBeaudry** [comment]
> Suggestion: Typescript uses the following syntax that might work well for this case: {key?:*}
JSDoc supports [*some* Google Closure Compiler syntax](http://usejsdoc.org/tags-type.html#jsdoc-types). For a `nullable` type you can use something comparable to TypeScript `{?key: *}`

**Comment by gabmontes** [comment]
@lll000111 @JustinBeaudry thanks!
