### ISSUE TITLE
How to export/import types declared in commonjs modules?

### ISSUE THREAD

**Issue by matt-curtis** [jsdoc3/jsdoc#1635]
I'm trying to import a type declared in a commonjs module (though not exported as part of its `module.exports`) in another file, and use it.

Say I have a file called `sauce.js`:

```js
class Sauce { }

function getFavoriteSauce(){
	return new Sauce();
}

module.exports = { getFavoriteSauce };
```

And another file called `index.js` (where I want to refer to the class type `Sauce`):

```js
const { getFavoriteSauce } = require("./sauce");

/**
 * @param {Sauce} sauceA // doesn't work
 * @param {Sauce} sauceB // doesn't work
 */
function mixSauces(sauceA, sauceB){
	sauceA.mixWith(sauceB);
};
```

While the type definition for `getFavoriteSauce` includes `Sauce` (`() => Sauce`) I can't mention `Sauce` as a type directly.

There doesn't appear to be any way to export the `Sauce` class and refer to it from another file. I've tried everything — `@typedef`, namely, with `@static`, `@global` and others thrown in out of desperation.

Is there no way to directly refer to `Sauce`?

**Comment by Mash12** [comment]
Facing same issue. Is there any solution or work around?

**Comment by lll000111** [comment]
You can declare types declared via `@typedef` as `@global`. Then jsdoc will create links in the HTML output.

If your quesiton isn't about jsdoc, &mdash; *this tool right here* &mdash; but about type-stuff in your IDE this is the wrong place.

**Comment by matt-curtis** [comment]
> If your quesiton isn't about jsdoc, — _this tool right here_ — but about type-stuff in your IDE this is the wrong place.

Thank you for clearing that up. In this case the problem seems to come from the fact that [Visual Studio Code doesn't support `@global`](https://github.com/Microsoft/TypeScript/wiki/JSDoc-support-in-JavaScript).
