### ISSUE TITLE
Need to show an error when the "lends" tag is used incorrectly

### ISSUE THREAD

**Issue by hegemonic** [jsdoc3/jsdoc#343]
I ran the following code through JSDoc:

``` javascript
var MyClass = Class.define({
    /** @lends MyClass# */

    /**
     * Create an instance of MyClass.
     * @constructs
     */
    initialize: function() {}
});
```

JSDoc reported the following fatal error:

```
js: "/Users/jeffw/github/jsdoc3/jsdoc/jsdoc.js", line 286: exception from uncaught JavaScript throw:
TagValueRequiredError: The @name tag requires a value. File: test.js, line: 8
```

If you move the `@lends` tag so it appears before the object literal, the example works as expected.

~~It seems like we should allow the `@lends` tag to appear within the object literal in this case. At the very least,~~ we should clarify the error message, since the example doesn't even use the `@name` tag...

**Comment by yordis** [comment]
:+1:

**Comment by MattiSG** [comment]
I get that error while my comment is _before_ the object. It is inline, though:

```javascript
var Runner = new Class( /** @lends Runner.prototype */ {

	Extends: require('events').EventEmitter,
```

The error is reported at the `@constructs`, much later: `ERROR: The @name tag requires a value. File: Runner.js, line: 70`

[Source file](https://github.com/MattiSG/Watai/blob/679619ed98a86ba52024960aa7816ba1cfe60e66/src/controller/Runner.js).

**Comment by hegemonic** [comment]
After investigating this thoroughly, I don't think there's any way for us to log a better error message in this case. Here's why:

+ In theory, we could check the AST node's type in the [`lends` tag's `onTagged` method](https://github.com/jsdoc3/jsdoc/blob/1c99ec39/lib/jsdoc/tag/dictionary/definitions.js#L549) and verify that the AST node a) exists and b) is either a block statement or object expression. However, when the `onTagged` method is called, we haven't set `doclet.meta.code.node` yet, so we don't have access to information about the AST node.
+ We log an error about the `@name` tag because the parent object wasn't documented, which prevents us from resolving `this` within the object, which in turn causes the property's name to be set to an empty string. That information doesn't allow us to say that there's a misplaced `@lends` tag—all we know is that the parent object wasn't documented.

    We _could_ set the property's name to its actual name in this case, rather than an empty string. But then your docs would still be wrong, and you wouldn't get any warnings at all. That doesn't seem like much of an improvement.

Because I don't see any good way to fix this issue, I'm closing it.
