### ISSUE TITLE
Find a way to show namespace paths

### ISSUE THREAD

**Issue by arcanis** [jsdoc3/jsdoc#43]
Hi,

In my current application, I've multiple namespaces, each of one containing classes, mixins, and sub-namespaces.

When I generate the doc, I've got this in my side pannel. As you can see, everything is messed : I can't know from a single eye shot if the class Array is in the GUI or LIB namespaces (in fact, it's in MixinUtils ...).

I think it could be a problem for large applications. Unfortunately, I currently don't know how to pretty print these informations.
## Classes

CrashReportScreen
FlatScreen
ProgressScreen
WebGLInfoScreen
Array
Object
## Namespaces

GUI
BrowserUtils
LIB
ClassUtils
MixinUtils
## Mixins

EventBehavior
StoreBehavior
VolatileBehavior
WidgetBehavior

**Comment by bsvensson** [comment]
Hi @hegemonic, we also want a tree to use in our template :)
About the *longname-to-tree method*,  could you give some more hints or pointers in regards to this yet-to-be documented method?

**Comment by hegemonic** [comment]
The `longnamesToTree` method is now [documented on GitHub master](https://github.com/jsdoc3/jsdoc/blob/f3a31e9a/lib/jsdoc/name.js#L394). It's available as both `module:jsdoc/name.longnamesToTree` and `module:jsdoc/util/templateHelper.longnamesToTree`.
