### ISSUE TITLE
Members not parsed if prefixed for a comma

### ISSUE THREAD

**Issue by Smolations** [jsdoc3/jsdoc#446]
I just encountered an issue when documenting an object literal namespace. Many people like to put commas before names in arrays, var declarations, object literals, etc. Whether it is good coding style or not, it really is just a style, so it should be accounted for. Unfortunately, members are skipped when the comma is out in front of them:

```
/** @namespace */
var MyNamespace = {
    /** This will get documented */
    foo: 'howdy'

    /** This will NOT get documented */
    , bar: ' ho neighborino!'
}
```

I know that I can force the documentation by including a @member directive or something similar (virtual doc), but I think writing the documentation should be as quick and painless as possible.  =]

**Comment by volosovich** [comment]
Hello everyone
Sorry if I write message to wrong topic or ask strange/stupid question.

I use JSDoc and when I use comma in description, this block not render in documentation.
Example:
```
/**
@function checkCustomMessage - check if config has custom message if no - send default message.
*/
```
This block is rendering.

```
/**
@function checkCustomMessage - check if config has custom message, if no - send default message.
*/
```
This block isn't rendering. Please note to comma before "if no".

So, is feature or bug?
Many language use comma in sentences, especially ukraine, russian, english etc .
Thank you very much for your answer. 

Use:
`"grunt-jsdoc": "^2.1.0"`

**Comment by Booster2ooo** [comment]
Hello,

I created a little plugin to support comma first style:
https://github.com/Booster2ooo/jsdoc-comma-first

It's nothing fancy, I hope it help.

**Comment by hegemonic** [comment]
Given the existence of a plugin that supports comma-first style (thanks, @Booster2ooo!) and the general lack of demand for this feature, I'm closing this issue.
