### ISSUE TITLE
Allow users to provide a list of links to external API docs

### ISSUE THREAD

**Issue by hegemonic** [jsdoc3/jsdoc#534]
It would be nice if we supported something like Javadoc's [`package-list` file](http://stackoverflow.com/questions/2818204/how-to-generate-links-to-the-android-classes-reference-in-javadoc). This allows you to automatically link specified types to an external set of API docs.

We would need to use a different format, though, that includes URLs. Maybe something like:

``` js
{
  "string": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
  "module:foo/bar": "http://example.com/docs/api/module-foo_bar.html"
}
```

We might want to implement this as a plugin.

**Comment by hegemonic** [comment]
Given the lack of demand for this feature, and what I suspect would be the very high complexity of implementing it, I'm closing this issue.

**Comment by JustinBeaudry** [comment]
I know this is an old issue, but I wanted to say that I created a (*very*) simplistic plugin for reusing `{@link}` inline tags. https://github.com/JustinBeaudry/jsdoc-plugin-url. It requires the user to manually create links in their JSDoc configuration file. For example, this is an example configuration object:

```json
{
  "urls": {
    "voightKampff": {
      "url": "https://bladerunner.fandom.com/wiki/Voight-Kampff_test",
      "name": "Voight-Kampff"
    },
    "bladeRunners": "module:bladerunner/bladerunners~bladerunners",
    "replicants": "module:bladerunner/replicants~replicants"
  }
}
```

and then reference them via a pseudo-tag (not actually a tag, just a `beforeParse` hook):

```javascript
/**
 *
 * See {@url voightKampff} for more information. {@url bladeRunners}. {@url replicants}.
 * 
 */
```
I've found it immensely helpful in cleaning up links. As I like to use LOTS of them.
