### ISSUE TITLE
Support ECMAScript 2015 syntax

### ISSUE THREAD

**Issue by kilianc** [jsdoc3/jsdoc#555]
Generators currently cause the following error:

```
Error: Line 69: Unexpected token *
```

**Comment by interactionist** [comment]
I second @flying-sheep. ES6 support would be awesome.

**Comment by jhorwit2** [comment]
+1. ES6 support would be amazing.

**Comment by danwoods** [comment]
+1

**Comment by arielschiavoni** [comment]
+1

**Comment by gitawego** [comment]
+1

**Comment by hegemonic** [comment]
I'll gladly accept pull requests from anyone who wants to help implement ES 2015 (formerly ES6) support in JSDoc. There's already an open pull request to add support for ES 2015 classes.

Note that I just switched JSDoc to use the [Espree](https://github.com/eslint/espree) parser, a fork of Esprima, so we're limited to the [features that Espree supports](https://github.com/eslint/espree/issues/10). However, Espree is moving very rapidly towards full support for ES 2015.

**Comment by sochka** [comment]
So if I understand right, most of the ES6 features are supported now?

**Comment by hegemonic** [comment]
@sochka The opposite. For most ES 2015 nodes, we log a warning and ignore the node.

**Comment by sochka** [comment]
How do I know what's supported? I'm interested in classes and lambdas in particular.

**Comment by hegemonic** [comment]
Classes and lambdas are not currently supported.

When I get a chance, I'll clean up the to-do list in this bug so it's more obvious what's done and what isn't done.

**Comment by vjsingh** [comment]
Probably not super helpful, but +1 for class support in general.

It seems to me that for any projects which use classes (like ours), the lack of support makes jsdoc largely useless? Correct me if I'm wrong.

Obviously, this message should be prefaced with the fact that I appreciate the creator for their work and regret that I don't have time to contribute myself.

**Comment by hegemonic** [comment]
For some additional context, I should point out that the major parser authors are still haggling over how to represent a variety of ES 2015 nodes in the AST: https://github.com/estree/estree/issues

It's tough to keep up with an AST syntax that's still changing from week to week, so thanks for your patience while I wait for things to settle down a bit.

**Comment by lukeapage** [comment]
> On master, JSDoc should now be able to parse ES6 files without throwing an error.

I'm having trouble with es-6 modules. At first they weren't supported by the version of espress you use (they recently added support). Next I upgraded espress and tried again. Instead of "unexpected reserved word" I now get "Illegal import declaration" and "Illegal export declaration"

It would be really nice to be able to parse and get something, even if I don't get es6 modules integrated into jsdoc yet

**Comment by hegemonic** [comment]
@lukeapage Yes, I understand that. I'm working to update Espree.

**Comment by lukeapage** [comment]
Anything i can do (without having to understand all the code and a limited
amount of time) to help?

**Comment by hegemonic** [comment]
@lukeapage Nope, at this point it's all about writing code.

**Comment by hegemonic** [comment]
Classes are now supported! Code like the following now works on master (Node.js only):

```js
/** Point class. */
class Point {
    /**
     * @param {number} x - The x value.
     * @param {number} y - The y value.
     */
    constructor(x, y) {
        // ...
    }
}
```

Next up: Modules.

**Comment by interactionist** [comment]
Great work. It there an overview which ES 2015 features work as of right now?

**Comment by hegemonic** [comment]
@interactionist See the checklist at the top of this issue.

**Comment by interactionist** [comment]
@hegemonic How could I miss that! Thanks.

**Comment by theasta** [comment]
@hegemonic I'd love to help. I saw the check list at the top but I'm guessing you are currently implementing some of the missing items. Which one can I pick?

**Comment by hegemonic** [comment]
@theasta You could tackle the new promise-related tags in #509 (see [this comment](https://github.com/jsdoc3/jsdoc/issues/509#issuecomment-63498330) for the final syntax) or the new `@yield`/`@yields` tag for generators. Both of those will require adding new doclet properties, which means they'll need template changes as well.

**Comment by theasta** [comment]
@hegemonic Feel free to assign the Promise ticket to me.

**Comment by interactionist** [comment]
@hegemonic I would like to tackle the block scope (let, const, for …) but I don't know where to start from.

**Comment by hegemonic** [comment]
@interactionist I'm not sure about that one either. There may not be anything to do, but I haven't investigated yet.

**Comment by djMax** [comment]
I'm having trouble getting this to work on master. I cloned the repo, ran gulp, npm link'ed on both sides, and I get:

WARNING: JSDoc does not currently handle ClassExpression nodes. Source file: /Users/mmetral/dev/js/invoice.js, line 63

/Users/mmetral/dev/node/jsdoc/lib/jsdoc/src/astnode.js:112
    switch (node.type) {
                ^
TypeError: Cannot read property 'type' of null
    at exports.nodeToValue (/Users/mmetral/dev/node/jsdoc/lib/jsdoc/src/astnode.js:112:17)
    at exports.nodeToValue (/Users/mmetral/dev/node/jsdoc/lib/jsdoc/src/astnode.js:160:19)
    at Object.exports.getInfo (/Users/mmetral/dev/node/jsdoc/lib/jsdoc/src/astnode.js:317:25)
    at Visitor.makeSymbolFoundEvent (/Users/mmetral/dev/node/jsdoc/lib/jsdoc/src/visitor.js:442:33)
    at Visitor.visitNode (/Users/mmetral/dev/node/jsdoc/lib/jsdoc/src/visitor.js:392:18)
    at Visitor.visit (/Users/mmetral/dev/node/jsdoc/lib/jsdoc/src/visitor.js:314:27)
    at Walker.recurse (/Users/mmetral/dev/node/jsdoc/lib/jsdoc/src/walker.js:546:44)
    at Parser._walkAst (/Users/mmetral/dev/node/jsdoc/lib/jsdoc/src/parser.js:245:18)
    at Parser._parseSourceCode (/Users/mmetral/dev/node/jsdoc/lib/jsdoc/src/parser.js:236:18)
    at Parser.parse (/Users/mmetral/dev/node/jsdoc/lib/jsdoc/src/parser.js:157:18)
    at Object.module.exports.cli.parseFiles (/Users/mmetral/dev/node/jsdoc/cli.js:359:42)
    at module.exports.cli.main (/Users/mmetral/dev/node/jsdoc/cli.js:229:14)
    at Object.module.exports.cli.runCommand (/Users/mmetral/dev/node/jsdoc/cli.js:183:5)
    at /Users/mmetral/dev/node/jsdoc/jsdoc.js:134:13
    at Object.<anonymous> (/Users/mmetral/dev/node/jsdoc/jsdoc.js:136:3)
    at Module._compile (module.js:456:26)

**Comment by hegemonic** [comment]
@djMax Ah, I completely forgot that we also need to handle class expression nodes. Thanks for the heads up. Class declarations (as shown above) are indeed working.

**Comment by gso** [comment]
Generator using `[Symbol.iterator]`:
    *[Symbol.iterator]() {
        ...
    }
Is currently throwing the following error:
> ERROR: Unable to parse /home/user1/WebstormProjects/EonJS/src/RecurRuleContainer/RecurRuleContainer.js: Cannot call method 'toString' of undefined
Any quick workarounds would be appreciated as it is currently the only error preventing the documentation for a project from generating.

**Comment by hegemonic** [comment]
@gso I don't have a workaround for this. Do you have a reference that demonstrates that `[Symbol.iterator]` generators are valid ES 2015 code? If so, I can file an upstream bug against the Espree parser.

**Comment by lukeapage** [comment]
Generators and async/await were dropped from es6/es 2015 and moved to
es7/es2016.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Generator_comprehensions

**Comment by briandipalma** [comment]
Generators are in ES15, comprehensions were dropped.

Here is an in depth article on them and you will see `Symbol.iterator` used in the examples.

http://www.2ality.com/2015/03/es6-generators.html

I'd say the problem is `*` or computed properties not `Symbol.iterator` though.

**Comment by gso** [comment]
Symbol, https://people.mozilla.org/~jorendorff/es6-draft.html#sec-symbol-objects
Symbol.iterator falls under the heading of 'well-known symbols' https://people.mozilla.org/~jorendorff/es6-draft.html#table-1
The former link sourced from the MDN ref. page for 'Symbol' (specifications section) https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol#Specifications

**Comment by gso** [comment]
ClassDeclaration https://people.mozilla.org/~jorendorff/es6-draft.html#sec-class-definitions
ClassElement
MethodDefinition https://people.mozilla.org/~jorendorff/es6-draft.html#sec-method-definitions
GeneratorMethod https://people.mozilla.org/~jorendorff/es6-draft.html#sec-generator-function-definitions
* PropertyName
PropertyName https://people.mozilla.org/~jorendorff/es6-draft.html#sec-object-initializer
ComputedPropertyName
[ AssignmentExpression ]

**Comment by sochka** [comment]
@briandipalma what is ES15? Is it a new name for ES6 or ES7? I can't google the name for some reason

**Comment by hegemonic** [comment]
@gso I'm familiar with the spec. I'm still not clear on whether `*[Symbol.iterator]() {}` is legal ES2015 code. Please spell out why you believe that this is legal. (Or you're welcome to [file your own bug](https://github.com/eslint/espree/issues) against the Espree parser.)

@sochka The spec is now called "ECMAScript 2015", not "ECMAScript 6."

**Comment by hegemonic** [comment]
@gso Never mind--I see that [Axel Rauchmeyer's article](http://www.2ality.com/2015/03/es6-generators.html#iterating_over_trees) uses that syntax, so I'm sure it's legit. I'll file the bug against Espree.

**Comment by hegemonic** [comment]
Modules are now supported! Default exports should work:

```js
/** @module color/mixer */

export default {
    /** Blend two colors together. */
    blend: function(color1, color2) {}
};
```

As well as all sorts of named exports:

```js
/** @module color/mixer */

/** The name of the module. */
export const name = 'mixer';

/** The most recent blended color. */
export var lastColor = null;

/** Blend two colors together. */
export function blend(color1, color2) {}

// convert color to array of RGB values (0-255)
function rgbify(color) {}

export {
    /**
     * Get the red, green, and blue values of a color.
     * @function
     */
    rgbify as toRgb
}
```

If you find bugs in JSDoc's support for ES 2015 modules, please file a new issue.

**Comment by lukeapage** [comment]
@hegemonic its all awesome, thanks for your work. Any chance we can get an alpha release? we're using a github url at the moment which stops npm from shrinkwrapping (because of a mismatch in underscore versions between dependencies further down the chain)

**Comment by tkellen** [comment]
:+1: thanks for this! About to update http://github.com/endpoints to es6 module syntax. I'll let ya know if anything goes wrong :)

**Comment by gso** [comment]
FYI if not already aware -- https://github.com/jsdoc3/jsdoc/issues/555#issuecomment-89656059, bug filed against Espree https://github.com/eslint/espree/issues/123 -- iterator expression syntax, closed 3 days ago.

**Comment by ndugger** [comment]
Are we saying that class expressions are supported? I just installed jsdoc via NPM, and I get errors that state that it's not supported;

JSDoc does not currently handle [...] nodes

- "..." ExportDeclaration
- "..." ClassDeclaration
- "..." ClassBody
- "..." MethodDefinition

**Comment by gso** [comment]
Ref. https://github.com/jsdoc3/jsdoc/issues/555#issuecomment-39749496, npm git+https://github.com/jsdoc3/jsdoc.git

**Comment by otakustay** [comment]
I'm trying to use jsdoc with [babel](https://github.com/babel/babel) based project, I think it's better for jsdoc to use babel's parser so some ES7 proposal's could be support and not result in parse error

**Comment by buzzfeedjoe** [comment]
FYI when I try to use shrinkwrap for the latest development version, it fails due to an error related to the version of underscore being used (1.6.0 is needed by underscore-contrib but jsdoc uses 1.7.0). Is there a way to get around this? Thanks for the help!

npm WARN unmet dependency /opt/buzzfeed/buzzfeed/node_modules/jsdoc/node_modules/catharsis/node_modules/underscore-contrib requires underscore@'1.6.0' but will load
npm WARN unmet dependency /opt/buzzfeed/buzzfeed/node_modules/jsdoc/node_modules/underscore,
npm WARN unmet dependency which is version 1.7.0
npm ERR! Error: Problems were encountered
npm ERR! Please correct and try again.
npm ERR! invalid: underscore@1.7.0 /opt/buzzfeed/buzzfeed/node_modules/jsdoc/node_modules/underscore

**Comment by lukeapage** [comment]
@buzzfeedjoe I had the same problem.

I think Its caused by the github dependency.

From memory, we had to do this (I don't have access to the project any more)

```
npm install
npm prune
```

then manually go into `node_modules/jsdoc/node_modules/catharsis/node_modules/underscore-contrib`, create a node_modules, copy underscore and change the version to 1.6.0, then run npm shrinkwrap again to get a shrinkwrap file, then delete node_modules and install again to get the clean, reproducible install.

It goes without saying it looks like a bug in npm - you might try updating to the latest.

**Comment by buzzfeedjoe** [comment]
@lukeapage your trick worked! Thanks for the tip :)

**Comment by ariporad** [comment]
Hey everyone,

Sorry if this is not allowed by the projects contributing rules, but I'm not really sure where JSDoc stands ES6 wise. Could someone summarize it for me?

Thanks!

**Comment by h13i32maru** [comment]
Hi! Everyone!

If you want ES6 documentation tool, please consider https://github.com/h13i32maru/esdoc that I have developing :smile:

**Comment by sochka** [comment]
@h13i32maru that's nice! Would be even cooler if there was a library like angular-jsdoc with special support for angular services, directives etc. =)

**Comment by tenntenn** [comment]
> https://github.com/h13i32maru/esdoc

It sounds good! :+1:

**Comment by hegemonic** [comment]
@ariporad See the checklist near the top of this bug. Only the development version of JSDoc (not the version on npm) currently supports ECMAScript 2015.

@h13i32maru Please do not advertise your project on JSDoc's issue tracker. Thanks for your understanding.

**Comment by ariporad** [comment]
@hegemonic: Sorry if this is dumb, but is that list the list of stuff shipping in npm (which I know from you + experimentation doesn't support ES6) or master?

**Comment by hegemonic** [comment]
@ariporad That's the list of things shipping on master.

**Comment by h13i32maru** [comment]
@hegemonic I'm sorry :pensive:  If uncomfortable, please delete my comment.

**Comment by netpoetica** [comment]
> Are we saying that class expressions are supported? I just installed jsdoc via NPM, and I get errors that state that it's not supported;

> JSDoc does not currently handle [...] nodes

> "..." ExportDeclaration
> "..." ClassDeclaration
> "..." ClassBody
>"..." MethodDefinition

I am also still seeing this with my ES6 code in JSDoc 3.3.2. 

I also get an additional:
- JSDoc does not currently handle ExportSpecifier nodes

These are just warnings, but generated documentation is essentially empty / incredibly confusing.

I was hoping I could find some sort of example ES6 file using JSDoc in the way the authors of JSDoc would have expected to have their tests pass, but I do not see anything like this.

Considering the size of that list of implemented items, I would think that users (including myself) must be doing something differently than the implementors expected?

**Comment by hegemonic** [comment]
@netpoetica JSDoc 3.3.x does not support ES2015. You'll need to use the development version of JSDoc for ES2015 support. JSDoc 3.4.0 will support ES2015.

**Comment by codecvlt** [comment]
Looks like static class variables are not supported with jsdoc 3.4.0-dev
e.g
export default class AClass {
  static someVar = 'something';
}

**Comment by yaycmyk** [comment]
@codecvlt They're still a stage 1 proposal, so I'd be surprised if any parsers supported it. https://github.com/jeffmo/es-class-static-properties-and-fields

**Comment by Aweary** [comment]
Looks like it has trouble parsing arrow functions used in React components.

```js
class SomeComponent extends React.Component {
  someMethod = () => {
   return false;
 }
}
```

It throws the `Unexpected token =` error. This format is a common alternative in to using `bind` everywhere when using ES6 in React.

**Comment by yaycmyk** [comment]
@Aweary Did you see my comment above? Related to the same thing, not supported in the current ES 2015 spec.

**Comment by flying-sheep** [comment]
@Aweary why would you do that? just leave out the “=” and the “=>” and presto

**Comment by yaycmyk** [comment]
@flying-sheep He's trying to autobind a member, which is supported in the stage 1 members proposal, but not in the current class spec.

**Comment by Aweary** [comment]
@yaycmyk correct, we use this instead of having to call `.bind(this)` all the time. That was just an example to demonstrate the syntax causing the problem. Thanks for the heads up.

**Comment by flying-sheep** [comment]
ah, sorry! i missed the part below the code.

**Comment by zandaqo** [comment]
Guys, detecting default parameters doesn't seem to work with method definitions in 3.4. That is, I can get default values in stand alone functions without documenting them, but not in class/object methods when I use the new method notation:
```javascript
class A {
  /**
   * @param {number} [a] Some number.
   */
  getA(a = 1) {
    return a;
  }
}
```

Docs generated for the above do not show `1` as the default value for `a` param.

**Comment by r24y** [comment]
The [changelog](https://github.com/jsdoc3/jsdoc/blob/master/CHANGES.md#340-november-2015) seems to imply that I ought to be able to run JSDoc 3.4.0 on code that uses native modules, yet I'm still getting the error:

```
/.../node_modules/jsdoc-jsx/node_modules/jstransform/src/jstransform.js:270
    throw e;
    ^

Error: Parse Error: Line 1: Illegal import declaration
    at throwError ...
```

It failed on the JSX as well, which to my understanding was also resolved. I'm willing to use the `jsdoc-jsx` plugin for now to resolve that, but I can't seem to get past the modules issue.

Is there a discrepancy between what was published to npm and what's in this repo for 3.4.0? That's the only thing I can think of that would cause this issue.

**Comment by Reinmar** [comment]
I've spent some time in order to understand how JSDoc handles ES6 modules. I pushed results of my tests to https://github.com/ckeditor/ckeditor5-design/tree/jsdoc-module-test

There are couple of [modules](https://github.com/ckeditor/ckeditor5-design/tree/jsdoc-module-test/ckeditor5) which I tried to document.

First of all, due to #1337 I had to trick JSDoc to get anything work: https://github.com/ckeditor/ckeditor5-design/blob/jsdoc-module-test/jsdoc/plugins/export-fix.js

After I got rid of `export default` and `export class` classes started to work. However, there was still a problem with `export default function` which I had to change to `export function`. In other words, default exports do not work at all.

The result is also a bit confusing, because since default exports don't work, you get links like: `module:ckeditor5/a~A` instead `module:ckeditor5/a~default`. Perhaps this is the expected result that exports are documented under their internal names (because the same happens in [this case](https://github.com/ckeditor/ckeditor5-design/blob/jsdoc-module-test/ckeditor5/e.js)), but it's problematic for us, because the readers of the documentation will not know how to import the right class. We'd need to somehow let readers know that in case of default exports they'll need to do this:

```js
import A from 'ckeditor5/a';
````

instead of:

```js
import { A } from 'ckeditor5/a';
```

Right now, JSDoc gives no clue whether an export was the default or not.

Another thing which I don't get is the [linking to the exported things](https://github.com/ckeditor/ckeditor5-design/blob/jsdoc-module-test/ckeditor5/linking.js). With classes I must use `~` and with other things I must use `.` as a separator. I wasn't able to find a clarification for that in JSDoc's documentation.

**Comment by hyperbrave** [comment]
es6 exports are working in my case, but the generated docs are showing node require syntax instead of import

```javascript
(require("my/thing"))(options)
```

whereas I want it to generate using import statements

```javascript
import thing from "my/module"
thing(options)
```

is this possible?

**Comment by flying-sheep** [comment]
that's *only* possible with `export default`

other exports need the brace syntax:

```js
export function thing() { ... }
```

```js
import {thing} from 'my/thing'
```

**Comment by deltreey** [comment]
I'd like to note that backticks are working in master now, so work on this is helping me!

**Comment by withinboredom** [comment]
FYI, async/await have come out from behind the `--harmony` flag in node 7.7.1: http://node.green/#ES2017-features-async-functions

**Comment by damianobarbati** [comment]
Is JSDoc compatible with ES6/ES7 or not?
Or better: is JSDOC compatible just with old aged sh***y JS or not?

```
macbook:mvp damiano$ ./node_modules/jsdoc/jsdoc.js -a api/*
ERROR: Unable to parse /Users/damiano/Desktop/mvp/api/crud.js: Unexpected token =>
```

Because it's kinda ridiculous nowadays finding tools not working with current JS specs.

We had ES6 around for 2 years by now and ES7 arrived as well with node/chrome/safari/edge shipping async/await: and here we're still having troubles with arrow functions?

Keep up the good work guys.

**Comment by dancoates** [comment]
@damianobarbati take it easy there. No one is being paid to maintain this and you aren't paying to use it so please try and be more constructive with your criticisms.

If you are having trouble with ES2016+ and jsdoc then you have a few options.

- Transpile your code before running it through jsdoc
- Use the [`jsdoc-babel`](https://github.com/ctumolosus/jsdoc-babel) plugin
- [Contribute](https://github.com/jsdoc3/jsdoc/blob/master/CONTRIBUTING.md) changes/fixes to jsdoc to improve its ES2016+ support.

That said, I do believe that arrow functions should work with jsdoc, so you may be using an out of date version?

**Comment by damianobarbati** [comment]
@dancoates you are totally right, my apologies: too much frustration.

Arrow functions are working right, problem is async/await not supported
For whoever is having same problem, here the current solution:
```
    "plugins": [
        "node_modules/jsdoc-strip-async-await"
    ],

```

Best,
D

**Comment by dancoates** [comment]
@damianobarbati no problemos 🙂

Not sure if you are already using babel but if so you may find that using jsdoc-babel is a more all-purpose solution as it will run your code through the same set of transforms that are specified in your `.babelrc` before the code is consumed by jsdoc so in theory would work for any other new features like static class properties that you may want to use.

**Comment by damianobarbati** [comment]
@dancoates I'm using JSDoc to document my APIs for front-end developers who are going to consume them: just latest Node, no transpiling there :)

I'll keep this in mind once I'll start documenting components, thanks!

**Comment by hegemonic** [comment]
We now support any syntax that [Babylon](https://github.com/babel/babylon) can parse (i.e., far beyond what's in ES2015).
