### ISSUE TITLE
template documentation?

### ISSUE THREAD

**Issue by tmcw** [jsdoc3/jsdoc#865]
I'm looking at building a template for JSDoc's output, but can't find any documentation that describes how templates work. Existing prior art like [react-jsdoc](https://github.com/nullobject/jsdoc-react) look like they preprocess javascript to make it work with JSDoc.

**Comment by tmcw** [comment]
Looks like some of the documentation is [here](https://github.com/jsdoc3/jsdoc/tree/master/templates) and some of the other documentation is [here](http://usejsdoc.org/about-configuring-jsdoc.html). it would be great to have one of the [related links](http://usejsdoc.org/about-configuring-jsdoc.html#related-links) link to github.

**Comment by hegemonic** [comment]
It's true, we have almost no documentation that tells you how to create a template. I filed jsdoc3/jsdoc3.github.com#97 against the docs, so I'm closing this issue.

In practice, most people start by forking the default template. (The `jsdoc-react` template is an exception.) However, the default template is somewhat brittle, lacks tests, and is difficult to modify.

If you'd like to start with something more reliable, I would encourage you to take a look at [Baseline](https://github.com/hegemonic/jsdoc-baseline), which will eventually become the new default template for JSDoc. I'm working on changes that will make the template fairly easy to customize without forking the whole thing. That feature should be in place within a month or so.
