### ISSUE TITLE
Include template by name

### ISSUE THREAD

**Issue by tmcw** [jsdoc3/jsdoc#867]
After figuring out that `haruki` is the way to get JSON after #866, running

    jsdoc index.js -t haruki

Will throw

    FATAL: Unable to load template: Cannot find module 'haruki/publish'

Requiring a full path to template files seems like a risk for publishing (npm install directories vary) and also just a lot to expect of a user (who knows where jsdoc is? `which jsdoc` will yield a symlink

The correct liner for me was

    jsdoc index.js -t /usr/local/lib/node_modules/jsdoc/templates/haruki -d console

But will not be that for everyone.

**Comment by hegemonic** [comment]
Relative paths are already allowed, which means `templates/haruki` works. (I believe JSDoc searches for the `-t` path relative to the directory where the JSDoc configuration file is located; then relative to the current working directory; and finally relative to the JSDoc directory. This probably isn't documented anywhere right now, so I filed jsdoc3/jsdoc3.github.com#94 against the docs.)

It's true that just `-t haruki` does not work. However, `-t templates/haruki` isn't too terrible, and I'd prefer not to gum up the template- and plugin-finding code with even more path-specific logic. For those reasons, I'm going to close this issue.
