### ISSUE TITLE
Allow modules with . in name

### ISSUE THREAD

**Issue by tmcw** [jsdoc3/jsdoc#868]
This is something that currently projects like jsdoc-react [are hacking into place](https://github.com/nullobject/jsdoc-react/blob/82cc27feb0353296c5f43bd2326381e01cb5e5c9/src/publish.js#L28) - if jsdom supported `.` in module names, it would be possible to document submodules that are exposed via require as `module.methodname`.

**Comment by hegemonic** [comment]
JSDoc already supports modules with `.` (and other punctuation) in their names. Just enclose the module name in quotes: `@module "a.module.with.periods"`. This is documented [here](http://usejsdoc.org/about-namepaths.html), although the information is a bit buried right now.
