### ISSUE TITLE
Variable and class with same name mean you can't view the class in the HTML docs

### ISSUE THREAD

**Issue by benatwork99** [jsdoc3/jsdoc#869]
Not sure if this is a usage problem or a bug.

If I have a class - say `Foo` - and then I have a variable with the same name, the HTML doc output shows the class but clicking that takes me to the variable definition.

I came across this using node.js - I have a module called `Foo`, I require the module with a reference variable called `Foo`, and then want to create an instance of `Foo` called `foo`. But this means the doc output is broken so I need to rename my reference to the class.

E.g.:

Foo.js
````javascript
/**
 * Foo class
 * @constructor
 * @this {Foo}
 */
var Foo = function(){};
````

app.js
````javascript
/** Foo class reference */
var Foo = null; // would be a require
/** Foo variable */
var foo = new Foo();
````

If I do a `jsdoc *.js` on this, I can't browse to the `Foo` class via the HTML page

**Comment by hegemonic** [comment]
I think the solution is to use a line comment, or a normal block comment (not a JSDoc-style block comment), on `var Foo` in `app.js`:

```js
/* Foo class reference */
var Foo = require('./Foo');
/** Foo variable */
var foo = new Foo();
```

Or, if you need to use a JSDoc-style comment for some reason, you can add an `@ignore` tag:

```js
/**
 * Foo class reference
 * @ignore
 */
var Foo = require('./Foo');
/** Foo variable */
var foo = new Foo();
```

You probably don't need a JSDoc-style comment on `var foo`, either, unless you need it to appear in your documentation for some reason.

I suspect this is more of a usage question than a bug, so if you have follow-up questions, I'd appreciate it if you could send them to the [jsdoc-users mailing list](http://groups.google.com/group/jsdoc-users). (But if you find bugs or have feature requests, please feel free to file new issues.) Thanks for your understanding!
