### ISSUE TITLE
Improvement: list of objects for @param

### ISSUE THREAD

**Issue by micky2be** [jsdoc3/jsdoc#870]
I'm a big fan of being able to describe an object with the following syntax.
```js
/**
 * Decorate a donut.
 * @param {RawDonut} donut - The raw donut to decorate.
 * @param {boolean} donut.needsSprinkles - Whether the donut needs sprinkles.
 * @param {boolean} donut.needsGlaze - Whether the donut needs glaze.
 * @return {Donut} The decorated donut.
 */
function decorateDonut(donut, options) {
    // ...
}
```

But when the argument is an array of objects it becomes really tricky to write the JSDOC of it.
And if possible I would love using a similar syntax than the previous example like for example the following:
```js
/**
 * Decorate donuts.
 * @param {RawDonut[]} donuts - List of raw donuts to decorate.
 * @param {boolean} donuts[].needsSprinkles - Whether the donut needs sprinkles.
 * @param {boolean} donuts[].needsGlaze - Whether the donut needs glaze.
 * @return {Donut[]} The decorated donuts.
 */
function decorateDonuts(donuts, options) {
    // ...
}
```

**Comment by hegemonic** [comment]
Ha, I thought I was the only one who always used food in my sample code!

I just tested your proposed syntax, and once I corrected the `donut[]` references to `donuts[]`, it seems to work fine already. For that reason, I'm closing this issue.

I just updated jsdoc3/jsdoc3.github.com#52 to note that we still need to document this syntax.

**Comment by micky2be** [comment]
I don't consider this working since it thinks `donuts[]` is the name of a parameter.
Which also clash with my IDE and my code checker (JSCS) since the argument doesn't exist.

![screen shot 2015-01-09 at 10 10 32](https://cloud.githubusercontent.com/assets/728644/5674048/c2c36c16-97e7-11e4-9b99-f1dd2d8851ff.png)

So sure it doesn't crash but the interpretation of it is incorrect.

**Comment by hegemonic** [comment]
Ah, I see what you're saying. Yes, we should collapse the properties into the `donuts[]` row of the table. Reopening.

**Comment by hegemonic** [comment]
Fixed on master.

**Comment by micky2be** [comment]
Great, thank you guys
