### ISSUE TITLE
Tests fail at "should fire all jsdocCommentFound events, in source order, then all symbolFound events, in source order"

### ISSUE THREAD

**Issue by Koyot** [jsdoc3/jsdoc#871]
After one of the changes made on the 19th of Dec the tests started to fail, particularly on "should fire all jsdocCommentFound events, in source order, then all symbolFound events, in source order", reports 4 failures. When I reset the repo to commit 1cb337c90a7914b6cbb8dbbc949632cce62ced4a, it works fine. It was done on ubuntu 11.10.

**Comment by hegemonic** [comment]
Ubuntu 11.10 was released in 2011, and its end-of-life date was in May 2013. The tests all pass on more recent versions of Ubuntu. For that reason, I'm going to close this issue.

If you can reproduce this issue on a current version of Ubuntu, please let me know, and I'll reopen the issue.
