### ISSUE TITLE
Navigation links to tutorials aren't included in output.

### ISSUE THREAD

**Issue by tswaters** [jsdoc3/jsdoc#875]
```sh
npm ls --depth 0 | grep jsdoc
├── jsdoc@3.3.0-alpha13
```

When generating documentation, links to tutorials are not included in the navigation.  It lists just the first one it finds, but doesn't create a link to it.

When publish is hit, tutorials are populated properly but because they don't have a 'longname', `seen[undefined]` is set to true and subsequent tutorials aren't included.  The reason it doesn't link is the `buildMemberNav` function tries to link to the long name (which again is undefined).  

I was able to fix it in my project with a custom template and a few tweaks to `publish.js`... I added a special `buildTutorialNav` which uses `name` and references the `tutoriallink` function.

```javascript
function buildTutorialNav(items, itemHeading, itemsSeen) {
    var nav = '';
    if (items.length) {
        var itemsNav = '';
        items.forEach(function(item) {
            if ( !hasOwnProp.call(itemsSeen, 'tutorial:' + item.name) ) {
                itemsNav += '<li>' + tutoriallink(item.name) + '</li>';
                itemsSeen['tutorial:' + item.name] = true;
            }
        });
        if (itemsNav !== '') {
            nav += '<h3>' + itemHeading + '</h3><ul>' + itemsNav + '</ul>';
        }
    }
    return nav;
}
```
I prefixed "tutorial:" to the name for use in the seen object -- I'm unsure if this is sufficient for avoiding collisions.  I knew for sure just passing name in there would've caused me trouble.

**Comment by hegemonic** [comment]
Thanks for reporting this issue and identifying a possible fix! Based on some hastily run tests, it appears that this has never worked at all in the default template. Yeesh.

**Comment by hegemonic** [comment]
Fixed on master.
