### ISSUE TITLE
Mention that Markdown is parsed in @file/@overview as well?

### ISSUE THREAD

**Issue by dandv** [jsdoc3/jsdoc#877]
First time using JSDoc. I see at http://usejsdoc.org/plugins-markdown.html that 

> This will cause Markdown in @description tags (including implicit descriptions without tags), @classdesc tags, @param tags, @property tags, and @returns tags to be parsed.

Practice shows that Markdown is parsed from @overview tags as well:

```
/**

@overview # Heading goes here

This module is the interface to the API. It provides access to objects, and formats
the response objects to a simple, linear model.
...
*/
```

Should @overview be added to the list of tags?

**Comment by hegemonic** [comment]
Thanks for pointing this out. The docs live in jsdoc3/jsdoc3.github.com, which is the right place to file doc issues. I've updated jsdoc3/jsdoc3.github.com#38 to get this cleaned up as well.
