### ISSUE TITLE
Pass @author through Markdown

### ISSUE THREAD

**Issue by dandv** [jsdoc3/jsdoc#878]
I'd like to link to my GitHub profile from the @author tag:

    @author Dan Dascalescu, [@dandv](http://github.com/dandv)

**Comment by hegemonic** [comment]
Sure, this is an easy change, and I don't anticipate it causing problems (although I've been wrong before...).

For now, you can do this by adding a setting to your JSDoc configuration file. See [these instructions](http://usejsdoc.org/plugins-markdown.html#extended-tag-support).

**Comment by hegemonic** [comment]
Fixed on master.
