### ISSUE TITLE
adding @memberof to a class causes class members to disappear from docs

### ISSUE THREAD

**Issue by 75lb** [jsdoc3/jsdoc#880]
buona sera! i'm seeing this issue on the master branch.. if i generate docs for this class (filename `earth.js`), all is well:

```js
/**
@class
*/
function Earth(){}

/**
are rivers present
*/
Earth.prototype.rivers = function(){};

/**
are trees nearby
*/
Earth.trees = true;
```

but if i create a separate file (`something.js`) with this module:
```js
/**
@module something
*/

/**
a property
*/
exports.thing = "something";
```

...then make my Earth class a @memberof this module:
```js
/**
@class
@inner
@memberof module:something
*/
function Earth(){}

/**
are rivers present
*/
Earth.prototype.rivers = function(){};

/**
are trees nearby
*/
Earth.trees = true;
```
things go a bit wrong.. when i generate now (with `$ jsdoc earth.js something.js`), on the docs page for `something~Earth` the members of the Earth class have disappeared (the `rivers` and `trees` members are not displayed).. 

here is the output from `$ jsdoc -X tmp/earth.js tmp/something.js`:
https://gist.github.com/75lb/7fd6ab4693c7c4059ef1

**Comment by hegemonic** [comment]
Thanks for reporting this issue!

Strangely, if you put your second and third examples into a single file, everything works just fine. I'll investigate.

**Comment by hegemonic** [comment]
Another workaround is to use the `@alias` tag in `earth.js`:

```js
/**
@class
@inner
@memberof module:something
*/
function Earth(){}

/**
are rivers present
@alias module:something~Earth#rivers
*/
Earth.prototype.rivers = function(){};

/**
are trees nearby
@alias module:something~Earth.trees
*/
Earth.trees = true;
```

But that shouldn't be necessary...

**Comment by 75lb** [comment]
yeah, that’s the workaround i’m using in my ‘real’ app.. was pleased to find this temp solution - will keep me going..

**Comment by hegemonic** [comment]
Fixed on master.

**Comment by hegemonic** [comment]
Added the missing test fixture in 16b8aa0a73f70933814aadef66bf8ec369ae3273.
