### ISSUE TITLE
Question: Subclasses and Plugins

### ISSUE THREAD

**Issue by janpaepke** [jsdoc3/jsdoc#881]
Hi there,

I have been using JSDoc for my plugin [ScrollMagic](http://janpaepke.github.io/ScrollMagic/docs/index.html) for a while now and am loving it.
The [upcoming version](https://github.com/janpaepke/ScrollMagic/tree/development) has some architectural changes that I am having a very hard time to reflect in JSDoc though.
So I'm hoping you can shed some light on how to properly implement this.

#### 1. Subclasses
In the current version ScrollMagic exports two classes: `ScrollMagic` and `ScrollScene`.
To make it more coherent with requirejs (one export per file) and other reasons this will be changed to one object, containing two classes: `ScrollMagic.Controller` and `ScrollMagic.Scene`.
Their constructor will respectively be `new ScrollMagic.Controller()` and `new ScrollMagic.Scene()`.
The `ScrollMagic` object is basically just a holder for the two classes.

Now I tried documenting it like this:
```js
/**
@class
*/
ScrollMagic.Controller = function(options) {
    //... methods ...
}
```
But in the exports it only ever shows "Controller" never "ScrollMagic.Controller".
Now that's actually not a big deal for the menu and headlines, because it makes them more readable.
The constructor however needs to be shown correctly, but it also exported as `new Controller()`.
I tried defining it as `@class ScrollMagic.Controller`, but that also exports just as `Controller` with the added problem that all associated methods disappear.

__How should I approach this the correct way?__

#### 2. Plugins
ScrollMagic 2.0 introduces plugins, that extend the prototypes of one of the above classes.
They basically add new methods to them.
Now I wouldn't want these methods to be exported into the same list as the core methods.
Instead I would love to have an extra main menu point, listing the plugins.
Then upon clicking it would show me which class they extend and list the methods in the regular fashion.

Example: Plugin X adds method a() and b() to the ScrollMagic.Scene prototype.
In the Menu "Plugins" I find a link for "X".
When opening "X" I see that "X" extends "ScrollMagic.Scene" and has two methods: "a()" and "b()".

The closest I have gotten to that was using the `@mixins` option: `@mixin Scene.X` and defining the methods using `@memberof Scene.X`.
My thought was to simply overwrite the wording of mixins (as I don't have any) to "Plugins" in the template.

There are three issues with this approach though:
- it shows the methods as being 'static' while they are not. They are methods for ScrollMagic.Scene instances.
- Identification (and thus proper linking inside of the page) only works, if Scene is not defined using `ScrollMagic.Scene`, as described above
- The whole workaround feels very hacky and wrong, since I don't hink this is what mixins where planned to be used for.

I was thinking there should be some sort of `@plugin` tag, for this case, but maybe I'm missing something.
So again my question would be:
__How to approach this the right way?__

thank you for your help and amazing piece of software.

regards,
J

**Comment by hegemonic** [comment]
Thanks, @janpaepke--I'm glad that you've enjoyed using JSDoc!

I'd prefer to keep "how do I do this" questions on the [jsdoc-users mailing list](https://groups.google.com/forum/#!forum/jsdoc-users). Can you please repost this question to the mailing list? I'll answer as promptly as I can.

**Comment by hegemonic** [comment]
Oops, @janpaepke to make sure you get this.

**Comment by janpaepke** [comment]
sure. done. thanks. :)
