### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by cd** [jsdoc3/jsdoc#882]
How do i document this correctly? JSDoc cancels after the foo function.
```
/**
 * Superior foo function
 * @param {object} args Arguments...
 */
function foo(args) { }

/**
 * bar function
 * @param {object} args Arguments...
 */
foo.prototype.bar = function(args) { }
```

**Comment by hegemonic** [comment]
You need to add a `@class` tag to `foo`.

(In the future, please post questions to the [jsdoc-users mailing list](http://groups.google.com/group/jsdoc-users). The GitHub issue tracker is for bug reports and feature requests. Thanks!)
