### ISSUE TITLE
Removing Tutorials from the Nav bar

### ISSUE THREAD

**Issue by rdepena** [jsdoc3/jsdoc#886]
Hey, I am using the Tutorials feature and I like it but I do not want the tutorials to appear on the nav bar, is there an option I can pass in to get this behavior ?

btw I looked at http://usejsdoc.org/about-tutorials.html and there is no info on removing them from the nav bar.

**Comment by hegemonic** [comment]
You'll need to modify the JSDoc template to remove the tutorials from the navbar. There's no option to control this behavior.

(In the future, please post "how do I do this" questions to the [jsdoc-users mailing list](https://groups.google.com/forum/#!forum/jsdoc-users). Thanks!)

**Comment by rdepena** [comment]
awesome, thank you.
