### ISSUE TITLE
parameters missing in functions

### ISSUE THREAD

**Issue by scottnath** [jsdoc3/jsdoc#905]
Hi all,

I'm trying to use jsdocs to add docblocks to my gulp task files, but my parameters are not showing up unless I use `@class` which is incorrect for gulp tasks. I have tried using '@module', '@function' (which I think is correct) and '@method'. For all of those, the parameters I set don't show up.

Here is an example of the docs that were output:
http://scottnath.github.io/jsdoc-test

An example file:
```
/**
 *  @fileOverview Uses Gulpjs to trigger browser-sync
 *
 *  @author       Scott Nath
 *
 *  @requires     NPM:gulp
 *  @requires     NPM:browser-sync
 *  @requires     /gulp/config.js
 */
'use strict';
var gulp        = require('gulp');
var browsersync = require('browser-sync');
var config      = require('../../config');

/**
 * Gulp task that triggers browser-sync
 * @method browsersync
 *
 * @param   config.browsersync.development development configuration
 *
 */
gulp.task('browsersync', function() {
  browsersync.init(null, config.browsersync.development, function (err, bs) {
    console.log('Started connect web server on ' + config.browsersync.development.host + ':' + config.browsersync.development.port);
  });;
});

gulp.task('browsersync-reload', function(){
  browsersync.reload();
});
```

This file can be found here:
https://github.com/scottnath/jsdoc-test/blob/master/gulp/tasks/development/angular-templatecache.js

and there's a bunch more in the containing folders.

Would love any advice or changes that anyone has to help me properly document these files and have docs created via jsdoc.

thanks,
Scott

**Comment by hegemonic** [comment]
Can you please repost this question to the [jsdoc-users mailing list](https://groups.google.com/forum/#!forum/jsdoc-users)? The issue tracker is for bug reports and feature requests.

Thanks!

**Comment by scottnath** [comment]
Thank you @hegemonic . Looks like my post to jsdoc-users is awaiting approval.

Curious though...aren't functions supposed to show the parameters attached to them?
If they are, wouldn't this be a bug?

thanks,
Scott
