### ISSUE TITLE
method appears twice

### ISSUE THREAD

**Issue by myphysicslab** [jsdoc3/jsdoc#907]
Method appears twice in documentation in a situation involving 2 interfaces and 2 classes using @inheritDoc.  This is probably related to [issue 906: @inheritdoc fails when class C extends class B which implements interface A](https://github.com/jsdoc3/jsdoc/issues/906).

In the example code below:

* SimObject is an interface
* PhysicsObject is an interface that extends SimObject
* AbstractSimObject is a class that implements SimObject
* PhysicsPoint is a class that extends AbstractSimObject, and also implements PhysicsObject

The problem is that the **getName** method in PhysicsPoint appears twice:  once with documentation (seems to be from the "implements PhysicsObject" tag) and once without documentation (seems to be from the "extends AbstractSimObject" tag).

The resulting documentation can be seen at:
http://www.myphysicslab.com/rmnp/test20150204b/out/index.html
Below is the code for this example. Also available at 
http://www.myphysicslab.com/rmnp/test20150204b/test20150204b.js
Using JSDoc 3.4.0-dev (Thu, 22 Jan 2015 23:02:06 GMT)

```javascript
/** @classdesc An object in the simulation which could be displayed.
* @interface
*/
myphysicslab.lab.model.SimObject = function() {};

/** Identifier for this {SimObject}.
@method
@return {string} a string identifier for this {SimObject}
*/
myphysicslab.lab.model.SimObject.prototype.getName;

/** @classdesc An object used in a physics simulation that has mass, position, velocity.
* @interface
* @extends {myphysicslab.lab.model.SimObject}
*/
myphysicslab.lab.model.PhysicsObject = function() {};

/** Returns the mass of this object, or NaN if this object can never have mass
@method
@return {number} the mass of this object, or NaN if this object can never have mass
*/
myphysicslab.lab.model.PhysicsObject.prototype.getMass;

/** @classdesc Base class that provides common methods for {SimObject}s.
* @param {string=} name
* @constructor
* @implements {myphysicslab.lab.model.SimObject}
*/
myphysicslab.lab.model.AbstractSimObject = function(name) {
  /**
  * @type {string}
  * @private
  */
  this.name_ = name || "";
};

/** @inheritDoc */
myphysicslab.lab.model.AbstractSimObject.prototype.getName = function() {
  return this.name_;
};

/** @classdesc Represents a point in space.
* @param {string} name
* @param {number=} mass  default is 0
* @constructor
* @extends {myphysicslab.lab.model.AbstractSimObject}
* @implements {myphysicslab.lab.model.PhysicsObject}
*/
myphysicslab.lab.model.PhysicsPoint = function(name, mass) {
  myphysicslab.lab.model.AbstractSimObject.call(this, name);
  /**
  * @type {number}
  * @private
  */
  this.mass_ = mass || 0;
};

/** @inheritDoc */
myphysicslab.lab.model.PhysicsPoint.prototype.getMass = function() {
  return this.mass_;
};

/** Sets location of center of mass of this PhysicsPoint (optional operation).
@param {number} x_world the x location in world coords
@param {number} y_world the y location in world coords
*/
myphysicslab.lab.model.PhysicsPoint.prototype.setPosition = function(x_world, y_world) {};
```

**Comment by hegemonic** [comment]
I can't reproduce this after fixing #906, so I think your theory was correct.

If you're still seeing this issue, or some variant of it, please let me know so I can reopen this issue.
