### ISSUE TITLE
Prevent footer date from being updated at every change

### ISSUE THREAD

**Issue by jviotti** [jsdoc3/jsdoc#910]
When regenerating my project's documentation, the footer of every file (even the ones I didn't modify the source file) gets the date updated, causing a lot of noise in the commits:

```diff
<footer>
-    Documentation generated by <a href="https://github.com/jsdoc3/jsdoc">JSDoc 3.3.0-alpha5</a> on Tue Jan 13 2015 08:54:20 GMT-0300 (ART)
+    Documentation generated by <a href="https://github.com/jsdoc3/jsdoc">JSDoc 3.3.0-alpha5</a> on Mon Jan 26 2015 10:36:41 GMT-0400 (BOT)
 </footer>
```
Is there a way to disable this feature?

**Comment by hegemonic** [comment]
There's currently no way to disable this feature. I'd accept a pull request to add a config setting for this. I'd suggest adding a `templates.default.includeDate` setting to JSDoc's config file; we should include the date unless this setting is defined and set to `false`.

**Comment by jviotti** [comment]
@hegemonic I'm working on a PR for this issue. 

I have it working with the following approach:

- Add `includeDate` to the `defaults` object at `lib/jsdoc/config.js`.
- Implement a conditional around the date at `templates/default/tmpl/layout.tmpl`, checking for the previously defined config option through `env.conf.templates`.

I was looking forward to add some unit testing for this, but I'm not sure if you're actually testing the output of the compiled templates.

I did include a unit test clause to check that the value of `includeDate` defaults to true.

Should I update the documentation somewhere to include information about the new option before sending the PR?

**Comment by hegemonic** [comment]
@jviotti Thanks for working on a pull request! I look forward to seeing it.

> + Add `includeDate` to the `defaults` object at `lib/jsdoc/config.js`.

You can skip this. The `defaults` object shouldn't need to know about template-specific config settings.

+ I was looking forward to add some unit testing for this, but I'm not sure if you're actually testing the output of the compiled templates.

Unfortunately, the default template has no tests. :/

+ I did include a unit test clause to check that the value of `includeDate` defaults to true.

You can skip this too.

+ Should I update the documentation somewhere to include information about the new option before sending the PR?

If you could file a new issue at [jsdoc3/jsdoc3.github.com][https://github.com/jsdoc3/jsdoc3.github.com/issues], I'd appreciate it. Thanks for asking about this!

**Comment by jviotti** [comment]
@hegemonic Made the changes you requested and sent the PR (https://github.com/jsdoc3/jsdoc/pull/916). I'll open an issue for the documentation once the PR gets merged.

**Comment by hegemonic** [comment]
@jviotti Merged! If you could open an issue for the docs, I'd appreciate it.

**Comment by jviotti** [comment]
@hegemonic Great, opened https://github.com/jsdoc3/jsdoc3.github.com/issues/103, thanks for the support!
