### ISSUE TITLE
CoffeeScript compiler support

### ISSUE THREAD

**Issue by Soviut** [jsdoc3/jsdoc#915]
I've got a project written in CoffeeScript that I'd like to document. I'd like to avoid pre-compiling with gulp or grunt in this case since it's server-side and doesn't require any build steps currently. Mocha and Node itself both have options to target alternative compilers, for example:

```
mocha --compilers coffee:coffee-script/register
```

It'd be great if JSDoc supported this as well.

**Comment by hegemonic** [comment]
Right now there's a ton of code in JSDoc that assumes it's parsing JavaScript, not a compile-to-JavaScript language, so it would take a ton of work to support CoffeeScript natively. The same goes for TypeScript and any other compile-to-JS language.

I'd like to be able to support this someday, but it's unlikely to happen anytime soon.

**Comment by Soviut** [comment]
As I understand it, Mocha and others that use the `--compiler` flag are transpiling on the fly so there's no language-specific stuff to do. As long as the comments survive I'd imagine JSDoc should be able to handle it. I'm going to do a little research into how Mocha does it to see how easy it might be to build a PR.

**Comment by hegemonic** [comment]
Ah, so you want JSDoc to transpile code, using the compiler of your choice, and then parse the generated JS code. That sounds more feasible.

Before you spend time on this, I'd suggest that you add some JSDoc comments to a few CoffeeScript files; compile the files to JS; and verify that JSDoc can make sense of the output. It would be a shame to spend time on this, only to discover that the CoffeeScript compiler generates code that JSDoc can't understand.

**Comment by Soviut** [comment]
I've done some tests with it on pre-compiled coffeescript and it seems to work fine. The only downside is how ugly the comment blocks wind up looking in coffeescript.

```coffeescript
###*
 * @param
 *
###
```

Other projects already do some of the precompilation and typically allow for these styles:
```coffeescript
###
# @param
#
###
```
or
```coffeescript
##
# @param
#
```
Personally, I've always wished comment blocks could just be prefixed with their doc target, like markdown code blocks.
```javascript
/* jsdoc
    @param whatever
*/
```

**Comment by japboy** [comment]
:+1:

**Comment by zixia** [comment]
use `--compilers coffee:coffee-script/register` is a good idea. TypeScript also can be supported by this method to avoid pre-compiling.

:+1:

**Comment by hegemonic** [comment]
I think the right way to support this is to write a plugin that preprocesses the CoffeeScript source code before JSDoc sees it, similar to [jsdoc-babel](https://github.com/ctumolosus/jsdoc-babel). Also, I don't want JSDoc to take a dependency on CoffeeScript just to support a CoffeeScript-to-JavaScript plugin.

For those reasons, I'm closing this issue.
