### ISSUE TITLE
Enhancement: Show callback and type definitions on the navigation bar

### ISSUE THREAD

**Issue by n-riesco** [jsdoc3/jsdoc#918]
Neither callbacks nor type definitions are listed on the navigation bar. (using JSDoc 3.3.0-beta1).

**Comment by hegemonic** [comment]
I'd prefer not to add these to the navbar, because I think that would just create extra noise for large codebases.

You should be able to add these to the navbar for your project by modifying the default template.

**Comment by n-riesco** [comment]
Thank you for the lead on modifying the template.

About the noise argument, I would argue that it depends on the nature of the project rather than the size. To document an API, callback and type definitions are really important.
