### ISSUE TITLE
How to document getters & setters?

### ISSUE THREAD

**Issue by rayshan** [jsdoc3/jsdoc#925]
Let's say we have a non-standard way of defining getters & setters:

```js
    data: {
        get: function () {return this._data},
        set: function (data) {
            if (data !== this._data) {
                this._data = data;
                // some other custom logic
            }
        }
    }
```

Above gets parsed & added to `data` property's getters & setters. Should we document it as `@property {Object[]}` or `@param {Object[]} data` and `@returns {Object[]}`? What's the best practice to document any custom logic upon getting & setting?

**Comment by hegemonic** [comment]
Please send this question to the [jsdoc-users mailing list](https://groups.google.com/forum/#!forum/jsdoc-users). The issue tracker is for bug reports and feature requests.

Thanks!

**Comment by rayshan** [comment]
Sorry. Thanks!
