### ISSUE TITLE
Problem with npm 2.5.1 and jsdoc not using semver

### ISSUE THREAD

**Issue by sateffen** [jsdoc3/jsdoc#926]
Heyho,

I'm using jsdoc in multiple projects, and developed with nodejs 0.10 and npm 1.4.14 . In this versions I had my dependency set to:

    "jsdoc": "^3.3.0"

which worked perfectly, but now I updated to nodejs 0.12 and npm 2.5.1 and this doesn't work anymore.

npm tells me there is no compatible version found, which is correct in that way, that the versioning is not semver like.

The only way is to install a specific version (like 3.3.0-beta1), but not use the cool features of npm.

Is there a plan to skip this (horrible) versioning with alpha and beta releases, and commit fully to semver, to make this work?

I think a lot of people will run in this trouble, because it's common to use npm versioning helpers for most recent versions. (Not even ~ works, non of the npm comperators work I guess)

Any thoughts?

**Comment by hegemonic** [comment]
As stated in the README, you can use `jsdoc@"<=3.3.0"` to pick up the latest alpha/beta release.

I don't intend to continue with alpha/beta releases in the future. That was a stopgap to deal with the fact that 3.3.0 was a huge project that's taken literally years to complete, and people wanted a way to install reasonably recent bits from NPM, even if they were unstable.

Sorry, but I have no plans to move to strict semver. For the time being, JSDoc will continue to use traditional major/minor/bugfix versioning.
