### ISSUE TITLE
JSDOC to provide feature to automatically create javadoc for all files inside parent folder or subfolder

### ISSUE THREAD

**Issue by rajeevszone** [jsdoc3/jsdoc#927]
JSDOC to provide feature to automatically create javadoc for all files inside parent folder or subfolder.
so if structure is:
ParentFolder
---a1.js
   - SubFolder
   -----b1.js
  ------b2.js
So, jsdoc ParentFolder/  to generate javadocs for all js files within this directory.

**Comment by hegemonic** [comment]
This feature already exists. Use the `-r` command-line option.
