### ISSUE TITLE
Too simple output for @return with object structure

### ISSUE THREAD

**Issue by BlackWolf** [jsdoc3/jsdoc#931]
When using the object structure syntax for `@return`, the output generated by JSDoc is much too simplified to be really useful for the reader.

This comment:

```
/**
 * Some method that returns a point
 * @return {{x: Number, y: Number}} The generated point
 */
```

will generate an output like:

```
Returns:
    The generated point
    Type: Object
```

While this parses successfully and is technically correct, obviously if I state the exact structure of the return in my documentation that is important for the documentation reader and should therefore be present in the output. The same is true for parameters, by the way.

**Comment by hegemonic** [comment]
It's true, we currently discard most of the type info for Closure Compiler-style objects. You can use the [`@typedef` tag](http://usejsdoc.org/tags-typedef.html) to document the object, but I can understand why you wouldn't want to go that route for simple cases like this one.

**Comment by hegemonic** [comment]
I just remembered that #636 already covers this, so I'm closing this issue as a duplicate.
