### ISSUE TITLE
subparams only displayed for first param

### ISSUE THREAD

**Issue by Marshallx** [jsdoc3/jsdoc#940]
/**
 * @method
 * @description Display message
 * @param {string} [msg] The message to display.
 * @param {object} options Additional options.
 * @param {boolean} options.bold Make the message bold.
 */

The subparams of the options object are not displayed.

If I remove the `msg` param such that `options` is the first param, then the subparams of options are displayed ok.

**Comment by hegemonic** [comment]
Duplicate of #901, which is fixed on master. The fix will be included in JSDoc 3.3.0.
