### ISSUE TITLE
No output from JSDoc

### ISSUE THREAD

**Issue by cibulka** [jsdoc3/jsdoc#941]
Hello!

I have yet another problem with JSDoc generating absolutely no documentation - both with Grunt plugin (`npm install grunt-jsdoc`) and with JSDoc installed globally (`npm install jsdoc@"<=3.3.0" -g`). None of my files or folders start with underscore.

I also receive some more errors with particular commands:

`jsdoc --test` => `js: Couldn't read source file "test/runner.js: test/runner.js (No such file or directory)".

`jsdoc test.js --debug` => `js: "/Users/Cibulka/.node/lib/node_modules/jsdoc/jsdoc.js", line 316: exception from uncaught JavaScript throw: Error: Unknown command line option found: debug

`jsdoc --debug` => Hangs indefinetely with preceeding `Running debug`

For some time, even basic command `jsdoc test.js` screamed `No input files for proccess` at me. This went away.

My test.js to document (taken straight from JSDoc3 documentation page):

```
/**
 * Represents a book.
 * @constructor
 * @param {string} title - The title of the book.
 * @param {string} author - The author of the book.
 */
function Book(title, author) {
}
```
I am relatively new with Javascript and absolute newbie with JSDoc, so maybe I just don't get something. Thanks in advance.

**Comment by cibulka** [comment]
Also,

`jsdoc test.js --verbose` => Prints nothing to console and still generates empty output.

`jsdoc --version` => `JSDoc 3.2.2`

`jsdoc test.js --explain` =>

```
[
    {
        "files": [],
        "kind": "package",
        "name": "undefined",
        "longname": "package:undefined",
        "description": "undefined",
        "version": "undefined",
        "licenses": "undefined"
    }
]
```

Screenshot of empty output:

![screen shot 2015-03-08 at 9 58 48 am](https://cloud.githubusercontent.com/assets/3989833/6545183/c94845f6-c579-11e4-919a-4ee1d4a7b215.png)

**Comment by cibulka** [comment]
And since you asked for a shell version on a similiar thread, here you go:

`sh --version` => `GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin14)`

I work on my Macbook Pro with Yosemite 10.10.2, if that helps.

**Comment by hegemonic** [comment]
@cibulka Would you mind trying the current beta version of JSDoc 3.3.0 instead? JSDoc 3.2.2 is the latest stable version, but it's very old at this point.

I'm not sure why `npm install jsdoc@"<=3.3.0"` is giving you 3.2.2; it ought to give you 3.3.0-beta2 as of right this second.

**Comment by cibulka** [comment]
Sure thing, will do that tomorrow morning! Thanks for the reply.

**Comment by cibulka** [comment]
I use JSDoc with https://github.com/krampstudio/grunt-jsdoc and I just noticed its `package.json` points to JSDoc 3.2.2 version. As they made the latest commit to the repo about a week ago, one would think that the plugin is up to date!

I'm not sure how to change and install dependencies of the package manually - tried to edit package.json and then `npm grunt-jsdoc install`, but `package.json` just got overwritten back (which makes sense) - so I'm trying native `jsdoc` instead.

However I still must be doing something wrong: 

- `jsdoc /path/to/file.js` > There are no input files to process.
- `jsdoc /path/to/file.js --debug` >
```
DEBUG: Environment info: {"env":{"conf":{"tags":{"allowUnknownTags":true,"dictionaries":["jsdoc","closure"]},"templates":{"monospaceLinks":false,"cleverLinks":false,"default":{"outputSourceFiles":true}},"source":{"includePattern":".+\\.js(doc)?$","excludePattern":"(^|\\/|\\\\)_"},"plugins":[]},"opts":{"_":["/Users/Cibulka/Documents/_00-Web-WP/tvar.dev/web/app/themes/tvar-wp-theme/assets/js/dev/wp.js"],"debug":true,"destination":"./out/","encoding":"utf8"}}}
There are no input files to process.
```

- `jsdoc /path/to/file.js --explain` > There are no input files to process.
- `jsdoc --version` > JSDoc 3.3.0-beta2

**Comment by cibulka** [comment]
I must really be doing something wrong - when I followed the grunt-jsdoc's instruction to install the plugin with `npm install --save-dev grunt-jsdoc@beta`, now it generates an empty folder. Relevant part of `Gruntfile.js`:

```
		jsdoc: {
			
			child: {
				src: ['assets/js/dev/*.js'],
				dest: docsFolder + '/js/jsdoc',
				options: {
					recurse: true,
					verbose: true
				}
			},
			
		},
```

`Yuidoc` with similar configuration seems to work fine (so I guess document my "parsibly").

**Comment by hegemonic** [comment]
I can't imagine what's going on here. Based on the `--debug` output, it's clear that JSDoc is finding the file `wp.js`.

Do you have another machine that you can try this on?

**Comment by cibulka** [comment]
Not at the moment ... Is it possible that I just do the documentation itself wrong, so JSDoc can't find anything to parse? But as I said before, YUIDoc seem to work fine...

**Comment by hegemonic** [comment]
Okay, I see what's happening here. By default, JSDoc ignores files and directories that start with an underscore. One of the parent directories for `wp.js` starts with an underscore. As a result, JSDoc is skipping that file, leaving it with no files to process.

You can fix this by either a) moving the file or b) setting `source.excludePattern` to `""` in your JSDoc config file. See the [instructions for configuring JSDoc](http://usejsdoc.org/about-configuring-jsdoc.html) if you need more info. (Sorry, but I'm not sure how configuration works with the Grunt plugin.)

**Comment by cibulka** [comment]
Of course! 

I've already saw that JSDoc excludes paths with underscores and I specifically checked my configuration for that - but I totally forgot that there is one in the base folder. Sorry for taking your time with a problem that is already well documented and thank you!

**Comment by hegemonic** [comment]
That feature would be very useful, I agree, but it would require drastic changes to the way that JSDoc filters source files. (The problem is that some users _want_ to filter based on the fully resolved path.) You're right, though, the behavior is confusing in this particular, fairly common case.

**Comment by cibulka** [comment]
I see. And it's still possible to alter the behaviour with `source.excludePattern`, so it makes sense to leave things as they are. Thank you for your work!

**Comment by alireza-saberi** [comment]
I used singe command line of ` node_modules/jsdoc/jsdoc.js js/script.js --debug` of a single file of script.js and I get an empty description file. Could anybody help me with that please based on the following debug?

 
```
node_modules/jsdoc/jsdoc.js js/script.js --debug
DEBUG: JSDoc 3.4.2 (Mon, 03 Oct 2016 18:14:32 GMT)
DEBUG: Environment info: {"env":{"conf":{"tags":{"allowUnknownTags":true,"dictionaries":["jsdoc","closure"]},"templates":{"monospaceLinks":false,"cleverLinks":false,                         "default":{"outputSourceFiles":true}},"source":{"includePattern":".+\\.js(doc|x)?$","excludePattern":"(^|\\/|\\\\)_"},"plugins":[]},"opts":{"_":["js/script.js"],"deb                         ug":true,"destination":"./out/","encoding":"utf8"}}}
DEBUG: Parsing source files: ["C:\\Users\\Ali\\practice\\armin\\form-auto-complete-javascript\\js\\script.js"]
Parsing C:\Users\Ali\practice\armin\form-auto-complete-javascript\js\script.js ...
DEBUG: Finished parsing source files.
DEBUG: Indexing doclets...
DEBUG: Adding inherited symbols, mixins, and interface implementations...
DEBUG: Adding borrowed doclets...
DEBUG: Post-processing complete.
Generating output files...
Finished running in 3.33 seconds.
```


/cc @hegemonic
