### ISSUE TITLE
Rhino support?

### ISSUE THREAD

**Issue by tmcw** [jsdoc3/jsdoc#942]
It's not clear what the intent of JSDoc's Rhino compatibility is, especially when it requires a custom build. Is this legacy code, or is there a usecase I'm missing here?

**Comment by hegemonic** [comment]
We support Rhino for a few reasons:

1. In the past, we required Rhino.
2. For some users, it may be more convenient to run JSDoc on the JDK. (I have no idea whether this is true, or how many users would prefer the JDK over Node.js.)

At some point, I plan to survey the community and find out how many people, if any, rely upon Rhino support. If nobody needs it, I'll deprecate the Rhino version. But for now, at least, we need to continue to support Rhino.

**Comment by subash1** [comment]
@hegemonic  is it possible, run jsdoc using JDK for now.??
