### ISSUE TITLE
argparser vs modules

### ISSUE THREAD

**Issue by tmcw** [jsdoc3/jsdoc#943]
JSDoc [has its own argument parsing code](https://github.com/jsdoc3/jsdoc/blob/master/lib/jsdoc/opts/argparser.js): this is pretty rare in node-land, where great, heavily tested and proofed parsers like [yargs](https://www.npmjs.com/package/yargs) and [minimist](https://github.com/substack/minimist) are available.

**Comment by hegemonic** [comment]
True, but the current code works well and requires very little maintenance. I'm not going to replace this code just for the sake of replacing it.
