### ISSUE TITLE
Caption for tag @example not working as documented

### ISSUE THREAD

**Issue by akloeber** [jsdoc3/jsdoc#944]
The example at http://usejsdoc.org/tags-example.html suggests that a caption can also be given after the `@example` keyword (in addition to wrapping it in `<caption>` tags which works as expected) but the following snippet wraps the caption *"How to call it?"* inside the highlighted box when compiled through jsdoc:
```js
/**
 * Function foo
 * @return {string} returns always 'bar'
 *
 * @example How to call it?
 * var val = foo();
 */
function foo() {
  return 'bar';
}
```
Is this supposed to work or is this an error in the documentation?

__Environment:__
JSDoc 3.3.0-beta2
node v0.12.0
MAC OS X 10.10.2

**Comment by hegemonic** [comment]
This is a documentation error. It looks like the `<caption>` tag is either missing or is getting stripped out when we generate the HTML files. I'll fix it.

(In the future, please file doc issues over in the [documentation repo](https://github.com/jsdoc3/jsdoc3.github.com/issues). Thanks!)

**Comment by hegemonic** [comment]
Fixed in the [documentation repo](https://github.com/jsdoc3/jsdoc3.github.com).
