### ISSUE TITLE
Enums with numeric keys cause TypeError

### ISSUE THREAD

**Issue by lazd** [jsdoc3/jsdoc#946]
JSDoc doesn't seem to like this:

```js
/**
 * Enum with numeric keys.
 * @enum {string}
 */
var NumericEnum = {
    0: 'Zero',
    1: 'One'
};
```

Version: #master@3f1ecac83a15e8ec3c4feb5b312f536775802b93

**Comment by hegemonic** [comment]
Fixed on master and releases/3.3. (Apologies, but I overlooked your test fixture for this one.)
