### ISSUE TITLE
Overly verbose documentation of object parameters.

### ISSUE THREAD

**Issue by Gisleburt** [jsdoc3/jsdoc#951]
(Originally mistakenly reported on krampstudio/grunt-jsdoc#123)

Take the documentation of the following method:

```javascript
/**
 * Make a GET request to the API service
 * @param apiRequest {ApiRequest} Options for the get request
 * @param apiRequest.url {string} The url to request
 * @param apiRequest.data {{}} Any data to send to the url
 * @param apiRequest.callback {function} The callback to return data to
 * @param apiRequest.method {string} Any data to send to the url
 * @memberOf! ApiService
 * @access private
 */
var ajax = function (apiRequest) {
    ...
};
```

This produces rather brilliant documentation:

![Full documentation](http://i.imgur.com/SGujLkK.png)

Note that ApiRequest is a TypeDef, that is defined in another file but that JSDoc recognises in the Type column and will link to this:

![ApiRequest TypeDef](http://i.imgur.com/IJdwC7B.png)

```javascript
/**
 * @typedef {Object} ApiRequest
 * @property url      {string}   The url to request
 * @property data     {Object}   Any data to send to the url
 * @property callback {function} The callback to return data to
 * @property method   {string}   Any data to send to the url
 */
```

So it would seem reasonable that the author wouldn't have to document every parameter of the ApiRequest object. 

However, if we remove those lines:

```javascript
/**
 * Make a GET request to the API service
 * @param apiRequest {ApiRequest} Options for the get request
 * @memberOf! ApiService
 * @access private
 */
var ajax = function (apiRequest) {
    ...
};
```

Then the documentation is missing the deeper explanation:

![Missing documentation](http://i.imgur.com/OWQZzrd.png)

It seems that JSDoc could parse this information at least one level deeper without the commenter having to duplicate each property of the object.

This could be overridden if the commenter documents any single parameter of the object so that they could tell the reader that only part of the object is relevant.

**Comment by hegemonic** [comment]
I think you're asking for the default template to copy all the properties from the type `ApiRequest` to the parameter `apiRequest`.

I'm closing this issue because it's very difficult to add features of this sort to JSDoc's current default template. However, I've opened a new issue against the Baseline template (hegemonic/jsdoc-baseline#150), which will eventually become the new default template for JSDoc. Thanks for the suggestion!
