### ISSUE TITLE
latest master gives segfault in ubuntu 14.04 64bit

### ISSUE THREAD

**Issue by phun-ky** [jsdoc3/jsdoc#956]
Running this line:

    jsdoc --package package.json -c .jsdocrc ./doxify/ -r docstarget -l

With `Node v0.12.0`, ubuntu 14.04 and `JSDoc 3.4.0-dev (Wed, 18 Feb 2015 03:07:23 GMT)`

Gives this error:
`[1]    18937 segmentation fault (core dumped)  jsdoc --package package.json -c .jsdocrc ./doxify/ -r docstarget -l`

EDIT:

Getting the same result with `JSDoc 3.3.0-beta1 (Wed, 21 Jan 2015 17:41:43 GMT)`

**Comment by hegemonic** [comment]
Hmmmm. It shouldn't be possible for JSDoc to trigger a segfault.

I have a bunch of questions to try to narrow this issue down:

1. What (if anything) changed before you started seeing this error? For example, did you upgrade Node.js?
2. Do you know whether you get a segfault with other versions of Node.js?
3. Do you get a segfault when you run other Node.js apps?
4. If you just run `jsdoc`, with no arguments, what output do you get?
5. If you run `jsdoc` with the `--debug` flag, what output do you get?

**Comment by phun-ky** [comment]
1. no
2. have not tried 
3. no
4. will try tomorrow when i'm back at the office
5. see 4.

thanks for the quick reply, will get back to you

**Comment by hegemonic** [comment]
@phun-ky Did you get a chance to follow up on this?

**Comment by hegemonic** [comment]
Closing due to lack of information.

**Comment by phun-ky** [comment]
Sorry , will come back with more information asap :/


Sendt fra en Samsung Mobil.

<div>-------- Opprinnelig melding --------</div><div>Fra: Jeff Williams <notifications@github.com> </div><div>Dato:23.03.2015  17:29  (GMT+01:00) </div><div>Til: jsdoc3/jsdoc <jsdoc@noreply.github.com> </div><div>Ko: Alexander Vassbotn Røyne-Helgesen <alexander@phun-ky.net> </div><div>Emne: Re: [jsdoc] latest master gives segfault in ubuntu 14.04 64bit (#956) </div><div>
</div>Closing due to lack of information.

**Comment by phun-ky** [comment]
Hm, It's working now with  `JSDoc 3.3.0-beta1`.. weird. I will create a new issue if this arises again
