### ISSUE TITLE
add support for @package access

### ISSUE THREAD

**Issue by myphysicslab** [jsdoc3/jsdoc#962]
In addition to the @private and @protected tags, closure compiler also supports @package, which corresponds to the notion from Java of "package private":
https://developers.google.com/closure/compiler/docs/js-for-compiler

> Marks a member or property as package private. Only code in the same directory can access names marked @package. In particular, code in parent and child directories cannot access names marked @package.

It would be great for JSDoc to add this if not too difficult.  I see @package listed in issue #605, but no separate issue for it.  For me, just being able to exclude items marked @package from the JSDoc output would be useful.

**Comment by hegemonic** [comment]
Yep, this one is on the list of tags to implement. I'll try to prioritize this one.

**Comment by vickychijwani** [comment]
This would be great to have. My use-case is the same as @myphysicslab's.

**Comment by hegemonic** [comment]
Fixed on master. The `@package` tag will be supported in JSDoc 3.5.0.
