### ISSUE TITLE
@see tag reference to constructor not working

### ISSUE THREAD

**Issue by myphysicslab** [jsdoc3/jsdoc#963]
A  @see tag that references a constructor does not result in a working link.  I'm able to reference the constructor using @link, but not @see.

Here is an example.  The @link to the constructor and the @see tag for the method both work, but the @see tag to the constructor does not.
```javascript
/** Returns the normal of the "special edge" of the {RigidBody} that owns this {Edge},
in world coordinates. A normal is a unit-length vector that is perpendicular to the
{Edge}. See the section "Special Edge for Proximity Testing" in {@link
myphysicslab.lab.engine2D.RigidBody}.
@see myphysicslab.lab.engine2D.RigidBody the section "Special Edge for Proximity
    Testing"
@see myphysicslab.lab.engine2D.RigidBody#getSpecialEdge
@method
@return {!myphysicslab.lab.util.Vector} the normal of the "special edge" of the
{RigidBody} that owns this {Edge}, in world coordinates
*/
Edge.prototype.getSpecialNormalWorld;
```

Here is the generated HTML for the @see tags:
```HTML
    <dt class="tag-see">See:</dt>
    <dd class="tag-see">
        <ul>
            <li>myphysicslab.lab.engine2D.RigidBody the section "Special Edge for Proximity
    Testing"</li>
        
            <li><a href="myphysicslab.lab.engine2D.RigidBody.html#getSpecialEdge">myphysicslab.lab.engine2D.RigidBody#getSpecialEdge</a></li>
        </ul>
    </dd>

```

**Comment by hegemonic** [comment]
I'm 99.9% sure that this is because you have text after `myphysicslab.lab.engine2D.RigidBody`. If you remove that text, everything should work.

Or you could do this, which would use the extra text as the link text: `@see {@link myphysicslab.lab.engine2D.RigidBody the section "Special Edge for Proximity Testing"}`
