### ISSUE TITLE
Clarification: What should we do to mark what should be present on the generated index.html?

### ISSUE THREAD

**Issue by phun-ky** [jsdoc3/jsdoc#967]
Currently, the output from jsdoc gives us a bunch of html files including an index.html-file. In the index file, there's a heading and a navigation, but no content. What do I do to generate content on that page? Does it have to be injected manually by the template, or am I missing something?

> To clarify, all files are documented, but nothing beside the navigation reflects that on the index page

Update: I see now that currently, the only way to generate something in the index.html file, is to include a README.md file. Maybe I'm conflicting about this, and we need something to identify the core/main file (in my case, the core javascript file)?

**Comment by hegemonic** [comment]
You're correct--that's the way the default template works. If you want to identify the main JS file, you'll need to include that information in the README. (Or you can customize the template to show something different on the index page.)
