### ISSUE TITLE
Adding memberof tag igonre all members and methods of class

### ISSUE THREAD

**Issue by houssemFat** [jsdoc3/jsdoc#968]
Hello , I'm using the documentation for my files 
```
       /**
         * @class IssueClass
         * @extends PX.Modules.Backbone.BaseView
         * @type {Backbone.View}
         */
      var IssueClass = BaseView.extend(
            /** @lends IssueClass.prototype */
            {
                /**
                 * @type {String}
                 */
                className: 'product-item-container',
                /**
                 *  @public
                 * @param number
                 */
                vote : function (number){
                    this.model.set ('vote', this.model.get('vote') + number) ;
                    this.$el.find ('#vote_count').html (this.model.get('vote'));
                },
            });
        // extends backbone
        return IssueClass;
```

result is ok :

![result_without_member_of](https://cloud.githubusercontent.com/assets/5431172/6846542/60516736-d3bf-11e4-9920-dcc9f7789017.png)

But after adding '@memerOf' to add my class to a namespace 
```
       /**
         * @class IssueClass
         * @memberof PX.Application.Views
         * @extends PX.Modules.Backbone.BaseView
         * @type {Backbone.View}
         */
````

![add_member_of](https://cloud.githubusercontent.com/assets/5431172/6846596/a61dd466-d3bf-11e4-8689-ace7252988be.png)

Result (all members and methods are gone): 

![result_with_member_of](https://cloud.githubusercontent.com/assets/5431172/6846543/60518004-d3bf-11e4-99d3-d63702220bb0.png)

**Comment by hegemonic** [comment]
That's because the `@lends` tag now contains the wrong namepath. Try `/** @lends PX.Application.Views.IssueClass.prototype */`.

**Comment by houssemFat** [comment]
Thank you :+1: it works
