### ISSUE TITLE
when a typedef is inside a module, return types stop linking to the type definition

### ISSUE THREAD

**Issue by lukeapage** [jsdoc3/jsdoc#969]
In the following example, when jsdoc is generated (with the default template and docstrap) there is no link from the return type to MyType.

If I remove the module definition at the start it fixes it.

```
/** @module my/module */

/** @typedef {Object} MyType
    @property {string} prop
*/

/** 
  * My class
  * @class
  */
function Func() {
}

/**
   @returns {MyType} the return type
  */
Func.prototype.myfunc = function() {
};
```

I've tried prefixing MyType with the module and it doesn't help.

**Comment by hegemonic** [comment]
This is not exactly obvious, but a typedef inside a module has `inner` scope by default. So this will work to link to `MyType`:

```js
/**
 * @returns {module:my/module~MyType} the return type
 */
Func.prototype.myfunc = function() {};
```

If you prefer, you can add a `@static` tag to the typedef, and you can then link to it as `module:my/module.MyType`.

**Comment by manugb** [comment]
Hey guys it would be nice to have if you parse the @returns or @param {module:my/module~MyType}
so when you show the link it only says MyType and not module:my/module~MyType

**Comment by jtq** [comment]
Alternatively you can just mark the inner typedef as `@global` and just refer to it as `{MyType}` anywhere you like, if you don't mind littering your global namespace with module-specific types.

This is irritating though - if inner typedefs are listed in the JSDoc documentation page for a module, what reasonable rationale is there for not *linking* to that typedef definition when it's used in JSDoc comments in that same module?
