### ISSUE TITLE
Escaping JSDoc comments within another JSDoc comment

### ISSUE THREAD

**Issue by srad** [jsdoc3/jsdoc#971]
You can see my issue on Stackoverflow: http://stackoverflow.com/questions/29333830/jsdoc-comment-within-a-jsdoc-comment

Can there be some kind of convention to properly escape a nested JSDoc comment within an ```@example``` tag?
Of course the nested closing comment tag needs to be escaped to prevent interference with the outer JSDoc comment.

**Comment by hegemonic** [comment]
Duplicate of #821.
