### ISSUE TITLE
Interface not generating files

### ISSUE THREAD

**Issue by chrilith** [jsdoc3/jsdoc#974]
Hi,

I'm trying to generate a file for an interface.
The simplest example is to take the one from the documentation:
http://usejsdoc.org/tags-interface.html

The virtual comments for the "Color" interface are not generated if I copy past the code to one of my files.
If I change @interface to @class, the file is generated.

Any clue?
Thanks

**Comment by hegemonic** [comment]
What version of JSDoc are you running? The `@interface` tag is only supported in fairly recent builds of JSDoc 3.3.0.

**Comment by chrilith** [comment]
Ah sorry, indeed I forgot to give the version. Here is what is in my package.json file:

"jsdoc": "^3.3.0-beta3"

Yesterday I did an "npm update" in order to generate the doc.

Thanks!

**Comment by chrilith** [comment]
Ok, it is me. I'm using the jaguars theme. using the default theme, interfaces are correctly generated!

**Comment by gburghardt** [comment]
I'm using 3.3.0-beta3 as well, and I can't get `@interface` flags to properly generate documentation. I copied and pasted the interface example in the JSDoc site. It showed up under "Globals" in the default theme, with no information about the `rgb` method. Is there a nightly build of JSDoc that supports this flag newer than beta3 then?
