### ISSUE TITLE
Sometimes an accidental double module definition puts jsdoc in an infinite loop

### ISSUE THREAD

**Issue by lukeapage** [jsdoc3/jsdoc#975]
I accidentally ended up with a code file

```
/**
  * @module example/b/c
  **/
/**
  * @module example/b/c
  **/
```

the strange thing is that this didn't cause a problem until I added an extra jsdoc on a function in a unrelated file. It seemed that no matter what function I added jsdoc for (I tried disabling different functions on or off) once the unrelated file count went over a certain amount, jsdoc hung.

I debugged..
![image](https://cloud.githubusercontent.com/assets/309321/6965758/270178c8-d954-11e4-8b6c-c102f397585c.png)

and to my surprise found a unrelated file was causing the problem, spotted the double module definition and fixed it.

I was using the latest master.

It should probably warn or error when you have a double module definition in a file? or that loop above should protect itself against infinite recursion and error with the id causing the problem?

I guess this is low priority unless you know an easy fix.. thought I'd report it anyway.

**Comment by lukeapage** [comment]
p.s. to be clear when debugging it was stuck in that while loop with doc === doc.

**Comment by hegemonic** [comment]
Fun! Thanks for investigating the cause of this issue. I think the right solution is to prevent the infinite loop.

**Comment by hegemonic** [comment]
I couldn't reproduce this, but I put some code in place to guard against the infinite loop. Hopefully that'll prevent others from experiencing the same problem.

If you run into this again, please feel free to file a new issue.

**Comment by cppctamber** [comment]
I have been having this issue all day today, using version JsDoc 3.4.0. Presently using grunt to run it as a task. I did manage to get it work once today, but after editing a few file's @property tags it no longer works again. Reverting to the file versions where it worked before did not solve the issue :(

**Comment by lukeapage** [comment]
@cppctamber is it definitely the same issue - e.g. an infinite loop in this place, caused by duplicate module tags? If you can get a repro case I think it would be worth sticking into a new issue.
