### ISSUE TITLE
global.html#<class name> file generated, instead of a file name based on the class/original file name

### ISSUE THREAD

**Issue by dryajov** [jsdoc3/jsdoc#980]
Running jsdoc on my project's files [alicatejs](https://github.com/dryajov/alicatejs), produces a global.html#Repeater.js  file, when parsing app/scripts/alicate/components/repeater.js, instead of the expected Repeater*.html set of files. I'm not sure what causes this behavior; and while my main use of jsdoc is through [gulp-jsdoc](https://www.npmjs.com/package/gulp-jsdoc), running jsdoc on the codebase directly, also generates this file.

To reproduce, clone the project's repo and checkout the `jsdoc_issue ` branch, then do : `npm install && gulp doc`, the files should be generated under `docs/`.

**Comment by hegemonic** [comment]
This is because your JS files don't have a comment block that includes the `@module` tag. Take a look at the [examples on the documentation website](http://usejsdoc.org/howto-commonjs-modules.html#values-assigned-to-module-exports-).

**Comment by dryajov** [comment]
That did it, thank you!
