### ISSUE TITLE
event anchor links fail on ":" in id when using boostrap to render

### ISSUE THREAD

**Issue by tsonny** [jsdoc3/jsdoc#982]
I fixed this in my implementation by making the following change in tag/dictionary/definitions.js

    event: {
        keepsWhitespace: true,
        removesIndent: true,
       // Following is commented out to fix linking error in JSDoc output.
        //isNamespace: true,
        onTagged: function(doclet, tag) {
            setDocletKindToTitle(doclet, tag);
            setDocletNameToValue(doclet, tag);
        }
    },

**Comment by hegemonic** [comment]
This sounds like it may be a bug in the JSDoc template that you're using. If you can reproduce the issue with the default template, please provide a code sample that demonstrates the issue.

Closing this for now.
