### ISSUE TITLE
Module functions not always recognized correctly.

### ISSUE THREAD

**Issue by snoack** [jsdoc3/jsdoc#985]
It seems that only following form is correctly recognized as static module method:
```
/** module mod */

...

/**
 * Foo
 */
exports.foo = function() {};
```

However, often you need to call the exported method also within its module. Therefore you assign it to a local variable. However, following function is recognized as `inner`:
```
/**
 * Foo
 */
function foo() {};
exports.foo = foo;
```

I see that it might be difficult to consider a later assignment. So I tried to do all assignments in one line. But interestingly the following code isn't even recognized as a function:
```
/**
 * Foo
 */
let foo = exports.foo = function() {};
```

**Comment by hegemonic** [comment]
The [Use JSDoc page on CommonJS modules](http://usejsdoc.org/howto-commonjs-modules.html) has some information that should help you out with this issue. In short, you'll probably need to use the `@alias` tag to provide the correct longname for the exported method.

**Comment by snoack** [comment]
For now I went with @static which does the same in my case but is more
implicit (less verbose). Do you know that the documentation of the jsdoc
source code has the same issue if you would ever run jsdoc on it? And,
frankly I'm not a fan of sacrificing readability of source code for
compatibility with jsdoc, as the source code is read more often.
