### ISSUE TITLE
Feature: jsDoc should have a tag that output generation date and time

### ISSUE THREAD

**Issue by damianof** [jsdoc3/jsdoc#990]
It would be nice to have a tag that allows to output current date time of documents generation, maybe something like @displayGenerationTimestamp

My current need is for the README file. It might be used also in other places. But to give an example here is how I would use it:
README file:
My great title in this file - @displayGenerationTimestamp

The output HTML will show like:
My great title in this file - [2015/04/20 09:43:27 AM ET]

or maybe like 
My great title in this file - [generated on 2015/04/20 09:43:27 AM ET]

The date time format could follow UTC or other standard

**Comment by hegemonic** [comment]
Thanks for the suggestion. I'd rather not add this as a core JSDoc tag. It should be easy to [implement a plugin](http://usejsdoc.org/about-plugins.html#tag-definitions) that defines this tag, though.

**Comment by damianof** [comment]
Thank you Jeff, I appreciated your time answering. I followed your suggestion and implemented a plugin.
Thank you again,
Damiano
