### ISSUE TITLE
Add support for @return {this}

### ISSUE THREAD

**Issue by claudio-silva** [jsdoc3/jsdoc#991]
I do not believe JSdoc currently has any way to document the return type of a method to be the same type as the instance type.
Something like:
```
/**
 * @return {this}
 */
```
This would be very useful for chaining APIs where objects on the chain can inherit methods from a superclass / prototype.
For instance (using ES6 syntax):
```js
class A {
    /**
     * @returns {A}
     */
    x() {
        return this;
    }
}
class B extends A {
    /**
     * @returns {B}
     */
    y() {
        return this;
    }
}
var b = new B();
b.x().y();
```
In this example, the call to `y()` will cause a warning/error (when using a linter or an IDE like Webstorm) because`x()` is annotated to always return type A (which does not contain an `y()` method), when, in this case, `x()` is actually returning type B.
Furthermore, there is no way I can get useful autocompletion from any javascript IDE, as there is currently no way to correctly annotate this kind of return type

**Comment by hegemonic** [comment]
I think `@return {this}` is already "supported" in the sense that it doesn't break anything. What else are you looking for? I can't help you with IDE autocompletion, unfortunately.

**Comment by Delapouite** [comment]
To improve the (lodash)[http://lodash.com] online doc which is generated from the jsdocs blocks in the source, a nice way to indicate that a function is chainable will be a huge gain.

Could a new **@chainable** tag be considered?

https://github.com/lodash/lodash/issues/1077

**Comment by claudio-silva** [comment]
Ok, I'm going to present a very concrete example where currently JSDoc does not generate documentation correctly ("correctly" should be taken in the sense I previously explained).

Put this code into a `test.js` file on an empty folder (note that this is NOT the same code as above):

```js
/**
 * @class
 */
class A {
    /**
     * @returns {A}
     */
    x() {
        return this;
    }
}
/**
 * @class
 * @extends A
 */
class B extends A {
    /**
     * @returns {B}
     */
    y() {
        return this;
    }
}
```
Install the latest JSDoc development version:
```
sudo npm install -g git+https://github.com/jsdoc3/jsdoc.git
```
Now run:
```
jsdoc test.js
```
Then open the generated documentation on the `out` folder, specifically you should open `out/B.html`.

You'll see something like this:

### Class: B
#### B
##### new B()
> Source: test.js, line 16

#### Extends
* A

#### Methods
##### x() → {A}
> Inherited From: A#x
> Source: test.js, line 8

##### Returns:
Type A
##### y() → {B}
> Source: test.js, line 20

##### Returns:
Type B

---

As you can see, Class `B` is described has having a method `x()` that returns `A`, while that method **should** return `B`, because when it is invoked on an instance of `B`, it returns `B`.

---

#### Now that the problem was made explicit, I'm going to suggest a solution:

Let's edit the javascript file, and replace the doc comment of method `x()` with this one:
```js
/**
 * @returns {this}
 */
x() {
  return this;
}
```
Regenerate the documentation.

Now, JSDoc says:

##### x() → {this}
> Inherited From: A#x
> Source: test.js, line 8

##### Returns:
Type this

---

The proposed behavior is for JSDoc to output the return type of `x()` as being `B`.  
Notice that, currently, neither `{this}` nor `this` are output as links, as it happens when JSDoc recognizes the type name (like, for instance, on the return type of `y()`). So, for JSDoc, `this` is currently just dummy text.

---

Now, the suggestion, summarized:

**It would be very useful if JSDoc would recognize `this` as a return type and output `B` as the return type of `x()` on the example above.**

Another possibility would be the creation of a new jsdoc tag, like @Delapouite suggested.

Any kind of solution would be fine for me, as long as it would make JSDoc output the correct type and, as a consequence and added bonus, allow IDEs like Webstorm to follow the lead and provide correct auto-completion and code analysis.

**Comment by hegemonic** [comment]
Automatically changing the return type from `this` to `B` would make the docs _less_ useful. It wouldn't be clear that the method returns the current `B` object rather than a new `B` object. If you want this behavior, I'd suggest [writing a plugin](http://usejsdoc.org/about-plugins.html) to enable it.

I also don't think we need a new tag for this case, because `@return {this}` already works.

**Comment by claudio-silva** [comment]
@hegemonic, I'm sorry to see the way you dismiss this issue so lightly.
I don't want to create a plugin for this. It's not about solving a problem for me only. This is about the Javascript community, for whom this feature would be useful and, as you and the other creators of this documentation system do have the power to influence that community, it would have a very different effect if you would come up with a standard, sanctioned solution for this, as that would have a rippling effect, causing tool makers to incorporate such feature into their products (such as NetBeans and Webstorm).
What I'm asking for is nothing new, it is a feature that already exists in other languages.
For instance:
- The Typescript team is investigating this issue and brainstorming solutions for it, as you can see in [this issue on GitHub](https://github.com/Microsoft/TypeScript/issues/513).
- In Objective-C, we have `instancetype`.
- Scala has `this.type`. See [this article](http://scalada.blogspot.pt/2008/02/thistype-for-chaining-method-calls.html).
- In PHPDocumentor, you can use the `$this` keyword as a function return type. See [this reference](http://phpdoc.org/docs/latest/guides/types.html#keywords). It is a very useful feature that allows you to get correct autocompletion on IDEs (ex: PHPStorm).
PHPDocumentor also defines `self` and `static` which have other meanings, but that may potentially also be useful for use with Javascript.
- I have also submitted a request for this feature to the Facebook's Flow team (see [this issue](https://github.com/facebook/flow/issues/399)).

As for your arguments:

> It wouldn't be clear that the method returns the current B object rather than a new B object.

I must say that this reasoning for dismissal is flawed, as if we were to consider it as being true, then any method that currently is documented as `@returns {X}` is not actually specifying if it is returning the same instance or a new instance of X.
So, should we just drop the `@returns {class}` feature because it "*would make the docs less useful*" ?!
Or should the JSDoc team create some way to disambiguate those situations? (and this is a very common use case).

Furthermore, it seems to me that your argument is, in fact, one more reason to create an annotation (or a special type keyword) do disambiguate that case. We should be able to declare if the function is returning A, a new B or the same B.
We have 3 different cases here and currently JSDoc only allows to document the first case. This does not seem to be a reason to close the issue, but instead it seems, to me, to be a good reason for opening even more issues!

> because @return {this} already works.

Well, it **doesn't work** in any way that the **work** word has a meaning for in the dictionary! I could also write `@return {dummy}` and it would also "work" in the sense you meant.

As I explained before:

> Notice that, currently, neither `{this}` nor `this` are output as links, as it happens when JSDoc recognizes the type name (like, for instance, on the return type of `y()`). So, for JSDoc, this is currently just dummy text.

So, JSDoc is just ignoring it. It may be a typo, a mistake, an error, JSDoc doesn't care, it just ignores it. So, it doesn't really work at all.

I politely and respectfully request that you and your team give some thought to (and consider) this issue. As I said, it's not about solving a pet problem for me; it's about bringing to the Javascript community a feature that, coming from an influential project as yours, would have a rippling cascading effect on that community that would result in better ways for us, developers, to document our code and better tooling on IDEs.

**Comment by shaoner** [comment]
Hi,

I've just come to the exact same issue trying to improve my documentation and I must agree, I cannot find a way to properly express `@return {this}`. 
Until now, I used to do:
```js
/**
 * @return {A}
 */
```

But it's not really clean when inheritance is involved since it looks like methods don't return the same type.
`@returns {this}` doesn't actually work in the expected way. Moreover `this` isn't a type so it should output the class name the method is from.

+1 for the feature.

**Comment by JCMais** [comment]
+1 on this for the same reason than @shaoner, even a new tag ``@chainable`` would be wonderful.

**Comment by FlorianBezagu** [comment]
+1 Would be very useful to be able to tell it returns `this` or it's `chainable`.

**Comment by claudio-silva** [comment]
I've given links above showing that this issue is important to other projects, like TypeScript, for instance. They have been [heavily discussing it](https://github.com/Microsoft/TypeScript/issues/3694) and, finally, they are already implementing it (as you can see [here](https://github.com/Microsoft/TypeScript/pull/4910)), and everybody there agrees it's necessary and important for the correct documentation and validation of code.
I believe the analysis presented on [this latest link](https://github.com/Microsoft/TypeScript/pull/4910) also addresses the concerns you have mentioned above.
So, will you please reconsider and reopen this issue?

**Comment by kruncher** [comment]
+1 for assuming the current type for `@returns {this}`

**Comment by andygeiss** [comment]
+1 please provide inheritance for @returns {this} tags ;-)

**Comment by NemoStein** [comment]
I know this has 3 years already, but the need for this feature still exists.
I'd like to ask if this can be reviewed.

**Comment by fabian-hoffmann-altimi** [comment]
> Automatically changing the return type from `this` to `B` would make the docs _less_ useful. It wouldn't be clear that the method returns the current `B` object rather than a new `B` object. If you want this behavior, I'd suggest [writing a plugin](http://usejsdoc.org/about-plugins.html) to enable it.
> 
> I also don't think we need a new tag for this case, because `@return {this}` already works.

I sincerely hope that people with attitude like this do not work on huge, community-driven projects.
All that OP said is valid. Discussed feature/improvement is still needed.

**Comment by patrick-tolosa** [comment]
Adding my 2 cents for anyone still here in 2020,

Yes this is problematic, but the alternative isn't simple.

1. as mentioned, it's not clear if the function returns a new B or the current B.
2. JS is one of those languages where you can change `this`, making the documentation just wrong as it depends on running context - In fact, `this` is not defined by the function, it's defined by the calling object.

**Comment by solamanhuq** [comment]
I'd like to see this feature added too. VSCode uses JSDoc and having intellisense for this would be huge!

**Comment by demosofa** [comment]
I have problem when I want to created an export type of a callback that I declared in parent class. I created a @callback in the parent class and create @typedef outside of that class to make the @callback global. In child class, I was be able to get the type from import() but the @returns {this} from the @callback still refered to parent class instead of child class. This problem made code completion not show any functions from child class but parent class

**Comment by frnhr** [comment]
Just to add to the [list from the comment above](https://github.com/jsdoc/jsdoc/issues/991#issuecomment-104642530)(from 9 years ago) of other languages that have this feature...

In Python, `self` is equivalent to `this` in JS and some other langs. Python's typing system (mypy) has support for `Self`, ref: https://typing.readthedocs.io/en/latest/spec/generics.html#self
