### ISSUE TITLE
Methods under 'memberof' classes are scoped static

### ISSUE THREAD

**Issue by DNoved1** [jsdoc3/jsdoc#994]
Example code:

```javascript
/** All the classes. */
var classes = {}

/** @memberof classes */
class Class {
    /** This method will be labelled as static in generated documentation. */
    foo() {}
}
```

The incorrect scope seems to be added in name.js~resolve, due to neither the name field nor the memberof field including a '#' (although code.name does, however it is not checked), so resolve defaults to static scope.

Not too sure where the best place to fix this would be.

**Comment by hegemonic** [comment]
Good catch! I'll have to take a closer look at this one.

**Comment by hegemonic** [comment]
Fixed on master.
