### ISSUE TITLE
Class defined inside closure not documented

### ISSUE THREAD

**Issue by itsravenous** [jsdoc3/jsdoc#995]
Similar to #993, but the below code results in the class not being documented at all. From what @hegemonic mentioned in #993, I'm wondering whether the fact that the function is anonymous is the issue (i.e. if it was named it could be used as a prefix to the class identifier). I'm aware that explicitly naming the class and adding `@memberof` on the method would work, but I prefer to avoid the extra tags if possible. I realise I'm being lazy/greedy here, but I do think that in general the "automatic" behaviour is much preferable in terms of maintenance.

```javascript
(function () {
    /**
     * @class
     */
    var MyClass = function () {

    };

    /**
     * An instance method
     * @return {void}
     */
    MyClass.prototype.myMethod = function () {

    };
})()
```

**Comment by hegemonic** [comment]
Yes, the anonymous function is the issue here.

Sorry, but without additional tags, there's no way for JSDoc to know that this class is available outside of the anonymous function.
