### ISSUE TITLE
jsdoc stuck on "Generating output files"

### ISSUE THREAD

**Issue by teeohhem** [jsdoc3/jsdoc#998]
In parsing about a 300 file codebase, the jsdoc parsing happens just fine, but the "generating files" phase gets stuck and never completes. There is no additional information using the --debug flag. I am using 3.3.0-beta3. I reverted back to 3.3.0-alpha11 and everything works just fine.

**Comment by hegemonic** [comment]
Can you provide access to the files that are causing problems? If not, there's no way for me to investigate this issue.

**Comment by hegemonic** [comment]
Closing due to lack of information. I'll be happy to investigate if you can give me a way to reproduce the issue.
